### ISSUE TITLE
Has anyone released standalone binaries for Windows and Linux?

### ISSUE THREAD

**Issue by JoeUX** [Cyan4973/xxHash#101]
Hi all – I saw all the different programming language implementations on the xxHash website. Is anyone posting binaries for standalone programs, presumably a CLI? I'm most interested in programs I could run on Windows 10, newer releases of Fedora/RHEL, and Alpine.

All I've seen so far are some online xxHash sites, but I'd rather run local.

Any tips on which library implementations would be easiest to compile into a program on my own? Maybe the Go versions?

**Comment by Cyan4973** [comment]
Are you able to compile source code using `make` ?

**Comment by JoeArizona** [comment]
No, that just yields a long error message, as usual. (I didn't know it was even an option in this case – I thought xxHash was just a library.) I can rarely get make/gcc to work on Windows. In this case the error is:

> "C:\MinGW_64_6.3.0_POSIX_SJLJ\bin\mingw32-make.exe"
> process_begin: CreateProcess(NULL, uname, ...) failed.
> mingw32-make: Makefile:160: pipe: No error
> cc      -O3 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef    xxhash.c xxhsum.c -o xxhsum.exe
> process_begin: CreateProcess(NULL, cc -O3 -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef xxhash.c xxhsum.c -o xxhsum.exe, ...) failed.
> make (e=2): The system cannot find the file specified.
> Makefile:56: recipe for target 'xxhsum' failed
> mingw32-make: *** [xxhsum] Error 2

The only make executable I can find in the MinGW distro I downloaded is `mingw32-make.exe`, as seen above.

**Comment by Cyan4973** [comment]
Windows is indeed a difficult platform for `make`.
I tend to use [msys2 environment](http://www.msys2.org/), which works best for me.
It also allows installation on MinGW64 via `pacman`.

Alternatively, if you like Visual, you just have to create a console application, include `xxhash.c` and `xxhsum.c`, and it should produce the desired binary.

Your initial question also referred to `Fedora/RHEL, and Alpine`, which should work well with `Makefile`.
