### ISSUE TITLE
Add support for Windows 10 UWP apps.

### ISSUE THREAD

**Issue by VijayChavda** [Cyan4973/xxHash#106]
From the NuGet Package Manager:

> Package System.Data.HashFunction.xxHash 1.8.2.2 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586).

**Comment by t-mat** [comment]
@VijayChavda thanks for the report!
But since nuget package is maintained by @brandondahler, could you consult at the following project's issue board firstly?
https://github.com/brandondahler/Data.HashFunction
