### ISSUE TITLE
Website link on main github page is broken

### ISSUE THREAD

**Issue by vivmaha** [Cyan4973/xxHash#110]
__http://www.xxhash.com__ should probably be changed to __http://cyan4973.github.io/xxHash__

![image](https://user-images.githubusercontent.com/6677347/29533355-51010ab4-8666-11e7-83b1-4802273f53fe.png)

**Comment by Cyan4973** [comment]
This choice is intentional.
http://www.xxhash.com currently redirects toward http://cyan4973.github.io/xxHash .
This gives us flexibility to change it in the future.
