### ISSUE TITLE
Limit source line length to 120 characters

### ISSUE THREAD

**Issue by jvriezen** [Cyan4973/xxHash#115]
In the development environment we've established where I'm trying to use XXHASH, we have a hard limit on source line length of 120 characters.   There are a few lines in the source which are longer than this.  Can these be adjusted to use additional lines (some preprocessor statements will require backslash to split a line)

**Comment by t-mat** [comment]
@jvriezen Could you provide more information of your develop environment?
There is a possibility to add such limitation to our CI test to support the limitation.

@Cyan4973 we can check long lines by the following command

```
cd xxhash
find . -type f -name '*.c' -o -name '*.h' | while read -r filename; do awk 'length > 120 {print FILENAME "(" FNR "): " $0}' $filename; done
```

This pattern may help CI test.

**Comment by Cyan4973** [comment]
I've updated source code in `dev` branch,
so that no line of code in `*.c` or `*.h` is >= 120 chars.

Thanks to @t-mat script, which made it easy to find the targeted lines !

**Comment by jvriezen** [comment]
Thank you very much.   My development platform is on an IBM i using ILE/C.   It has the option of compiling from a more conventional stream file where the line length would not be an issue, or from a 'old school'  source physical file, which has fixed length records.    Our development environment has settled on 120 as the fixed length.   My explanation probably raised more questions than it answers....
