### ISSUE TITLE
Another implementation for Ruby

### ISSUE THREAD

**Issue by konsolebox** [Cyan4973/xxHash#122]
Hi,

5 months ago I created an alternative wrapper for xxHash in Ruby. Please consider adding it to http://cyan4973.github.io/xxHash/#other-languages.

The difference of it compared to the existing wrapper is that it stays consistent with how the Digest functions are implemented. I.e., `digest` produces a string instead of a number. I added `idigest` for producing the number instead. `hexdigest` is also implemented. The string produced by `digest` and `hexdigest` are big-endian based.

Homepage: https://rubygems.org/gems/digest-xxhash
Source: https://github.com/konsolebox/digest-xxhash-ruby
Auto-generated documentation: http://www.rubydoc.info/gems/digest-xxhash/0.0.3

**Comment by Cyan4973** [comment]
Thanks for the notification @konsolebox .
Your project has been added to the list on xxhash homepage.
Regards

**Comment by konsolebox** [comment]
Nice. Thank you too.
