### ISSUE TITLE
Analog of CRC32 combine inversion

### ISSUE THREAD

**Issue by borgotta-g** [Cyan4973/xxHash#125]
Hi.
Please excuse me for asking something I understand only barely. I am not a programmer myself, but trying to understand applicability of your algorithm for needs of my project.
We have a working program that uses crc32 for means of data resiliency. Crc32 combine is used for a read-modify-write cycle. As you can understand both forward and inverse is used to avoid rehashing of full data block.
As far as I have been told, current code with crc32 able to do something like `crc32(AB) = crc32(A) [combine] crc32(B)` and, more importantly, `crc32(AZB) => crc32(AXB)` is done faster than full `crc32(AXB)` rehashing, because you can do `crc32(AZB) [combine] ( crc32(Z) [xor] crc32(X) ) = crc32(AXB)`. That is, while Z < (A+B). Again, as I've been told, xxHash does it differently: `xxHash(AB) = xxHash(xxHash(A),B)`, and because of that, the reversal of xxHash is impossible.
Is my understanding correct? Or is that possible to make read-modify-write cycle withount full block rehashing with xxHash?

**Comment by Cyan4973** [comment]
Hi @borgotta-g 

Indeed, crc combination is a crc feature.
For an in-depth look at how it works, I recommend [this excellent answer](https://stackoverflow.com/questions/23122312/crc-calculation-of-a-mostly-static-data-stream/23126768#23126768) from @madler .

xxHash doesn't offer such guarantee.
I haven't looked in depth to this question, but maybe internal loop is combinatorial at stripe boundaries. That's not guaranteed at this stage. Besides, should xxHash be combinatorial at stripe granularity, this would require to work with internal accumulators, which is not the same as combining hash results.

Anyway it's clearly not combinatorial at byte granularity.

**Comment by borgotta-g** [comment]
Thanks, @Cyan4973!
So the only solution for us would be a full rehash every modify time, correct?
Also I wonder, is there any acceleration of calculation if large portion of data block is consisting of zeroes?

**Comment by Cyan4973** [comment]
Yes, in absence of a more thorough investigation, that's the surest way to proceed.

Regarding portions of zeroes, it is not clear if there is a way to specialize that.
In presence of zeroes, xxHash still does operations on internal accumulators, so it's not "transparent". Maybe there's a way to simplify multiple rounds into a single more complex one producing same effect, but that's not easy to tell. 
xxHash is non linear : it still performs a `rotation` followed by a `multiplication`. The `rotation` part breaks linearity. So it's unclear at this stage if there is a way to summarize multiple rounds.
