### ISSUE TITLE
Is this library threadsafe?

### ISSUE THREAD

**Issue by nixomose** [Cyan4973/xxHash#133]
There's nothing obvious to lead me to believe that it is not thread safe (like a initialization section) but I can't find anywhere where it explicitly states that the hash function XXH64 is threadsafe. Can you confirm this?

**Comment by Cyan4973** [comment]
`XXH64()` is totally thread safe, using no resource beyond its own small stack-based variables.

Streaming variant `XXH64_reset()` is multi-threadable.
It requires a state `XXH64_state_t`, each thread shall have its own state.

**Comment by nixomose** [comment]
very cool, thanks for the quick response.
