### ISSUE TITLE
Warning building on Windows VS 2017

### ISSUE THREAD

**Issue by madscientist** [Cyan4973/xxHash#139]
Minor warning compiling on Windows (VS 2017):
```
xxhash-0.6.5\xxhsum.c(220): warning C4267: 'initializing': conversion from 'size_t' to 'U32', possible loss of data
```
Code in question:
```
U32 nbh_perIteration = ((300 MB) / (bufferSize+1)) + 1;  /* first loop conservatively aims for 300 MB/s */
```
It appears that since `bufferSize` is `size_t` the entire expression on the RHS is promoted to `size_t`.

**Comment by Cyan4973** [comment]
Thanks for notification @madscientist, the diagnosis looks correct to me !

**Comment by Cyan4973** [comment]
Fixed in latest `dev` branch update
