### ISSUE TITLE
Switch to remove "loading" message in xxhsum

### ISSUE THREAD

**Issue by gingerbeardman** [Cyan4973/xxHash#141]
I need to parse the output of the `xxhsum` command in a bash script.

Currently, it displays a loading message and then overwrites that text with the hash. This gets in the way of my parsing.

I also wonder what the point of the "loading" message is? It seems extraneous, mh5sum etc do not have such a message.

**Comment by ifduyue** [comment]
loading notifications are written to stderr, while results are to stdout.
Discard stderr and you'll get what you want.

```bash
xxhsum FILES... 2>/dev/null
```
or

```bash
xxhsum FILES... | results-processing-cmd
```

**Comment by gingerbeardman** [comment]
`xxhsum FILES... 2>/dev/null` works for me - thank you!
