### ISSUE TITLE
Compatibility between versions?

### ISSUE THREAD

**Issue by mykaul** [Cyan4973/xxHash#143]
I'd like to upgrade Gluster from using 0.62 to 0.65. Do we have any proof that 0.62 and 0.65 provide the same hashes for a given key?

**Comment by ifduyue** [comment]
Yes, same hashes for a given key.

https://github.com/Cyan4973/xxHash/compare/v0.6.2...v0.6.5
No algorithm changes in those commits.

Also have a look at https://github.com/Cyan4973/xxHash/issues/34#issuecomment-169176338

**Comment by Cyan4973** [comment]
@ifduyue answer is correct.

`xxhsum` includes a self-test which ensures that hash values remain the same whatever the version and the platform.
