### ISSUE TITLE
xxhash.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object

### ISSUE THREAD

**Issue by amadio** [Cyan4973/xxHash#147]
This is a bug received downstream by Gentoo at https://bugs.gentoo.org/666258.
Please see further details at the link above.

```
>>> Compiling source in /var/tmp/portage/dev-libs/xxhash-0.6.5/work/xxHash-0.6.5 ...

make -j8 AR=x86_64-pc-linux-gnu-ar CC=x86_64-pc-linux-gnu-gcc 
x86_64-pc-linux-gnu-gcc -O2 -march=native -pipe -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef   -c -o xxhash.o xxhash.c
x86_64-pc-linux-gnu-gcc -O2 -march=native -pipe -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef  -Wl,-O1 -Wl,--as-needed  xxhash.o xxhsum.c -o xxhsum
compiling static library
compiling dynamic library 0.6.5
x86_64-pc-linux-gnu-gcc -O2 -march=native -pipe -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef  -Wl,-O1 -Wl,--as-needed -shared -fPIC  xxhash.o -Wl,-O1 -Wl,--as-needed -shared -fPIC -Wl,-soname=libxxhash.so.0 -o libxxhash.so.0.6.5
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: xxhash.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by amadio** [comment]
Actually, nevermind. It looks like this has been introduced downstream. Might be worth taking a look at recent patches in Gentoo in any case. Sorry for the noise.

**Comment by Cyan4973** [comment]
I'm not completely sure what was going wrong in this case.
The dynamic library `libxxhash` is compiled with `-fPIC` by default.
Hence, it should not be missing.

If I understand correctly, someone apparently removed it, by using the objects from the static library (compiled without `-fPIC`) as basis for the dynamic library, hence missing the `-fPIC`.

I also note in the thread that : 

> The upstream Makefile has more problems than the ones I solved

Well if the claim could be substantiated with specific issues, it would prove more useful to improve the `Makefile`.

**Comment by jer-gentoo** [comment]
xxhash.c is compiled three times with the current Makefile. The changes I introduced ensured that the object file was compiled just a single time, but some "versions" of Gentoo's linker opaquely inject -pie which then of course fails on the missing -fPIC requirement for the object file.
