### ISSUE TITLE
Rationale for the constants?

### ISSUE THREAD

**Issue by jdemeyer** [Cyan4973/xxHash#151]
While reading

https://github.com/Cyan4973/xxHash/wiki/xxHash-specification-(draft)

I noticed that the constants like `static const u64 PRIME64_1 = 11400714785074694791ULL;` are just "magically" given without justification. It would be good to know why those numbers are chosen the way they are, or whether the values don't matter and any randomly chosen odd number would work.

**Comment by Cyan4973** [comment]
Sure,
generally speaking, they feature a good mix of bits 1 and 0, neither too regular, nor too too twisted. They are also prime numbers, at least for the 32-bits ones. I don't remember exactly for 64-bits ones.
Being prime numbers is not strictly required (the only requirement is for these numbers to be odd), but it certainly doesn't hurt.
And finally, they featured good behavior during tests, which is the most important criteria.

I could add a few notes on this topic in the specification.

**Comment by Cyan4973** [comment]
The specification has been updated in `dev` branch to provide a rationale for selection of constants : https://github.com/Cyan4973/xxHash/blob/dev/doc/xxhash_spec.md
