### ISSUE TITLE
Possible to view file sizes in hash output, or use a custom delimiter?

### ISSUE THREAD

**Issue by CalebHawthorne** [Cyan4973/xxHash#159]
Happy Thanksgiving, and thank you for a wonderful tool that I use almost daily.

I was curious if there is any way to print the file sizes in the resulting hash output, along with the file path? I'm not familiar with the source format, unfortunately, otherwise I would try to add it myself. I thought it might be possible in either Powershell, or possibly a batch file, but the advantage to having it print this in the results is not having to do anything externally.

I was also curious if there was a way to add a custom delimiter to the results, since unfortunately trying to parse the output wouldn't work with the default delimiter (space). 

Thank you again for a wonderful tool, and I apologize in advance if I did anything wrong (this is my first time ever posting on Github).

**Comment by Cyan4973** [comment]
You are on right track.
Yes, a fork would be relatively easy to create,
in which case, all it takes is to modify #L674.

Something like : 
```C
U64 const fileSize = BMK_GetFileSize(fileName);
DISPLAYRESULT(" , %s , %llu \n", fileName, fileSize);
```

would likely produce the wanted outcome.
