### ISSUE TITLE
cmake: unofficial_cmake does not allow -DXXH_PRIVATE_API

### ISSUE THREAD

**Issue by senior7515** [Cyan4973/xxHash#163]
While adding xxhash to a cmake project using external project add 

```
  EXTERNAL_PROJECT_ARGS
    CONFIGURE_COMMAND
      ${CMAKE_COMMAND}
      -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
      -DBUILD_XXHSUM=OFF
      -DBUILD_SHARED_LIBS=OFF
      <SOURCE_DIR>/cmake_unofficial
    INSTALL_COMMAND
      ${make_command} install && ${CMAKE_COMMAND} -E copy <SOURCE_DIR>/xxhash.c <INSTALL_DIR>/include/xxhash.c
    URL https://github.com/Cyan4973/xxHash/archive/v0.6.5.tar.gz
    URL_MD5 6af3a964f3c2accebce66e54b44b6446)
```

I had to override the install command to include the xxhash.c 

If enabled, the `install()` the install target does not include xxhash.c

A secondary solution would be to allow for `-DXXHASH_INLINE_ONLY_API` that can add a
`dummy.cc` target (empty) file and *not* build any `libxxhash.a`. 

I'm happy to push a patch for the first part of this issue. 

.alex

**Comment by senior7515** [comment]
to be clear, when you do `make install` for example, the contents of `include` are:

`include/xxhash.h` and *not* `include/xxhash.h, include/xxhash.c`

**Comment by Cyan4973** [comment]
Hi @senior7515, 
the `cmake` build script is community maintained.
I'll be happy to review and merge your patch if it can help your use case.

**Comment by senior7515** [comment]
@Cyan4973  - sure thing no problem. 

One thing I wanted to ask - related to cmake. 

Are you against moving the CMakeLists.txt up one directory? - it makes integrating w/ xxhash simpler. 

for example to integrate `google test` i just do :+1: 

```

... snip ...

  EXTERNAL_PROJECT_ARGS
    URL https://github.com/google/googletest/archive/644319b.tar.gz
    URL_MD5 e4cfcbe80bf32cb8caa8a7666ebc206c)

```

and for xxhash i have to specify `<SOURCE_DIR>/cmake_unofficial` and a configure command, etc. 

It's no big deal - but for future consumers they might find it easier to integrate. 

I'll prepare the patch for this change alone in just a minute.

**Comment by senior7515** [comment]
I posted the patch. let me know about other patches.

A follow up patch would be to add integration test script.

**Comment by senior7515** [comment]
@Cyan4973 no probs. added.
