### ISSUE TITLE
NDEBUG redefined in xxh3.h

### ISSUE THREAD

**Issue by totaam** [Cyan4973/xxHash#178]
This causes this warning (or error with `-Werror`):
```
In file included from xxhash.c:1017:
xxh3.h:50: error: "NDEBUG" redefined [-Werror]
 #define NDEBUG
```

**Comment by Cyan4973** [comment]
Thanks for the report @totaam,
an `#undef` just before will solve this situation.

**Comment by Cyan4973** [comment]
This issue is fixed in latest `dev` branch update.
