### ISSUE TITLE
The benchmark source corresponding to "Presenting XXH3" article.

### ISSUE THREAD

**Issue by leo-yuriev** [Cyan4973/xxHash#183]
Is the benchmark source code available anywhere (["Presenting XXH3" article](https://fastcompression.blogspot.com/2019/03/presenting-xxh3.html))?
I would like to use the same tool for measurements (and may be, if you agree, incorporate ones into 
[HashContest](https://github.com/leo-yuriev/HashContest)).

Regards.

**Comment by Cyan4973** [comment]
Yes, sure @leo-yuriev, that's a good idea.
I need to prep it, so that it becomes more easy to use.
I'll put it in a directory in this repository, and give a note here when it's ready.

**Comment by Cyan4973** [comment]
The benchmark source has been added to the repository, at `tests/bench`.

It's designed to be integrated, and you can select which level you prefer : 
- `main` : command line parser 
- `bhDisplay` : generate scenarios, push the results into `stdout`, designed to be read later as `.csv` import
- `benchHash` : benchmark the requested scenario, returns speed result as `double` expressed as nbHashes / second.
