### ISSUE TITLE
Get rid of unnecessary complications

### ISSUE THREAD

**Issue by czMaxx** [Cyan4973/xxHash#184]
Hello, I've been trying to compile the code with the highest warning level in MSVC and GCC 7 and found several parts that don't fully make sense.

https://github.com/Cyan4973/xxHash/blob/f3e08d7ea9286c2d68ae80607d4120550ee4c7ed/xxhash.c#L384 - why don't you just let it break for case 0 (or omit 0 and use default) and proceed to return XXH32_avalanche(h32); instead of keeping the dead/unreachable code in there? Does it have an impact on the switch itself? Is your goal to enforce the compiler to emit a jump table in preference to an if-chain? In that case, have you tried to hint the compiler with __assume( 0 ) or __builtin_unreachable()?

https://github.com/Cyan4973/xxHash/blob/f3e08d7ea9286c2d68ae80607d4120550ee4c7ed/xxhash.c#L426 - the and operator here is redundant since you're anding the value in the switch statement.

https://github.com/Cyan4973/xxHash/blob/f3e08d7ea9286c2d68ae80607d4120550ee4c7ed/xxhash.c#L996 - I actually don't get it and I think it may be a bug. You refer to the internal mem64 field, but you provide total_len as a parameter. It could be the same after anding the value, however - isn't it supposed to use memsize parameter?

I have few other suggestions, but these are the most obvious to me.

Btw: why on earth do you use size_t for buffer lengths, when you cast them to 32bit in the end? It makes no sense. Since size_t is platform dependent, the hash functions consume different parameters in 32bit and 64bit versions. Yes, it's a corner case (who would ever hash more than 4GB in one shot?), but I'd prefer a fixed-size argument - uint32_t. And another thing: why don't you handle total_len the same way for XXH32 and XXH64? It's not very probable, but just in theory, even the 64bit number may overflow and the check >= 32 may fail. It would be good to choose one size for borh total_len parameters and check whether they wrap around (total_len + len) < total_len to make it completely overflow-proof.

**Comment by Cyan4973** [comment]
If you believe these issues can be improved, an associated patch will be welcomed.

**Comment by easyaspi314** [comment]
>why don't you just let it break for case 0 (or omit 0 and use default) and proceed to return XXH32_avalanche(h32); instead of keeping the dead/unreachable code in there? 

Good idea. This was a way to unroll the original loop which looked like this:

https://github.com/easyaspi314/xxhash-clean/blob/ad30b369b7d08e36cad6069a8ceaf36201dabed7/xxhash32-ref.c#L133-L149

>Btw: why on earth do you use size_t for buffer lengths, when you cast them to 32bit in the end? It makes no sense. Since size_t is platform dependent, the hash functions consume different parameters in 32bit and 64bit versions. 

First of all, in XXH32, the hash only stores 32 bits of the length in the hash. The rest is truncated. There is no underflow, as it is just truncated. The addition of the length at the end is important to reduce the risk of length extension attacks. 

Second of all, we only use `size_t` for indexing. XXH32 is perfectly capable of doing a single shot of `0x100002006` bytes. There is no need to worry about doing 4gb in a single shot for 32-bit because…well…umm…32-bit devices will never ever have something larger than 4gb, it is physically impossible.

> I actually don't get it and I think it may be a bug. You refer to the internal mem64 field, but you provide total_len as a parameter. It could be the same after anding the value, however - isn't it supposed to use memsize parameter?

Yeah, I thought that was a little fishy imo. It does end up working out, but it is kind of weird.

**Comment by czMaxx** [comment]
easyaspi314: I'm still in the middle of playing with the code and I have to check what exactly is produced by the compilers, but I believe that the performance of the switch won't be downgraded if we let it go through the default case to break and execute the avalanche func after falling through 3, 2, 1 cases.

size_t issue, well maybe it's just my personal taste, but there's only a limited set of cases, where size_t actually can be beneficial and not slightly confusing. I agree that this usage is safe, because all instances of size_t variables are properly typecasted. What I meant is the very basic duality of the type. It allows you, to a ceratin extent, pass a 64bit number in the function, however you have to sacrifice the portability, if you do so. If you want to keep it portable, you have to use only the lower 32bits of it, which wipes the benefit of the wide argument (and you have to check all assignments/arithmetics to the fixed-size variables and cast them accordingly). This is the reason, why I consider using size_t as the last resort, when it's absolutely necessary and not the first choice. The other aspect of it is, that it's not a good practice to try to allocate a continuous buffer > 4GB and process it, therefore the debate is rather hypothetic. But I really like xxhash and if there's a possibility to polish the code, let's figure out what's the right way.

**Comment by czMaxx** [comment]
Ok, at least for MSVC, the fix of the unreachable code does not harm the switch and a jumptable is used (even when there's not enforced the full optimization), it's pretty straightforward.

.text:000000014000140F                 and     r8d, 1Fh
.text:0000000140001413                 mov     r9, rcx
.text:0000000140001416                 mov     rdi, 165667B19E3779F9h
.text:0000000140001420                 dec     r8d             ; switch 31 cases
.text:0000000140001423                 mov     r11, 0C2B2AE3D27D4EB4Fh
.text:000000014000142D                 cmp     r8d, 1Eh
.text:0000000140001431                 ja      def_140001467   ; jumptable 0000000140001467 default case
.text:0000000140001437                 lea     rcx, cs:140000000h
.text:000000014000143E                 mov     rsi, 27D4EB2F165667C5h
.text:0000000140001448                 mov     rbx, 7A1435883D4D519Dh
.text:0000000140001452                 mov     r8d, ds:(jpt_140001467 - 140000000h)[rcx+r8*4]
.text:000000014000145A                 mov     r10, 9E3779B185EBCA87h
.text:0000000140001464                 add     r8, rcx
.text:0000000140001467                 jmp     r8              ; switch jump
.text:000000014000146A ; ---------------------------------------------------------------------------
.text:000000014000146A
.text:000000014000146A $LN32:                                  ; CODE XREF: XXH64_finalize+67↑j
.text:000000014000146A                                         ; DATA XREF: XXH64_finalize:jpt_140001467↓o
.text:000000014000146A                 mov     rax, [rdx]      ; jumptable 0000000140001467 case 24
.text:000000014000146D                 add     rdx, 8
.text:0000000140001471                 imul    rax, r11
.text:0000000140001475                 rol     rax, 1Fh
.text:0000000140001479                 imul    rax, r10
.text:000000014000147D                 xor     r9, rax
.text:0000000140001480                 rol     r9, 1Bh
.text:0000000140001484                 imul    r9, r10
.text:0000000140001488                 sub     r9, rbx
.text:000000014000148B
.text:000000014000148B $LN31:                                  ; CODE XREF: XXH64_finalize+67↑j

**Comment by czMaxx** [comment]
By the way, this field:
https://github.com/Cyan4973/xxHash/blob/f3e08d7ea9286c2d68ae80607d4120550ee4c7ed/xxhash.h#L294
causes the comipler to add a dword padding at the end of the structure (because currently it does not have its natural alignment). I think that this is not what was wanted by the author, it seems to be the opposite. Maybe a mistake? What about shortening the struct padding to wrap at 8byte boundary? I mean reserved[ 2 ] -> reserved.

**Comment by Cyan4973** [comment]
I think the field should have been `XXH64_hash_t reserved` instead. The size, but different alignment.

**Comment by czMaxx** [comment]
Not really. In that case, the compiler will put a dword padding before the 64bit member, because the memsize member ends at a 4byte boundary.

struct XXH64_state_s {
off:0    uint64_t total_len;
off:8    uint64_t v1;
off:16   uint64_t v2;
off:24   uint64_t v3;
off:32   uint64_t v4;
off:40   uint64_t mem64[4];
off:72   uint32_t memsize;
off:76   uint32_t reserved;
};

**Comment by Cyan4973** [comment]
At `struct` level, it doesn't change anything.
Total size doesn't change, and last 12 bytes are unused anyway.

**Comment by czMaxx** [comment]
Anyway, I have collected the (proposed) improvements into a branch. With compiler optimizations in place the code looks like it was intended = the switch is translated to a fast jumptable (x86, x86_64) so if you want to review it (or allow others to review it), please grant me a contributor's rights.

**Comment by Cyan4973** [comment]
In general, it's enough to create PR from your fork into the target repository.
There's no need for any specific right.
This will automatically create the classic Github review environment.

**Comment by czMaxx** [comment]
And regarding the struct alignment and size. When I compile the test program, i receive these warnings:

test.c(19): warning C4820: 'XXH_orig_s': '4' bytes padding added after data member 'reserved'
test.c(42): warning C4820: 'XXH_wrong_s': '4' bytes padding added after data member 'memsize'

and the resulting code looks like:

.text$mn:00000000                 public _test
.text$mn:00000000 _test           proc near
.text$mn:00000000                 push    ebp
.text$mn:00000001                 mov     ebp, esp
.text$mn:00000003                 push    58h ; 'X'
.text$mn:00000005                 push    offset $SG9017  ; "HHX_orig: %d\n"
.text$mn:0000000A                 call    _printf
.text$mn:0000000F                 add     esp, 8
.text$mn:00000012                 push    50h ; 'P'
.text$mn:00000014                 push    offset $SG9018  ; "HHX_fixed: %d\n"
.text$mn:00000019                 call    _printf
.text$mn:0000001E                 add     esp, 8
.text$mn:00000021                 push    58h ; 'X'
.text$mn:00000023                 push    offset $SG9019  ; "HHX_wrong: %d\n"
.text$mn:00000028                 call    _printf
.text$mn:0000002D                 add     esp, 8
.text$mn:00000030                 xor     eax, eax
.text$mn:00000032                 pop     ebp
.text$mn:00000033                 retn
.text$mn:00000033 _test           endp

It's not necessary to bloat the structure to 58h with an implicit padding, when 50h is perfectly aligned to the 8byte boundary.

[test.txt](https://github.com/Cyan4973/xxHash/files/2984867/test.txt)

**Comment by Cyan4973** [comment]
The issue is, this last 64-bit field used to be useful in an earlier version.

Now the matter is how to handle the transition.
In a static linking context, it's not a problem : the `reserved` field could already be removed. The `struct` would be shorter. Everything would still work.

But with dynamic linking, things get worse.
A program may use the new `struct` definition from a recent `xxHash` header, but end up being actually linked to an old version of `xxhash` at runtime. The old version of `xxhash` will need the original larger size. If provided with a smaller memory area, it will crash the system.

The `reserved` field is only here to cover this scenario.

Reducing the `struct` size by reducing the `reserved` field will expose `xxHash` ecosystem to above-mentioned risk.

**Comment by czMaxx** [comment]
Ok, if it is a backward compatibility thing and not just the intention to pad the struct to 8byte boundary, then nevermind this change ;-)
