### ISSUE TITLE
need many update.....

### ISSUE THREAD

**Issue by shariat1** [Cyan4973/xxHash#195]
How to install and use? ...no helping!!

**Comment by easyaspi314** [comment]
The binaries have been taken down from the page because of an issue on windows. As Cyan is currently sick, development has been a little delayed.

You can compile them yourself though, either by running `make` in a Linux/macOS/WSL/Cygwin/msys2 terminal with GCC installed, or you can use cmake.

**Comment by shariat1** [comment]
[xxh32sum] Error 1 ...show this error

**Comment by easyaspi314** [comment]
That doesn't give me enough information.

I need stuff like:
 - OS and environment
 - Compiler version
 - Full build log
 - Steps you took

**Comment by shariat1** [comment]
root@localhost:/sdcard/tool/xxHash# ls
appveyor.yml        LICENSE    xxhash.c  xxhsum.1.md
cmake_unofficial    Makefile   xxhash.h  xxhsum.c
doc                 README.md  xxhash.o  xxhsum.o
libxxhash.a         tests      xxhsum
libxxhash.so.0.7.0  xxh3.h     xxhsum.1
root@localhost:/sdcard/tool/xxHash# make
ln -sf xxhsum xxh32sum
ln: failed to create symbolic link ‘xxh32sum’: Functi
on not implemented
Makefile:93: recipe for target 'xxh32sum' failed
make: *** [xxh32sum] Error 1
root@localhost:/sdcard/tool/xxHash#

See it ... I use  " make"  command .. But show error..

**Comment by felixhandte** [comment]
The error you are describing is not an xxh error. It sounds like you're on an extremely minimal operating system / filesystem that doesn't implement symbolic links. Whereas xxhash expects the standard complement of unix utilities.

What operating system are you using?

**Comment by easyaspi314** [comment]
I'm guessing Android or something from the path.

Considering that the path is /sdcard, the filesystem is likely FAT32, which doesn't support symlinks

**Comment by easyaspi314** [comment]
If you are on Android, try the Termux environment which gives you a filesystem that supports symlinks, or try /data/local.
On normal Linux, try something in /home.

**Comment by shariat1** [comment]
thanks now working...I clone it desktop then working...

root@localhost:~/Desktop/xxHash# make
cc -O3    -c -o xxhash.o xxhash.c
ar rcs libxxhash.a xxhash.o
cc -O3  -fPIC   xxhash.c -shared -Wl,-soname=libxxhas
h.so.0 -o libxxhash.so.0.7.0
ln -sf libxxhash.so.0.7.0 libxxhash.so.0
ln -sf libxxhash.so.0.7.0 libxxhash.so
cc -O3    -c -o xxhsum.o xxhsum.c
cc   xxhsum.o xxhash.o   -o xxhsum
ln -sf xxhsum xxh32sum
ln -sf xxhsum xxh64sum
root@localhost:~/Desktop/xxHash#

**Comment by easyaspi314** [comment]
If you solved your issue, please close it. Thanks.
