### ISSUE TITLE
Decode XXHash.XXH32

### ISSUE THREAD

**Issue by mcristales** [Cyan4973/xxHash#197]
Is there are some how can decode de unit? I have a problem because i need to obtain de original string of the XXHash.XXH32 after coding.

I Need help somebody?

**Comment by easyaspi314** [comment]
You can't really do that, not only is XXH32 explicitly designed to not be easily reversible, if your string is longer than 4 bytes, you lose information.

**Comment by mcristales** [comment]
Yes I know , well i am goint to obtain that registry in other way.
