### ISSUE TITLE
Add crystal binding to www.xxhash.com

### ISSUE THREAD

**Issue by methyl** [Cyan4973/xxHash#209]
I just published a basic crystal binding, which supports only string hashing but it's often enough. You can consider adding it to the website.

https://github.com/methyl/xxhash

**Comment by Cyan4973** [comment]
Never heard of Crystal before today...
Is that a kind of Ruby re-implementation ?

**Comment by methyl** [comment]
It's a system programming language with syntax very similar to Ruby and sharing some of the philosophy, but otherwise it's different - it's typed and compiles down to native binaries.

**Comment by Cyan4973** [comment]
Crystal binding added to the list
