### ISSUE TITLE
when can we expect xxh3 1.0?

### ISSUE THREAD

**Issue by hiqbn** [Cyan4973/xxHash#210]
looks fantastic and thanks for the work.

when can we expect xxh3 1.0?

**Comment by Cyan4973** [comment]
in roughly 2 release cycles

**Comment by hiqbn** [comment]
how many weeks away?

**Comment by Cyan4973** [comment]
Expect the next release in June.

We'll start from there, and see how much comment it generates. This will determine the delay for the following release.
