### ISSUE TITLE
Not much faster than md5sum

### ISSUE THREAD

**Issue by jcguu95** [Cyan4973/xxHash#221]
### Situation
I just tried the current master branch xxhsum for making an index file of my whole home folder at the same time:
`time (find ~ -type f -print0 | xargs -0 xxhsum > checksums_backup.xxh)`
`time (find ~ -type f -print0 | xargs -0 md5sum > checksums_backup.md5)`
According to the result of  `time` both taken around 8m10s.

While checking, `md5sum` performed better than `xxhsum`:
`time (xxhsum -c checksums_backup.xxh)` took 7m43.519s
`time (md5sum -c checksums_backup.md5)` took 7m31.624s

### Question
1. Is there anyway to get `xxhsum` faster? Did I miss something and do it wrong?
2. Why was the hash-checking faster than hash-making?

**Comment by ifduyue** [comment]
Probably the xxhsum round makes OS cache most of the files.

**Comment by Cyan4973** [comment]
I think @ifduyue is right : just fetching the file from support is likely the limiting factor. When files are already in the cache, it's likely going to run faster.

I made a similar test on a sample directory, and witnessed the time decrease from 4.1 sec (first run) to 2.9 sec (second run).

In your tests, since `md5sum` comes second, it benefits from caching done during first run with `xxhsum`.

**Comment by jcguu95** [comment]
Interesting! I will run the test again when I get my power adapter.

**Comment by jcguu95** [comment]
```
$time find ~ -type f -print0 > /dev/null
real    0m0.448s
user    0m0.124s
sys     0m0.320s
$ time (find ~ -type f -print0 | xargs -0 md5sum > checksums_back.md5)
**real    10m40.843s**
user    2m32.806s
sys     0m51.644s

$ time (find ~ -type f -print0 >> /dev/null)
real    0m0.444s
user    0m0.153s
sys     0m0.284s
$ time (find ~ -type f -print0 | xargs -0 xxhsum > checksums_backup.xxh)
**real    5m41.350s**
user    0m22.470s
sys     1m6.568s
```

Great! Seems that it's the cache problem.

How about the checking part?

**Comment by Cyan4973** [comment]
Could it be a little cousin of previous explanation ? 

aka, if you do a check after checksumming, maybe some of the files are still in cache ?
In which case, the check stage will seem faster, but it's effectively all about cache.
