### ISSUE TITLE
Issue with #define restrict

### ISSUE THREAD

**Issue by redorav** [Cyan4973/xxHash#226]
Hi,

Line 63 of xxh3.h defines out a C++ keyword and leaves it defined in the header. This is a problem when interacting with other code. Could it add an #undef restrict somewhere or, better yet, use an XXHASH_RESTRICT type of macro to use as a define instead?

It makes matters worse when restrict isn't actually a reserved keyword in C++, as you can actually use it as an identifier which is what's tripping up my code at the moment.

Thanks!

**Comment by Cyan4973** [comment]
Agreed

**Comment by Cyan4973** [comment]
This issue should not be fixed in `dev` branch
