### ISSUE TITLE
No compiler built-in swap64 and swap32 for clang

### ISSUE THREAD

**Issue by dtikhonov** [Cyan4973/xxHash#227]
[This check](https://github.com/Cyan4973/xxHash/blob/98684b15c862a29b2487a7a4c3e3969c674e5e34/xxhash.c#L689) for GNU version causes clang not to use compiler built-in function for swapping:

```
#if defined(_MSC_VER)     /* Visual Studio */
#  define XXH_swap64 _byteswap_uint64
#elif XXH_GCC_VERSION >= 403
#  define XXH_swap64 __builtin_bswap64
#else
static U64 XXH_swap64 (U64 x)
{
    return  ((x << 56) & 0xff00000000000000ULL) |
            ((x << 40) & 0x00ff000000000000ULL) |
            ((x << 24) & 0x0000ff0000000000ULL) |
            ((x << 8)  & 0x000000ff00000000ULL) |
            ((x >> 8)  & 0x00000000ff000000ULL) |
            ((x >> 24) & 0x0000000000ff0000ULL) |
            ((x >> 40) & 0x000000000000ff00ULL) |
            ((x >> 56) & 0x00000000000000ffULL);
}
#endif
```

This is because clang version is 402:

```
sh$ clang -dM -E - </dev/null |& grep GNUC
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
sh$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

In my tests, the compiler built-in is three times faster than the `XXH_swap64()` function.

As an alternative to checking for specific compiler versions, consider using platform-based checks:

```
#if defined(__FreeBSD__) || defined(__DragonFly__) || defined(__NetBSD__)
#include <sys/endian.h>
#define XXH_swap64 bswap64
#elif defined(__APPLE__)
#include <libkern/OSByteOrder.h>
#define XXH_swap64 OSSwapInt64
#elif defined(WIN32)
#include <stdlib.h>
#define XXH_swap64 _byteswap_uin64
#elif defined(__linux__)
#include <byteswap.h>
#define XXH_swap64 bswap_64
#else
static inline U64 XXH_swap64 (U64 x)
{
    /* ... */
}
#endif
```

**Comment by Cyan4973** [comment]
Could it work to just add `clang` as compatible with `__builtin_bswap64()` ?

**Comment by Cyan4973** [comment]
Also :
note that, in godbolt tests, [`clang` was able to simplify `XXH_swap64()` to `rax` instruction](https://godbolt.org/z/vFrCh8) all the way down to clang 3.0.

**Comment by dtikhonov** [comment]
I measured as follows:

```
#include <byteswap.h>
#include <stdint.h>
#include <stdlib.h>

#if XXH_SWAP
static inline uint64_t XXH_swap64(uint64_t x)
{
    return ((x << 56) & 0xff00000000000000ULL) |
           ((x << 40) & 0x00ff000000000000ULL) |
           ((x << 24) & 0x0000ff0000000000ULL) |
           ((x << 8)  & 0x000000ff00000000ULL) |
           ((x >> 8)  & 0x00000000ff000000ULL) |
           ((x >> 24) & 0x0000000000ff0000ULL) |
           ((x >> 40) & 0x000000000000ff00ULL) |
           ((x >> 56) & 0x00000000000000ffULL);
}
#define swap64 XXH_swap64
#else
#define swap64 bswap_64
#endif


int
main (int argc, char **argv)
{
    unsigned i, n;
    uint64_t v;

    if (argc > 2)
    {
        v = atoi(argv[1]);
        n = atoi(argv[2]);
    }
    else
    {
        v = 123;
        n = 1000000;
    }

    for (i = 0; i < n; ++i)
        v = swap64(v);

    return (int) v & 1;
}
```

```
sh$ clang -Wall -o ./swap-test -O1 swap-test.c -DXXH_SWAP=1
sh$ for i in {1..5}; do command time -f%U ./swap-test 1234 $[1 << 30 ] ; done
3.37
3.29
3.61
3.46
3.48
sh$ clang -Wall -o ./swap-test -O1 swap-test.c -DXXH_SWAP=0
sh$ for i in {1..5}; do command time -f%U ./swap-test 1234 $[1 << 30 ] ; done
1.29
1.26
1.26
0.96
1.04
```

It's interesting that clang can optimize that function to `bswap` instruction!  Looking at the assembly, I realize that the difference between the two versions above is that the call to `XXH_swap64()` is not inlined: https://godbolt.org/z/ixyJ6b

I don't know whether the same will hold in the xxhash.c.

**Comment by Cyan4973** [comment]
Interesting indeed !
`clang` can simplify both variants into `bswap` instruction, but makes a much worse job at inlining the "universal" variant.
Even adding a `force_inline` statement and pushing to `-O3` doesn't change the picture.
That's unexpected. I would hand-waive that it might be a consequence of optimization pass order.

Anyway, this is a good reason to move `clang` to use `bswap` instead.

**Comment by Cyan4973** [comment]
Also :
using `__builtin_bswap64()` results in exactly the same problem as the regular scalar variant, with poor inline result from `clang 3.8`, all the way up to latest `clang 8.0`. Interestingly, results are  actually better when using _older_ versions of `clang`, such as `clang 3.0`...

It's only when using `bswap_64()` that the code is consistently simplified.
That's another good reason to move to platform-based `bswap`, as opposed to compiler-based.

It's also quite disappointing of `clang`. I would not expect `clang` to make `__builtin_bswap64()` a second-rate intrinsic. It's silent, and without `goldbolt`, it would be much harder to observe such side-effect.

**Comment by Cyan4973** [comment]
So, I can change the way `XXH_swap64()` is generated on `clang` to help it use the more optimized variant, but a last question is : 
in which case does it matter ?

As far as I can tell, this function is mostly useful for big-endian systems. On such platform, read data is swapped in order to ensure XXH64() produces same result on both big and little endian systems. 
But on `x64` systems, which are little endian, `XXH_swap64()` seems basically unused. Only the transformation into canonical format uses it.

**Comment by dtikhonov** [comment]
> As far as I can tell, this function is mostly useful for big-endian systems.

Yes, I realized it (with some relief) after I posted the bug.  I have not tested on a big-endian system.

**Comment by Cyan4973** [comment]
The platform-based check for `bswap64()` proposed in the first post
cause issues when compiled on Windows platform,
as tested here : 
https://ci.appveyor.com/project/YannCollet/xxhash/builds/25888580

All tested compilers (Visual, mingw) are affected.

**Comment by dtikhonov** [comment]
That's surprising.  We have exactly the [same checks in lsquic-client](https://github.com/litespeedtech/lsquic-client/blob/master/src/liblsquic/lsquic_byteswap.h) and it [compiles fine on Windows](https://ci.appveyor.com/project/litespeedtech/lsquic-client/builds/24502992).  There has to be some Windows magic that would need to be tracked down.

**Comment by Cyan4973** [comment]
Seems to be just a simple misspell : the error message lists `_byteswap_uin64`, instead of `_byteswap_uint64`.
Trying again...

**Comment by dtikhonov** [comment]
Ah, that looks better.  You should probably do the same for `bswap32`.

**Comment by Cyan4973** [comment]
Well, we are not completely done yet.
When compiled in 32-bit mode, the Windows build complains that `_byteswap_uint64 ()` doesn't exist : https://ci.appveyor.com/project/YannCollet/xxhash/builds/25889813/job/i1glfy8x4s3blo6f .

Only `mingw32` has this issue, Visual x86 looks fine.

Note to self : I should find a way to extend coverage to `clang` on Windows too...

**Comment by Cyan4973** [comment]
Closing down.
This is not high-pri, we know this instruction is not in the performance critical path,
and changing the detection macro exposes the code to build breaks, especially on untested platforms.
