### ISSUE TITLE
xxHash doesn't work with Python3.5

### ISSUE THREAD

**Issue by TheShashank** [Cyan4973/xxHash#232]
I keep getting the error `ImportError: No module named 'xxhash.cpython'` when I try to import `xxHash` in my Python 3.5 installation. Are there workarounds to this, or is xxHash only for >3.6?

**Comment by Cyan4973** [comment]
This seems a python specific issue,
in which case, this question would be better targeted at the project of the python binder you are using.

**Comment by ilyapopov** [comment]
The issue should be directed to the Python bindings for xxHash: https://github.com/ifduyue/python-xxhash
