### ISSUE TITLE
Fails to build on Windows 7 x64

### ISSUE THREAD

**Issue by jafrey** [Cyan4973/xxHash#24]
Trying to build on Windows 7 x64 with Python 3 I get the following error:

    python-xxhash.c
    python-xxhash.c(363) : error C2099: initializer is not a constant
    python-xxhash.c(687) : error C2099: initializer is not a constant
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\
amd64\\cl.exe' failed with exit status 2

**Comment by t-mat** [comment]
Hi,

Did you build a code from this project ?  This repo is mirror of [original xxhash](https://code.google.com/p/xxhash/) which does not have any python related code.
It seems that you've complied @ifduyue's [python-xxhash](https://github.com/ifduyue/python-xxhash).  If so, you should post your issue to python-xxhash.

**Comment by jafrey** [comment]
Sorry about that. I swore I found the right git repo.
