### ISSUE TITLE
Add BLAKE2b hash in the benchmarks

### ISSUE THREAD

**Issue by Agagamand** [Cyan4973/xxHash#243]
BLAKE2 is a cryptographic hash function faster than MD5, SHA-1, SHA-2, and SHA-3, yet is at least as secure as the latest standard SHA-3. BLAKE2 has been adopted by many projects due to its high speed, security, and simplicity. 

https://blake2.net/

**Comment by Cyan4973** [comment]
Hi @Agagamand ,

Sure, I can and will certainly add Blake2b to the benchmark list.

Just be aware that, Blake2 being branded as offering cryptographic qualities, it's not in the same league, for both cryptography and speed. Blake2's speed is great in comparison with _other cryptographic hashes_ . But when compared with non-cryptographic hashes, it will seem quite slow.

**Comment by Cyan4973** [comment]
The results are in for Blake2.

For "large" inputs, the speed is almost on par with FNV, which is already plotted (and is not great).
For "small" inputs though, the results are abysmal, capping at ~6MH/s, which is more than one order of magnitude slower than all non-cryptographic ones.

I'll see later if I can usefully plot Blake2 on the same graph as other algorithms.

**Comment by Cyan4973** [comment]
Blake2 has been added to : 
https://github.com/Cyan4973/xxHash/wiki/Performance-comparison

For the time being, it's present only in table,
there is still a visualisation problem when trying to plot too many candidates in a single graph.
Raw Data could be made available, though it's unclear it this would be any useful.
