### ISSUE TITLE
Add CMakeLists.txt

### ISSUE THREAD

**Issue by hkimura** [Cyan4973/xxHash#25]
It's much easier for cmake-based projects to integrate xxhash if it has CMakeLists.txt.
Something like this?

    cmake_minimum_required(VERSION 2.6)
    cmake_policy(VERSION 2.6)

    project(xxhash)

    # I don't find xxHash's release version info. Let's say r39 means 0.39.
    set(XXHASH_LIB_VERSION "0.39.0")
    set(XXHASH_LIB_SOVERSION "0")

    set(BUILD_STATIC_LIBS ON CACHE BOOL "Set to ON to also build static libraries")
    if(BUILD_STATIC_LIBS)
      add_library(xxhashstatic xxhash.c)
      set_target_properties(xxhashstatic PROPERTIES OUTPUT_NAME xxhash)
    endif(BUILD_STATIC_LIBS)

    add_library(xxhash SHARED xxhash.c)
    set_target_properties(xxhash PROPERTIES
            COMPILE_DEFINITIONS "XXHASH_EXPORT"
    VERSION "${XXHASH_LIB_VERSION}"
    SOVERSION "${XXHASH_LIB_SOVERSION}")

The above example separates out xxhsum.c, which is under GPL thus some project might not want to include.

// edit: markdown format

**Comment by Cyan4973** [comment]
Good point Hideaki.

I typically don't maintain `CMakeLists.txt` for my projects
I already provide a `Makefile` and want to provide a single reference,

but I'm nonetheless opened to contributions and can include such file into release.
Using [lz4](https://github.com/Cyan4973/lz4) as an example, it would land into its own directory, named `cmake_unofficial`.

**Comment by hkimura** [comment]
That works fine. Thanks!

**Comment by Cyan4973** [comment]
Hi @hkimura , do you want to transform this issue into a PR ?

**Comment by hkimura** [comment]
I'd like to help, but it takes me a bit of time to make a real pull-request myself for corporate reasons.
If you could take the following file from my project and adjust whatever missing, that is much easier for me:
  https://github.com/hkimura/foedus_code/blob/master/foedus-core/third_party/xxHash-r39/CMakeLists.txt
  https://github.com/hkimura/foedus_code/blob/master/foedus-core/third_party/xxHash-r39/README_HP.markdown

In order to make a contribution to an OSS project I haven't contributed before, unfortunately I have to go through a lengthy legal process which takes at least weeks.

**Comment by hkimura** [comment]
Oh, BTW, in case you wonder about license issues (BSD in xxhash, GPL in my project):
I (the author) attest that the CMakeLists.txt I pointed to is solely trivial and has no intellectual whatsoever. "Reproduce"-ing the file shouldn't be counted as a derivative of a GPL software.

**Comment by Cyan4973** [comment]
Thanks Hideaki
I totally understand the corporate issue.

It will take some time to look into your linked proposal, because I'm not familiar with cmake.
I guess I'll have to find a way (and time) to properly test it.
But hopefully, there is no hurry ...

**Comment by Cyan4973** [comment]
unofficial cmakelist added to latest update.
Will be released as part of r41.
