### ISSUE TITLE
BYTE is predefined by some compiler

### ISSUE THREAD

**Issue by svorkoetter** [Cyan4973/xxHash#258]
One of the targets with which we wish to use xxHash requires compilation with a very old version of MSVC++ (Visual Studio 6), which defines a type named BYTE. This conflicts with xxHash. I've gotten around it for now by renaming xxHash's BYTE to XXBYTE. Perhaps this can be addressed officially in the sources?

Also, _byteswap_ulong is not supported by that version of MSVC++ either.

**Comment by Cyan4973** [comment]
I guess this is an issue when using `XXH_INLINE_ALL` ?

**Comment by svorkoetter** [comment]
Yes. I've only tried XXH_INLINE_ALL.

**Comment by easyaspi314** [comment]
What about `U8`?

**Comment by Cyan4973** [comment]
The problem now is the genericity of some names.
Not just `BYTE` or `U8` by the way, but also `U32` and `U64`.

While these names were in use within `xxhash.c` which was compiled separately, there was no issue.
But now that the tendency is to rather inline it, too generic names increase risks of name collisions.

So we need names which have _less_ chances to be also present in host's code.
Maybe `xxu8`, `xxu16`, etc.

note : also use this opportunity to properly link with types already declared in `xxhash.h`: `XXH32_hash_t` and `XXH64_hash_t`.
