### ISSUE TITLE
[Suggestion]  Add option to OSX binary to disable "Loading..." text

### ISSUE THREAD

**Issue by witedragen** [Cyan4973/xxHash#272]
I need to store a hash in a bash variable outputted from xxhsum.

I seem to get a lot of trailing spaces and sometimes will see the loading text in the variable/printout.

Can you add a option to output nothing while its calculating and ONLY output the final result?

**Comment by Cyan4973** [comment]
Yep, that's a good point.
Command `-q` should work properly with version in `dev` branch now.

It was already working partially (removing the "Loading x" message, but leaving a few trailing spaces). It's also better documented now.

**Comment by Cyan4973** [comment]
The feature is now available in latest release `v0.7.2`

**Comment by witedragen** [comment]
Magnificent! Thanks for the update cyan !
