### ISSUE TITLE
[Suggestion] Print hash only

### ISSUE THREAD

**Issue by witedragen** [Cyan4973/xxHash#274]
I'm storing hashes in bash variables and currently I use:

`$ foo="$(xxhsum -q /path/to/file | sed -e 's/^\(.\{16\}\).*/\1/')"`

Could you please add an option to print only the hash? I know what I'm using right now works, but it would be nice to use less processes (:

i also understand most users may not want this since checking it again with `-c` would not work, but for my application this is not a problem

**Comment by Cyan4973** [comment]
For the functionality to print (and check) hash values for a list of files,
I'm trying to remain close to `md5sum` interface.

Is there an option / argument in `md5sum` which achieves what you are looking for ?

**Comment by witedragen** [comment]
Checked the man page, didn't see anything

**Comment by easyaspi314** [comment]
@witedragen Can't you just use `xxhsum -q /path/to/file | cut -f 1 -d " "`? `sed` is kind of overkill imo.

**Comment by Cyan4973** [comment]
I believe the solution proposed by @easyaspi314 works great for this purpose.
It works with multiple files too, 
and `cut` is a much simpler operation which should cost negligible cpu compared to `sed`.
