### ISSUE TITLE
Minor: underline ==== comments clash with git's merge-conflict identifier

### ISSUE THREAD

**Issue by krcroft** [Cyan4973/xxHash#277]
When merging code, git by-default will flag merge conflicts using BEFORE and AFTER code blocks separated with a `=======` string:
``` diff
Changes made on the branch that is being merged into. In most cases,
this is the branch that I have currently checked out (i.e. HEAD).
=======
Changes made on the branch that is being merged in. This is often a 
feature/topic branch.
```
If the code itself contains `=======` strings, then this becomes error-prone to edit and search for.  

The recommendation here is (so long as this repo is managed in git) to use ASCII strings that don't overlap with git's identifier lines (perhaps `-------`'s)?

**Comment by easyaspi314** [comment]
Seems pretty reasonable.

Usually I do this:
```c
/*************************************
 *              SECTION              *
 *************************************/

/* * * * * * * * * * * * * * * * * * *
 *              SECTION              *
 * * * * * * * * * * * * * * * * * * */

/*********** SECTION ***********/

/*
 * SECTION:
 *
 * Lorem ipsum dolor sit amet
 */
```

Also, @Cyan4973 this would be a great time for us to go through the comments and pick the "right" style for once:

```c
/*
 * This is a multiline comment.
 *
 * Lorem ipsum dolor sit amet
 */
```

**Comment by Cyan4973** [comment]
I agree
