### ISSUE TITLE
New perl interface implementation

### ISSUE THREAD

**Issue by DoubleBB** [Cyan4973/xxHash#279]
I have written a new Perl interface modul to xxHash 64 bit algorithm based on your C code.
It is available at https://github.com/DoubleBB/digest-xxhash64
Please add this reference to the different language implementation list as Perl programming language.

thanx,

Bela Bodecs

**Comment by Cyan4973** [comment]
Hi Bela

Sure ! Could you spell one notable difference between your implementation and the existing xxhash Perl binding available at https://metacpan.org/pod/Digest::xxHash ?

**Comment by DoubleBB** [comment]
Digest::xxHash implementation is very good but has only functional interface that makes possible to calculate hash values of a single input value. (Although it can calculate 32 bit and 64 bit hash values.) So you need to store the whole data in memory to use this.
My implementation (Digest::xxHash64) has object oriented interface besides the functional interface.  It makes possible to calculate xxHash 64 bit values in single or multiple pass. It is good handling of streaming like sources or when you want to calculate hashes of long inputs like big files or so. This was my personal motivation to create it because I had to calculate hashes of large files in Perl.
My implementation calculates only 64 bit hash values as its name suggest.

**Comment by Cyan4973** [comment]
Great ! Thanks @DoubleBB !
