### ISSUE TITLE
Provide xxhsum Windows binaries for 0.7.2

### ISSUE THREAD

**Issue by yghorbal** [Cyan4973/xxHash#281]
Hello,

 xxhsum Windows binaries are provided with 0.7.1 (with an avx and an sse builds) which is very helpful. I'm using it in a script I'm writing.
 In the 0.7.1 there is no way to disable the "Loading..." message on STDERR which breaks some automations I'm trying to build based on the command output.
 The 0.7.2 addresses this with the -q, --quiet switch.
 It would be very handy that you include the Windows binary builds for xxhsum in the 0.7.2 as well.
 Thank you for this very useful tool.

Youssef

**Comment by Cyan4973** [comment]
`xxhsum` `v0.7.2` binaries for `win64` have been [published in the release tab](https://github.com/Cyan4973/xxHash/releases/tag/v0.7.2).
