### ISSUE TITLE
How to reset xxh32 from prev saved hash value?

### ISSUE THREAD

**Issue by Jae-hyun** [Cyan4973/xxHash#282]
Hi, 

I'd like to incremental update xxh32 hash from last saved hash value(u32).

How to convert u32 value to XXH32_state_t?
(XXH32_reset(XXH32_state_t* statePtr, XXH32_hash_t seed)

Or other methods to init it?

**Comment by Cyan4973** [comment]
There is no way.
The internal state of `xxh32` is 128-bit, not 32-bit, and that's just for the accumulator.

To incrementally update `xxh32`, one needs to save the entire state `XXH32_state_t`, and resume from its content.
