### ISSUE TITLE
Switched --quiet and --strict man descriptions?

### ISSUE THREAD

**Issue by LEARAX** [Cyan4973/xxHash#286]
I'm pretty sure the described behavior of the `--quiet` and `--strict` switches are swapped in the man page. Also, why is `--quiet` in the man page twice? The second description should probably clarify this a bit, and probably have a dash for consistency.

https://github.com/Cyan4973/xxHash/blob/1c3bfee5f0bf05c69ecbadec810c7f2ab12ab720/xxhsum.1#L44-L46

https://github.com/Cyan4973/xxHash/blob/1c3bfee5f0bf05c69ecbadec810c7f2ab12ab720/xxhsum.1#L63-L65

https://github.com/Cyan4973/xxHash/blob/1c3bfee5f0bf05c69ecbadec810c7f2ab12ab720/xxhsum.1#L67-L69

**Comment by Cyan4973** [comment]
You are right @LEARAX . These entries are bogus. 
To be fixed.
