### ISSUE TITLE
Underflow of statePtr and &state in two memcpy calls

### ISSUE THREAD

**Issue by krcroft** [Cyan4973/xxHash#292]
(screenshots from the PVS Studio static analyzer)

![image](https://user-images.githubusercontent.com/1557255/72755155-ab0e9880-3b7e-11ea-9be6-66859a6f64ea.png)

and

![image](https://user-images.githubusercontent.com/1557255/72755176-bcf03b80-3b7e-11ea-80cf-da5869102c6a.png)

https://www.viva64.com/en/w/v512/

**Comment by Cyan4973** [comment]
These structures are intentionally not completely `memset()`, and the reason is explained in the comment line just above : 

> do not write into `reserved`, planned to be removed in a future version

**Comment by krcroft** [comment]
Thanks for the explanation @Cyan4973 ; will exclude these as false-positives!
