### ISSUE TITLE
Are xxhash algorithms stable?

### ISSUE THREAD

**Issue by yasushi-saito** [Cyan4973/xxHash#295]
Does xxhash guarantee that future changes to the code doesn't change the output of the functions? If so, can we have a declaration in the doc? Btw, highwayhash has this guaratee.

I'm planning to use xxhash to compute the checksum of bulk data to be stored at rest. In that application, I need an assurance that I can update to a newer version of xxhash without reencoding the data.

**Comment by Cyan4973** [comment]
`XXH32` and `XXH64` both have this guarantee.

Newer `XXH3` and `XXH128` do not have this guarantee yet.

**Comment by XSAM** [comment]
Hi @Cyan4973, it is being a while after this issue is created. And, the [spec](https://github.com/Cyan4973/xxHash/blob/v0.8.2/doc/xxhash_spec.md#xxh3-algorithm-overview) is available. Does that mean `XXH3` has the guarantee now?

**Comment by Cyan4973** [comment]
Yes it is
