### ISSUE TITLE
XXH64: For short inputs, the documentation doesn't match implementation

### ISSUE THREAD

**Issue by ojakubcik** [Cyan4973/xxHash#296]
As specified in documentation, short inputs of length >= 8 are calculated as this:
```
while (remainingLength >= 8) {
    lane = read_64bit_little_endian(input_ptr);
    acc = acc xor round(0, lane);
    acc = (acc <<< 27) * PRIME64_1;
    acc = acc + PRIME64_4;
    input_ptr += 8; remainingLength -= 8;
}
```
where
```
round(accN,laneN):
accN = accN + (laneN * PRIME64_2);
accN = accN <<< 31;
return accN * PRIME64_1;
```

However, this isn't what the reference implementation is doing:
```
#define PROCESS8_64 {        \
    xxh_u64 const k1 = XXH64_round(0, XXH_get64bits(ptr)); \
    ptr+=8;                    \
    h64 ^= k1;               \
    h64  = XXH_rotl64(h64,27) * PRIME64_1 + PRIME64_4; \
}
```

It sets the `acc` to 0, which is IMO wrong, it should pass `h64`.

**Comment by Cyan4973** [comment]
I believe the code corresponds to the documentation, and vice versa.

doc : `acc = acc xor round(0, lane);`
code : `h64 ^= XXH64_round(0, XXH_get64bits(ptr));`

In both cases, the first argument of `round()` is `0`.

**Comment by easyaspi314** [comment]
@Cyan4973 do you think we should change the code to more match the docs?

There is no reason that the variable names have to be different, especially since the documentation's variable names are much more meaningful than the code's names.

Also, this doesn't seem to change the output on either GCC or Clang:
```c
#define PROCESS8_64 {                        \
    xxh_u64 lane = XXH_get64bits(ptr);       \
    h64 ^= XXH64_round(0, lane);             \
    ptr += 8;                                \
    h64 = XXH_rotl64(h64, 27) * PRIME64_1;   \
    h64 += PRIME64_4;                        \
}
```

as well as this (which my previous attempt changed GCC register allocation):

```c
XXH_FORCE_INLINE xxh_u64 XXH_xorFold(xxh_u64 val, int amt)
{
    return val ^ (val >> amt);
}

XXH_FORCE_INLINE XXH64_hash_t
XXH3_len_4to8_64b(const xxh_u8* input, size_t len, const xxh_u8* secret, XXH64_hash_t seed)
{
    XXH_ASSERT(input != NULL);
    XXH_ASSERT(secret != NULL);
    XXH_ASSERT(4 <= len && len <= 8);
    {   xxh_u32 input_lo = XXH_readLE32(input);
        xxh_u32 input_hi = XXH_readLE32(input + len - 4);
        xxh_u64 acc = input_lo | ((xxh_u64)input_hi << 32);
        acc ^= XXH_readLE64(secret) + seed;
        acc  = XXH_xorFold(acc, 51);
        acc *= PRIME32_1;
        acc += len;
        acc  = XXH_xorFold(acc, 47);
        acc *= PRIME64_2;
        return XXH3_avalanche(acc);
    }
}
```

Apparently, GCC treats this
```c
acc = XXH_xorFold(acc, 51);
```
different than these:
```c
acc = acc ^ (acc >> 51);
acc ^= acc >> 51;
```

while Clang treats them all the same.

**Comment by Cyan4973** [comment]
> do you think we should change the code to more match the docs?

Sure, anything that helps readability while preserving performance is welcomed.

> Apparently, GCC treats <xorfold> different than <separate operations>

Worse or better ?

**Comment by easyaspi314** [comment]
It looks like the only differences are register swaps, and swaps do occur with the provided code on aarch64, but I mean, it is aarch64, it has a billion registers.

I will check i686 GCC later, as i686 is where register allocation is the most important.

Also, clang will always generate the same thing on all platforms; it emits the exact same IR.

**Comment by ojakubcik** [comment]
> 
> 
> I believe the code corresponds to the documentation, and vice versa.
> 
> doc : `acc = acc xor round(0, lane);`
> code : `h64 ^= XXH64_round(0, XXH_get64bits(ptr));`
> 
> In both cases, the first argument of `round()` is `0`.

I initially though so too, but this is how `round` is defined:
```
round(accN,laneN):
accN = accN + (laneN * PRIME64_2);
accN = accN <<< 31;
return accN * PRIME64_1;
```

If I'm reading that correctly, it is referencing N-th accumulator - this is used e.g. in the following snippet:
```
        do {
            v1 = XXH64_round(v1, XXH_get64bits(input)); input+=8;
            v2 = XXH64_round(v2, XXH_get64bits(input)); input+=8;
            v3 = XXH64_round(v3, XXH_get64bits(input)); input+=8;
            v4 = XXH64_round(v4, XXH_get64bits(input)); input+=8;
        } while (input<=limit);
```

However, the merge function is using `0` too, so not sure which of these is correct:
```
static xxh_u64 XXH64_mergeRound(xxh_u64 acc, xxh_u64 val)
{
    val  = XXH64_round(0, val);
    acc ^= val;
    acc  = acc * PRIME64_1 + PRIME64_4;
    return acc;
}
```

**Comment by easyaspi314** [comment]
`round` is a separate function.

**Comment by ojakubcik** [comment]
I see, so for the main loop the actual value of `acc` is passed, but for merge and short inputs, `0` is passed. Thanks for clarification.
