### ISSUE TITLE
Invalid Copyright Year

### ISSUE THREAD

**Issue by JoshuaFern** [Cyan4973/xxHash#329]
Copyright is a complicated issue, but as far as I know you're not allowed to use "present".
`Copyright (C) 2012-present, Yann Collet`
Please consider updating your copyright to the current year :)

https://github.com/dreamer/dosbox-staging/pull/197#issuecomment-595692821
https://opensource.stackexchange.com/questions/4885/copyright-unitl-the-present-year-in-bsd-license

**Comment by easyaspi314** [comment]
Yeah, I was kind of thinking about that as well. It seemed kinda weird.

Besides, by the time a US copyright wears off, you will be too dead to care.

**Comment by easyaspi314** [comment]
Fix is up.
