### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by mvanleeu** [Cyan4973/xxHash#352]
Same as for zstd https://github.com/facebook/zstd/issues/2070, soem issue with Cloudflare. Probably same solution too.

**Comment by dsoprea** [comment]
Still down, even though the _zstd_ site came back.

**Comment by beachwalker** [comment]
Alternative: https://cyan4973.github.io/xxHash/

**Comment by Cyan4973** [comment]
It's disappointing, but the Cloudflare solution has been failing, after working for more than a year.
With no notification, no solution and no help in sight, I've reverted to previous situation, with only the `http://` website being redirected.
We'll if another solution becomes accessible in the future.
Closing for now.
