### ISSUE TITLE
Everything seems good. When do you expect version 1.0 to be out?

### ISSUE THREAD

**Issue by gitmko0** [Cyan4973/xxHash#353]
Everything seems good. When do you expect version 1.0 to be out?

**Comment by easyaspi314** [comment]
Soon™

It will come when it is ready.

**Comment by aras-p** [comment]
Are we there yet?
Are we there yet?
How about now?
Now?

:)

(on a more serious note: good work, looking forward to final XXH3 release)

**Comment by Cyan4973** [comment]
[xxHash v0.8.0](https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0) has been released this morning, it stabilizes output values of `XXH3`.

**Comment by gitmko0** [comment]
thanks! you are the best! let's inform all the programming languages to implement this.
