### ISSUE TITLE
Missing a big change in v0.7.3

### ISSUE THREAD

**Issue by ktrongnhan** [Cyan4973/xxHash#355]
From a consumer's standpoint, I think #303 is the biggest change in v0.7.3 but it was not mentioned in either the Release Notes or the CHANGELOG.
It caused a surprise to me as I had not expected changes to values XXH32 and XXH64 return.
Should there be a note for it somewhere?
Here is the PR's description just for a quick reference:
> Following suggestion from @pdillinger, at [#175 (comment)](https://github.com/Cyan4973/xxHash/issues/175#issuecomment-548108921) .
> 
> The probability of receiving an empty string is larger than random (> 1 / 2^64),
> making its generated hash value "more common".
> 
> For some algorithm, it's an issue if this "more common" value is 0.
> 
> Maps it instead to an avalanche of an arbitrary start value (prime64).
> The start value is blended with the `seed` and the `secret`,
> so that the result is dependent on those ones too.
> 
> It makes the return value of "empty string" no longer comparable with `0.7.2`.
> For this reason, the internal library version number is updated to `0.7.3`.

**Comment by easyaspi314** [comment]
XXH32 and XXH64 have not changed, and will never change.

All mentioned changes apply to XXH3.

**Comment by ktrongnhan** [comment]
Oops! My bad! Really sorry, closing now
