### ISSUE TITLE
make install  under cygwin

### ISSUE THREAD

**Issue by mvanleeu** [Cyan4973/xxHash#356]
Natively "make install" doesn't work in cygwin as the target isn't recognised. 
A simple fix is to add cygwin as a target in the filtering list in the Makefile, at time of writing around [line 321](https://github.com/Cyan4973/xxHash/blob/dev/Makefile#L321)

\# =========================================================
\# make install is validated only for the following targets
\# =========================================================
ifneq (,$(filter $(shell uname),**_CYGWIN_NT-6.1_** Linux Darwin GNU/kFreeBSD GNU OpenBSD FreeBSD NetBSD DragonFly SunOS))

with that change, make isntall is visible again under cygwin, and the files (binaries, manual, etc) are installed correctly under $(PREFIX),, /usr/local by default

Yann or other with commit rights, maybe an easy change for you?

**Comment by mvanleeu** [comment]
Note that uname returns different things depending if it is 64 bits (CYGWIN_NT-6.1) or 32 bits (CYGWIN_NT-6.1**-WOW**). I haven't looked at make and Makefiles in ages, but probably something clever can be doen via filter ()

**Comment by Cyan4973** [comment]
Indeed, the `CYGWIN_NT*` string changes depending on exact how.
I still have to find a way to allow all variants, not just a specific one.
