### ISSUE TITLE
Missing section in CMakeFile.txt for windows .dll target

### ISSUE THREAD

**Issue by vrqq** [Cyan4973/xxHash#362]
https://github.com/Cyan4973/xxHash/blob/d45288407e78c6d5bc2ebe53fe9ea1fd305ab939/cmake_unofficial/CMakeLists.txt#L119-L122
The ```RUNTIME DESTINATION``` would copy xxhash.dll when build flag -DBUILD_SHARED_LIBS=ON on Windows platform.
It doesn't matter on Linux platform because the .so files are treated by ```LIBRARY```
```
  install(TARGETS xxhash
    EXPORT xxHashTargets
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}")
```

**Comment by Cyan4973** [comment]
PR welcomed !
