### ISSUE TITLE
[pedantic] Secret size truncation in state

### ISSUE THREAD

**Issue by easyaspi314** [Cyan4973/xxHash#368]
A mostly pedantic issue that only affects people who are stupid enough to cause it, but an issue nonetheless.

On a secretSize > 4 GiB, the state and single shot functions will theoretically desync. This is due to the size being truncated from `size_t` to `XXH32_hash_t` when being stored in the state. 

We should use `size_t` instead (`XXH64_hash_t` will unnecessarily slow down 32-bit targets since unlike `totalLen`, we can't have a secret larger than `SIZE_MAX`, and it is already unsafe for long term storage due to the secret pointer).

**Comment by Cyan4973** [comment]
Thanks for pointing that out.

Indeed, a `secretSize` larger than 4 GB is something I'm _not_ eager to support.

That being said, I'm also concerned by API discrepancy. Both single-ingestion and streaming hash functions shall return the same value, in all scenarios, even crazy ones.

One option could be to refuse `secretSize` larger than 4 GB, but then, we can't have the single-ingestion API which accepts and work fine with it, while the streaming API doesn't.

On the other hand, changing `secretLimit` to `size_t` type seems to require just a few minor changes, so it's probably okay.

**Comment by easyaspi314** [comment]
Yeah, I agree. Stupid, but might as well avoid the inconsistency.

The structure size (should) still be 576 bytes, and there shouldn't be any measurable difference between using `size_t` and `uint32_t`.
