### ISSUE TITLE
Broken "other languages" link in the readme

### ISSUE THREAD

**Issue by lunakid** [Cyan4973/xxHash#370]
Maybe it's just a transient, but I'm having have trouble opening anything at https://xxhash.com.

Lovely work, BTW, cheers!
Sz.

**Comment by Cyan4973** [comment]
It's indeed a problem.
I don't have a solution. Something changed in Cloudflare, and since then, there are a lot of issues with `https://` connections. `http://` connections still work though.

**Comment by Cyan4973** [comment]
After months of failure, Cloudflare has been disabled. Only the `http://` link is now redirected.
