### ISSUE TITLE
Question. Using seed as additional data. In other words, does using different seeds affect the quality.

### ISSUE THREAD

**Issue by Sopel97** [Cyan4973/xxHash#371]
I need to hash 64 bytes of contiguous memory and 3 bytes that are spread somewhere else. I was thinking about providing the 64 bytes as data, and the 3 bytes as a seed. Would this harm the quality of the hash? Is there a different way of doing this while not sacrificing performance?

**Comment by easyaspi314** [comment]
Using different seeds does not make a huge difference on quality aside from `seed=0`.

However, using the input as a seed is really unusual, as usually the seed is constant.

**Comment by Cyan4973** [comment]
I believe that's fine.
Faced with a similar scenario, I would consider the same construction.
