### ISSUE TITLE
https://www.xxhash.com/ is down?

### ISSUE THREAD

**Issue by millerjp** [Cyan4973/xxHash#380]
Not an issue, but just thought you would like to know

![Screenshot 2020-05-29 at 13 49 04](https://user-images.githubusercontent.com/163300/83256716-3a722b00-a1b3-11ea-9111-d68fa11cbf37.png)

**Comment by Cyan4973** [comment]
Yeah, I'm not sure what's going on, but this whole attempt to bring `https` to xxhash.com sure backfired when something changed between Cloudflare and Github.
I might as well revert all this and come back to initial setting, even without "direct" `https` support.

**Comment by Cyan4973** [comment]
So, for the time being, I disabled Cloudflare on `xxhash.net` and `xxhash.org`,
so both should as initially intended,
meaning that requesting http://xxhash.net should redirect to https://cyan4973.github.io/xxHash/ .

This provides a backup.
I haven't yet decided for `xxhash.com`, but if I can't find a way to fix it, it will probably follow.

**Comment by WayneD** [comment]
Note that issue #352 is an older report of this problem.

**Comment by Cyan4973** [comment]
Due to this issue being lingering for month with no end in sight,
I've removed all my website from Cloudflare.

Meaning that, as before, `http://` will work properly, and redirect to `https://github.com/` web page, but trying to reach directly `https://xxhash.com` will not work.

**Comment by Cyan4973** [comment]
I'm going to close it for now.
If there is another solution which is reasonably accessible, I'll be happy to try it.
In the meantime, only the `http://` address get redirected.
