### ISSUE TITLE
bsd output style

### ISSUE THREAD

**Issue by grylem** [Cyan4973/xxHash#382]
Hello
please add options for bsd otput style for calc and checking like
XXHASH32 (filename) sum
XXHASH64 (filename) sum
XXHASH128 (filename) sum
Thanks.

**Comment by easyaspi314** [comment]
This isn't a bad idea.
The only potential issue is that *older* versions of xxhsum wouldn't be able to read it.
For the reference, it would go like this
```
XXHASH128 (checksum.xxh128) = 9eb7a54d24dbf6a2eb9f7ce7a1853cd0
```

Note that coreutils provides the `--tag` option which switches to the BSD format.

**Comment by Cyan4973** [comment]
Preserving consistency with `coreutils` is important.
Adding support for `--tag` format is a good idea.

**Comment by grylem** [comment]
sorry i made a mistake in the title should be "bsd output style".

**Comment by Cyan4973** [comment]
Adding a new output mode will be easy.

What will be more difficult is to add a matching consumption mode.
`xxhsum -c` must read files produced by `xxhsum`, to control listed checksums.
For consistency, it will also have to read files produced by `xxhsum --tag`.

This will cost code, complexity and time.

**Comment by easyaspi314** [comment]
Well if we are going to match coreutils, we are also missing the backslash modifier.

If the first non-space character is a backslash, it will escape `\n` and `\\`.

So
```shell
$ export FILENAME=$'foo\n\\bar.txt'
$ echo "$FILENAME" > "$FILENAME"
$ md5sum "$FILENAME"
\dc7fd66c4fc94c46b7c91d95c2c30914  foo\n\\bar.txt
$ md5sum --tag "$FILENAME"
\MD5 (foo\n\\bar.txt) = dc7fd66c4fc94c46b7c91d95c2c30914
$ xxhsum "$FILENAME"
cbf4f722b723ac65  foo
\bar.txt
```

If we really want to do that, it will be a pain unless we just copy from coreutils.

**Comment by Cyan4973** [comment]
That's probably a different topic, unrelated to the `--tag` option.

**Comment by grylem** [comment]
[RHash](https://github.com/rhash/RHash) can work with both types of output format - BSD and md5sum. For calculating and checking.

**Comment by baryluk** [comment]
I personally think that BSD format is silly (plus hard handling of special characters), compared to GNU format, but I wouldn't object having `--tag`  for compatibility and drop-in replacement of existing utils. But that also probably requires adding support in `xxhsum -c` to work robustly (including mixed hashes, and tag vs non-tag formats).

**Comment by easyaspi314** [comment]
Yeah the BSD format is nice to look at, but painful to parse.

In a perfect world, you could do this:
```c
int hash_type;
char *fname_buf = malloc(strlen(line)+1);
char hash_buf[17];
if (sscanf(line, "XXH%d (%[^)]) = %16s\n", &hash_type, fname_buf, hash_buf) == 3) {
    ...
}
```
But you would actually need to approach it from both sides, as the filename can contain parentheses and equal signs.

**Comment by Cyan4973** [comment]
Well, there's no guarantee that `xxhsum` will support any other display format independently decided by another utility.

In this case though, the difference seems small, so it should be easy to become compatible with it.

**Comment by Cyan4973** [comment]
I can probably add a `--tag` BSD-style output to `xxhsum`,
but it's much less clear if I can _read_ it (with check command `-c`)
while keeping this development under reasonable time-constrained budget.

I'm wondering if having just the first part (output only) makes sense.

**Comment by Cyan4973** [comment]
`--tag` will be a hidden option for next release.
I have no time to add a reader (`-c`) for next release, so the option will remain undocumented, until the corresponding `-c` check option is developed.

**Comment by Cyan4973** [comment]
With @WayneD 's #420, also offering `--check` ability for `--tag` format,
 the feature is now completed.
