### ISSUE TITLE
xxh3 is a long awaited feature since last year.

### ISSUE THREAD

**Issue by gitmko0** [Cyan4973/xxHash#388]
when can it be production ready? 0.73 only now... been waiting for it for more than a year. can we make it 1.0 already?

**Comment by Cyan4973** [comment]
It's coming along ...

**Comment by gitmko0** [comment]
big fan of your alien technology. a user of xxhash.
i'm totally clueless how your tech works but it's applied in my app a lot.
You are the expert, so whenever you say it's 1.0 then so be it. Great work! Big fan. 

Take your time to make it 1.0 because it's a backbone infrastructure piece we will be using forever.
(but if v0.8 can be compatible with 1.0, then please do launch it. performance wise can be fine tuned in future. i think all the fans here only need it to be consistent and good quality in result hash output since the performance increment from xxhash is so great and tempting to be migrated to.)

Thanks for the hard work!

**Comment by sergeevabc** [comment]
Actually I am, being an end-user, a bit lost about numeration. There is an utility called xxHash. There are three algorithms: 32-bit, 64-bit, 128-bit. What is XXH3 then?

**Comment by easyaspi314** [comment]
XXH3 refers to both XXH3_64bits and XXH128.

**Comment by gitmko0** [comment]
22 days... since 0.74... how many weeks to 0.8?

**Comment by easyaspi314** [comment]
> 22 days... since 0.74... how many weeks to 0.8?

It will be quicker if we don't have to tell you to be patient.

**Comment by Cyan4973** [comment]
[xxHash v0.8.0](https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0) has been released this morning, it stabilizes output values of `XXH3`.

**Comment by sergeevabc** [comment]
Hmm, I [wrote](https://github.com/Cyan4973/xxHash/issues/388#issuecomment-649475712) the following back in 2020:

> Actually I am, being an end-user, a bit lost about numeration. There is an utility called xxHash. There are three algorithms: 32-bit, 64-bit, 128-bit. What is XXH3 then?

And [again](https://github.com/Cyan4973/xxHash/issues/479#issuecomment-801379766) back in 2021:

> I am lost. xxhsum enables us to select an algorithm to use: either 0, 1, or 2 (aggrrhh, enumerating countable objects from zero is beyond my comprehension). Now, here comes the confusion, because there are XXH32, XXH64, XXH128, and… XXH3.

It's the end of 2023, but I'm still confused about the connection between numbers and algorithms _at a glance_, that is without diving into the wilds of this issue tracker, where one surely can find explanations. That's ultimately wrong, guys. During the evolution of this project several flavors of the algorithm were developed, they were compared and the results are listed on the official website, one of the flavors was chosen by default and... Which one is it, again? What is 1? Is it XXH<strong><ins>3</ins></strong>-64 or XXH-64 or...? See? This should be obvious _at a glance_. Consider reworking the [help screen](https://github.com/Cyan4973/xxHash/issues/345#issuecomment-1870670744), please.
