### ISSUE TITLE
[v0.8.0 Idea] Migrate xxhsum to C++

### ISSUE THREAD

**Issue by easyaspi314** [Cyan4973/xxHash#400]
Obviously a long term goal, but I am just thinking about how `xxhsum.c` is about 25% boilerplate.

I am primarily thinking of mostly just C with `std::string` and `std::vector`, and also doing something like this to simplify the `XXH_main` setup:

```cpp
static const char* cstr(const char* str) { return str; }
static const char* cstr(const std::string& str) { return str.c_str(); }
// Called with either char*[] or std::vector<std::string>
template <typename ArgvType>
int XXH_main(int argc, const ArgvType& argv)
{
    // just use cstr(x) for strcmp
}
#ifdef _WIN32
int XXH_wmain(int argc, wchar_t* utf16_argv)
{
    std::vector<std::string> utf8_argv;
    utf8_argv.reserve(size_t(argc));
    // Sweet mixed declarations, how I have missed you
    for (int i = 0; i < argc; i++) {
        utf8_argv.push_back(utf16_to_utf8(utf16_argv[i]));
    }
    return XXH_main(argc, utf8_argv);
}
#else
int main(int argc, char* argv[])
{
    return XXH_main(argc, argv);
}
#endif 
```
xxhsum.c is already valid C++, so we can do it one bit at a time just like how GCC transitioned. 

Thoughts? Obviously xxHash itself is going to remain C90 + `long long`.

**Comment by Cyan4973** [comment]
Sorry, `xxhsum` is planned to remained `C90` for the foreseeable future.
Sure, this choice is not as important as the library, 
but I'm not inclined to take a risk, especially as there is no need for it.

Refactoring `xxhsum.c` is not forbidden though.
For example, `xxhsum.c` doesn't have to remain a "single file" (in contrast with `xxhash.h`), which opens possibility to isolate some components, such as unicode supports, benchmark, self-test, etc. and adding some small shared units like resizable buffers if that's useful.

Finally, moving to `C99` is a possible direction in the future. But there is currently no urgency.
