### ISSUE TITLE
Allow reading stdin from console

### ISSUE THREAD

**Issue by jaki** [Cyan4973/xxHash#429]
Commit f7f77986f19a94a573590a0e0ec8c3caf48fe5c8 appears to have introduced support for using stdin.  For example, you can do

```sh
echo hi | xxhsum
```

and get

```
d50463dd92503d34  stdin
```

However, you are not allowed to supply stdin through the console.

```diff
+    // Check if input is defined as console; trigger an error in this case
+    if ((input_filename == stdinName) && IS_CONSOLE(stdin) ) return badusage(exename);
```

So running

```sh
xxhsum
```

gives

```
Wrong parameters
...
```

Reading from stdin through the console is a property that many programs have, such as `md5sum`, `sort`, and `tail`.  For them, you typically press ctrl+d for EOT.  `xxhsum` should also support this.

**Comment by Cyan4973** [comment]
I'm fine with having `xxhsum -` accepting to read input from the console,
but I'm more cautious about `xxhsum` (alone) waiting for the user to enter something and ending with a `Ctrl+D`
without a single word of help for the unknowing user to get out of this bind.

**Comment by jaki** [comment]
That sounds fair.  I would assume the user to be acquainted with ctrl+c, at least, but I don't mind restricting this feature to `xxhsum -`.

I did just find out that I can `xxhsum /dev/stdin` to get this affect without any work.  One quirk was that I had to ctrl+d twice (on linux).  I propose four options on what to do:

1. implement `xxhsum -` in code (the original plan)
1. route `xxhsum -` to `xxhsum /dev/stdin` (I'm not sure if this may have issues with weird file descriptor setups) (probably won't work on Windows)
1. document `xxhsum /dev/stdin` as the way to go for reading input from the console (probably won't work on Windows)
1. do nothing and close this issue (because it is workaroundable on Linux (and probably Unix))

**Comment by Cyan4973** [comment]
These are good suggestions.
Thinking about them, `1` is probably the better one.
`2` is not necessary : `xxhsum` can address `stdin` directly, without a need for a system-specific file handler.
`3` remains valid, it's basically another option on top of 1 for compatible systems (`posix` mostly).

**Comment by Cyan4973** [comment]
Completed in #431
