### ISSUE TITLE
Question about xxHash v0.8.0 release note

### ISSUE THREAD

**Issue by ifduyue** [Cyan4973/xxHash#443]
https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0

> After more than a year in the making, XXH3 has finally reached stable status, for both its 64-bit and 128-bit variants.
> While the code itself was in good enough shape for production use, the generated values could still change between versions. This limited XXH3 to local sessions only.
> From now on, output values produced by XXH3 for a given input and parameter set will remain identical across systems and across future versions. It makes it possible to store these values for later comparison, or to exchange them across network connections.

Second paragraph says the generated values could still change and hence XXH3 is limited to local sessions only.
Third paragraph says XXH3 is stable and suitable for across systems and  across future versions usages.

Is this a mistake because to me these two paragraphs are conflicted, or have I misunderstood the release note?

**Comment by Cyan4973** [comment]
One is in past tense (before)
the other uses present tense (from now on).

**Comment by ifduyue** [comment]
Oh, my poor English...  Thank you.
