### ISSUE TITLE
What is optimal block size for xxh3 (64 and 128 bit)?

### ISSUE THREAD

**Issue by AstolfoKawaii** [Cyan4973/xxHash#448]
By the "optimal block size" I mean the amount of bytes that hash may operate more efficiently if all updates are a multiple of this amount. (I didn't find is in docs)

(I am [writing](https://github.com/AstolfoKawaii/xxhash) go wrapper for xxh3 and the standard library requires this value, for example for sha256 it is 64 bytes)

Thank you.

**Comment by easyaspi314** [comment]
The answer to that is `XXH3_INTERNALBUFFER_SIZE`, which is currently defined to 256.
