### ISSUE TITLE
Error on files over ~2Gb on armv7: Value too large for defined data type

### ISSUE THREAD

**Issue by alex3kov** [Cyan4973/xxHash#451]
Version 0.8.0, works fine on the same armv7 machine on smaller files (<1Gb). Works fine on the same large (over 2Gb) files on amd64 machine. Using 32/64/128 versions of xxh*sum utility makes no difference.\
On armv7 SBC:
```sh
$ xxhsum -V
xxhsum 0.8.0 by Yann Collet 
compiled as 32-bit ARMv7 + unaligned little endian with GCC 9.3.0 
$ xxhsum large_file_2.4Gb.mp4 
Error: Could not open 'large_file_2.4Gb.mp4': Value too large for defined data type.
$ xxhsum file_842Mb.avi 
3047d17cd139a673  file_842Mb.avi
$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
Vendor ID:           ARM
Model:               2
Model name:          Cortex-A8
Stepping:            r3p2
CPU max MHz:         1008.0000
CPU min MHz:         624.0000
BogoMIPS:            1001.47
Flags:               half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
```
On amd64 laptop:
```sh
$ xxhsum -V
xxhsum 0.8.0 by Yann Collet
compiled as 64-bit x86_64 + SSE2 little endian with GCC 10.1.0
```
```

**Comment by easyaspi314** [comment]
Hmm

Does the build work if you do `make CFLAGS="-O2 -g -D_FILE_OFFSET_BITS=64"`

**Comment by Cyan4973** [comment]
`xxhsum` uses the standard `fopen()` / `fread()` / `fclose()` functions from `stdio.h`.
If they can't read files larger than 4 GB, we have to assume it comes from some limitation of the local `stdio` implementation.
This wouldn't be unheard of in 32-bit environments.
32-bit side-effects can have many forms, not being able to open a file > 4 GB is one of them (it's actually the first time I hear about this symptom, but is imho cleaner than streaming up to 4 GB and _then_ fail).

As suggested by @easyaspi314 , `_FILE_OFFSET_BITS=64` is a relatively standard way of forcing `stdio` implementation to use 64-bit counters and fields, thus solving the problem, and is expected to work on all "modern" posix systems.
Now, the success of this method will depend on which precise operating system and compiler is used on target armv7 machine

For reference : https://digital-domain.net/largefiles.html

**Comment by alex3kov** [comment]
<p>Yes it does. But I'm compiling with higher GCC version (than one used by distro
packagers), see below and OP:</p>
<pre><code class="language-sh">$ make CFLAGS=&quot;-O2 -g -D_FILE_OFFSET_BITS=64&quot;
cc -O2 -g -D_FILE_OFFSET_BITS=64   -c -o xxhash.o xxhash.c
ar rcs libxxhash.a xxhash.o
cc -O2 -g -D_FILE_OFFSET_BITS=64  xxhash.c -shared -Wl,-soname=libxxhash.so.0 -o libxxhash.so.0.8.0
ln -sf libxxhash.so.0.8.0 libxxhash.so.0
ln -sf libxxhash.so.0.8.0 libxxhash.so
cc -O2 -g -D_FILE_OFFSET_BITS=64   -c -o xxhsum.o xxhsum.c
cc -O2 -g -D_FILE_OFFSET_BITS=64  xxhash.o xxhsum.o  -o xxhsum
ln -sf xxhsum xxh32sum
ln -sf xxhsum xxh64sum
ln -sf xxhsum xxh128sum
$ ./xxhsum /path/to/large.mp4
7af43abdc0fec2d4  /path/to/large.mp4
$ ./xxhsum -V
xxhsum 0.8.0 by Yann Collet
compiled as 32-bit ARMv7 + unaligned little endian with GCC 10.2.0
</code></pre>
<p>P.S. Love the minimalism of xxhsum - compilation is like 1 min on Cortex-A8, no
deps.</p>
