### ISSUE TITLE
portable header guard

### ISSUE THREAD

**Issue by petervaro** [Cyan4973/xxHash#46]
The header `xxhash.h` uses the `#pragma once` as its *inclusion-guard*, which is still not in the standard (it was rejected, because it cannot be implemented reliably according to the committees), therefore it is not portable.

I would recommend to use the good ol' CPP definition based solution:

```C
#ifndef XXHASH_H_5627135585666179
#define XXHASH_H_5627135585666179 1

/* Here goes the header content */

#endif /* XXHASH_H_5627135585666179 */
```

*(The numbers are random ones, just to make sure the header guard identifier is unique.)*

**Comment by Cyan4973** [comment]
Right, it's a good point

**Comment by Cyan4973** [comment]
merged into master
