### ISSUE TITLE
Xxh3 with seed method doesn't use modified secret for input less or equal to XXH3_MIDSIZE_MAX

### ISSUE THREAD

**Issue by DoumanAsh** [Cyan4973/xxHash#463]
This is a bit of question rather than issue.
I do not believe there is a problem with this approach per se, but during porting your code I noticed that customized seed (derived from non-zero seed) is only used when we actually have input with size above XXH3_MIDSIZE_MAX

Is that intentional?
It is probably should be clarified in documentation as currently it makes you believe that any input would be different from default method such as `XXH3_64bits`

P.s. secret is used on small input for example:
https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L2813
https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L2795-L2796

**Comment by easyaspi314** [comment]
We use the seed directly against the default secret on the shorter lengths. 

It takes a lot of time to set up the generated secret.
