### ISSUE TITLE
How to use build modifiers with Makefile

### ISSUE THREAD

**Issue by janemba** [Cyan4973/xxHash#467]
Hello,

Well, is there any documentation on using build modifiers with Makefile ?

Thanks

**Comment by easyaspi314** [comment]
Are you talking about the config macros?

If so, they are primarily documented [here](https://github.com/Cyan4973/xxHash/blob/8296f4c32a300a6d2aa58261ef6e92f6a8f0e276/xxhash.h#L1098). Do a ctrl+f for `@ingroup tuning` to find the ones that haven't been grouped yet. They may eventually be extracted into a Doxygen site to avoid having to sift through xxhash.h.

For the Makefile, you can run `make help` although it doesn't completely cover the Makefile.

**Comment by janemba** [comment]
> Are you talking about the config macros?

Yes those one.

So if I have to use _cmake_, I guess I would use _-D_ switch.

`cmake -DXXH_STATIC_LINKING_ONLY ..`

So for the Makefile I appended the CFLAGS environment with _-D_ switch and I got the following:

```
$ CFLAGS+="-DXXH_STATIC_LINKING_ONLY" make                                                                                      
cc -DXXH_STATIC_LINKING_ONLY=1     -c -o xxhash.o xxhash.c
xxhash.c:40: warning: "XXH_STATIC_LINKING_ONLY" redefined
   40 | #define XXH_STATIC_LINKING_ONLY   /* access advanced declarations */
      | 
<command-line>: note: this is the location of the previous definition
ar rcs libxxhash.a xxhash.o
cc -DXXH_STATIC_LINKING_ONLY=1   -fPIC  xxhash.c -shared -Wl,-soname=libxxhash.so.0 -o libxxhash.so.0.8.0
xxhash.c:40: warning: "XXH_STATIC_LINKING_ONLY" redefined
   40 | #define XXH_STATIC_LINKING_ONLY   /* access advanced declarations */
      | 
<command-line>: note: this is the location of the previous definition
ln -sf libxxhash.so.0.8.0 libxxhash.so.0
ln -sf libxxhash.so.0.8.0 libxxhash.so
cc -DXXH_STATIC_LINKING_ONLY=1     -c -o xxhsum.o xxhsum.c
xxhsum.c:57: warning: "XXH_STATIC_LINKING_ONLY" redefined
   57 | #define XXH_STATIC_LINKING_ONLY   /* *_state_t */
[...]
```

**Comment by easyaspi314** [comment]
> > Are you talking about the config macros?
> 
> Yes those one.
> 
> So if I have to use _cmake_, I guess I would use _-D_ switch.
> 
> `cmake -DXXH_STATIC_LINKING_ONLY ..`

I may be wrong, but I don't think CMake works that way...

> So for the Makefile I appended the CFLAGS environment with _-D_ switch and I got the following:
> 
> ```
> $ CFLAGS+="-DXXH_STATIC_LINKING_ONLY" make                                                                                      
> cc -DXXH_STATIC_LINKING_ONLY=1     -c -o xxhash.o xxhash.c
> xxhash.c:40: warning: "XXH_STATIC_LINKING_ONLY" redefined
>    40 | #define XXH_STATIC_LINKING_ONLY   /* access advanced declarations */
>       | 
> <command-line>: note: this is the location of the previous definition
> ar rcs libxxhash.a xxhash.o
> cc -DXXH_STATIC_LINKING_ONLY=1   -fPIC  xxhash.c -shared -Wl,-soname=libxxhash.so.0 -o libxxhash.so.0.8.0
> xxhash.c:40: warning: "XXH_STATIC_LINKING_ONLY" redefined
>    40 | #define XXH_STATIC_LINKING_ONLY   /* access advanced declarations */
>       | 
> <command-line>: note: this is the location of the previous definition
> ln -sf libxxhash.so.0.8.0 libxxhash.so.0
> ln -sf libxxhash.so.0.8.0 libxxhash.so
> cc -DXXH_STATIC_LINKING_ONLY=1     -c -o xxhsum.o xxhsum.c
> xxhsum.c:57: warning: "XXH_STATIC_LINKING_ONLY" redefined
>    57 | #define XXH_STATIC_LINKING_ONLY   /* *_state_t */
> [...]
> ```

Oh, you don't define that on the command line (although we should macro guard it).

If you just want a static library, `make` will generate `libxxhash.a` for you.

**Comment by janemba** [comment]
> I may be wrong, but I don't think CMake works that way...

It is.

> Oh, you don't define that on the command line (although we should macro guard it).

Maybe I misunderstood the README but it says:

> The following macros can be set at compilation time to modify libxxhash's behavior. They are generally disabled by default.

So _compilation time_ isn't for the macro defined for the preprocessor like `gcc -D` does ? Should I use those macros by modifying the gcc line in the Makefile ?

**Comment by t-mat** [comment]
> So compilation time isn't for the macro defined for the preprocessor like gcc -D does ? Should I use those macros by modifying the gcc line in the Makefile ?

@janemba, in this case "compilation-time" means "at the time of compilation of your own program's source code which includes <xxhash.h>".  It doesn't mean "the compilation time of the xxHash library/CLI."

Therefore, if you want to use `XXH_STATIC_LINKING_ONLY`, you should put the following code at the beginning of your source code

```C
#define XXH_STATIC_LINKING_ONLY
#include <xxhash.h>
...
```

So, `XXH_STATIC_LINKING_ONLY` means

- Your code can access extra details/internals of the library.
- But you must link xxhash as a static library.
- Because xxhash library may change its internal in future.
- It also means xxhash doesn't guarantee to work `XXH_STATIC_LINKING_ONLY` features with future version of xxhash as a dynamic link library.
