### ISSUE TITLE
XXH3 sequential seeds generate same set of outputs on small (<=8b) sequential (LE) inputs 

### ISSUE THREAD

**Issue by pdillinger** [Cyan4973/xxHash#469]
The new Ribbon filter and others like it (e.g. Xor filter) need to be able to "re-seed" if construction fails with current hash seed. It's convenient to be able to simply iterate sequentially through hash seeds until a successful one is found. But I recently noticed that for inputs <=8b, a sequential set of inputs will generate (permutations of) the same set of outputs with sequential seeds, with XXH3.

Although I plan a better unit test for this, I modified my existing unit test for this case and it fails terribly, as expected based on code inspection.
https://github.com/pdillinger/rocksdb/commit/55a0cae879adfb75e78bad1188e35e9f6a874cdc

    make ribbon_test && ./ribbon_test

With same inputs except extended to 9 bytes instead of 8, it passes the more stringent test

    ./ribbon_test --thoroughness=100

Btw, my plan is to just work around this generally by avoiding sequential seeds. (I'll probably use multiplication/addition by a large prime; probably don't need to go nonlinear here.)

**Comment by easyaspi314** [comment]
That is expected. The "unpredictability" from changing the seed should come from the seed itself. If you are using sequential seeds, that is your problem. 

Unfortunately there is nothing we can do. XXH3 is finalized. Any future changes are going to be optimizations to the implementation itself, not the algorithm.

**Comment by pdillinger** [comment]
I don't see that declaimed anywhere. To me it seems reasonable to expect as much quality from HashWithSeed(\<data\>,\<seed\>) as from HashWithSeed(append(\<seed\>, \<data\>), 0).

**Comment by pdillinger** [comment]
I see reference to XXH3_generateSecret, but that seems rather heavyweight and inconvenient to simply iterate through independent seeds.

**Comment by Cyan4973** [comment]
If I do understand the topic correctly,
you are producing a suite of numbers
by iterating through the `seed` channel.

I don't remember having tested this scenario,
though I have instead tested the scenario where the _input_ is incremented linearly.
This last one would pass `practrand`, making it a good pseudo-random generator.

I naively assumed that linear increment of the `seed` would result in a similar outcome.
And maybe that's an incorrect assumption.

**Comment by Cyan4973** [comment]
Actually, there is a `smhasher` test which measures exactly this scenario: 
https://github.com/rurban/smhasher/blob/3f5ff072eb2076566a2a70c57aee3d9a450a0c87/KeysetTest.h#L620

Surprisingly, it did not detect anything wrong regarding `XXH3`...

**Comment by pdillinger** [comment]
I'm sure you'd get a nice spread of results by iterating on seed for a single input. The problem is correlation when both your inputs are linearly related and your seeds are linearly related.

**Comment by Cyan4973** [comment]
> The problem is correlation when both your inputs are linearly related and your seeds are linearly related.

Oh, that's indeed a much harder problem.

Thing is, this scenario was also supposed to be checked, with the new "PerlinNoise" test : https://github.com/rurban/smhasher/blob/master/KeysetTest.h#L84

It's controlling outcome of linear correlation of `seed` and `input`
for `input` sizes of 16, 32, 64 and 128-bit.

It also did not flagged any problem for `XXH3`,
though maybe the test is flawed, or incomplete.

**Comment by pdillinger** [comment]
I should have checked the lastest version. We forked XXH3 from 0.7.2 and it appears this has been fixed since then, probably with

    seed ^= (xxh_u64)XXH_swap32((xxh_u32)seed) << 32;

I would expect the PerlinNoise test to find the issue. Thanks

**Comment by easyaspi314** [comment]
Yup, that's the line that we added to fix the questionable PerlinNoise test, the scenario you are describing.
