### ISSUE TITLE
xxhsum is unable to verify checksum of file from STDIN

### ISSUE THREAD

**Issue by lacek** [Cyan4973/xxHash#470]
In common hash utilities (such as `md5sum` and `shasum`), the `-c` option allows input file from STDIN when the file name is `-`, e.g. for `md5sum`:

```
$ md5sum < test.txt > test.txt.md5
$ md5sum -c test.txt.md5 < test.txt
-: OK
```

When it comes to `xxhsum` (v0.8.0), error is reported:

```
$ xxhsum < test.txt > test.txt.xxh
$ xxhsum -c test.txt.xxh < test.txt
test.txt.xxh:1: Could not open or read 'stdin': No such file or directory.
1 listed file could not be read
```

**Comment by Cyan4973** [comment]
Implemented by @t-mat in latest `dev` branch update
