### ISSUE TITLE
Still can't compile on CentOS 7

### ISSUE THREAD

**Issue by willbryant** [Cyan4973/xxHash#473]
Following @easyaspi314's commits in #465 which @easyaspi314 merged in 4aa3d59, the #464 situation is incrementally better now, in the respect that it looks like I can now manually turn off variants.

But out of the box, the dev branch (incl. later fixes) still won't compile on CentOS 7.

Different reason now, the intrinsics type isn't present but `XXH_DISPATCH_AVX2` is still on by default; `__AVX2__` isn't, so `immintrin.h` doesn't get included.

```
In file included from /tmp/src/xxHash/xxh_x86dispatch.c:208:0:
/tmp/src/xxHash/xxhash.h: In function 'XXH3_accumulate_512_avx2':
/tmp/src/xxHash/xxhash.h:3801:5: error: unknown type name '__m256i'
     {   XXH_ALIGN(32) __m256i* const xacc    =       (__m256i *) acc;
     ^
/tmp/src/xxHash/xxhash.h:3801:55: error: '__m256i' undeclared (first use in this function)
     {   XXH_ALIGN(32) __m256i* const xacc    =       (__m256i *) acc;
```

`immintrin.h` is in fact present on CentOS 7, so it's interesting that `__AVX2__` is not defined; `__SSE2__` is (and `emmintrin.h` does exist and get included).

Now, looking at the current logic:

```
#  if (defined(__GNUC__) \
       && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 7))) /* GCC 4.7+ */ \
   || (defined(_MSC_VER) && _MSC_VER >= 1900) /* VS 2015+ */ \
   || (defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 180030501) /* VS 2013 Update 2 */ \
   || XXH_HAS_INCLUDE(<avx2intrin.h>) /* GCC/Clang internal header */
```

I notice that `avx2intrin.h` does exist. But that's sort of irrelevant, because we're not including it, because there's completely separate logic:

```
#  if defined(__AVX2__)
#    include <immintrin.h>
#  elif defined(__SSE2__)
#    include <emmintrin.h>
```

IMHO we sort of need to go one way or the other, these two blocks need to effectively align.

**Comment by willbryant** [comment]
Ah, turns out there's another separate place the includes actually get done for xxh_x86dispatch.c:

```
#if defined(__GNUC__)
#  include <emmintrin.h> /* SSE2 */
#  if XXH_DISPATCH_AVX2 || XXH_DISPATCH_AVX512
#    include <immintrin.h> /* AVX2, AVX512F */
#  endif
```

At first, this looks like it should pull in the necessary definitions - `__m256i ` is defined in `avxintrin.h` and it's included by `immintrin.h`. But `immintrin.h` itself has guards, eg.:

```
#ifdef __AVX__
#include <avxintrin.h>
#endif

#ifdef __AVX2__
#include <avx2intrin.h>
#endif
```

Which is interesting, because it means that:
* It doesn't seem really necessary to have the same `if defined(__AVX2__)` guard on the inclusion of `immintrin.h` in `xxhash.h`, it could just be included all the time if we want, but
* Unfortunately including it solves nothing because `immintrin.h` will still not include `avxintrin.h` where `__m256i` is defined (and we'll have the same problem for the actual AVX2 intrinsics).

`avxintrin.h` tells us to include `immintrin.h` instead of `avx2intrin.h`, so bypassing `immintrin.h` is out. Neither `emmintrin.h` (nor any of the other header files) include `avxintrin.h`.

This all made me confused how this all compiles successfully on other distros/versions. Well, on Ubuntu 20.04, there's no guards at all in `immintrin.h`. And on my mac, the header file that comes with clang has a different guard:

```
#if !defined(_MSC_VER) || __has_feature(modules) || defined(__AVX__)
#include <avxintrin.h>
#endif
```

`_MSC_VER` is never set, so `avxintrin.h` gets included.

So I'm leaning towards thinking that we need to turn XXH_DISPATCH_AVX2 off for older versions of GCC, because we don't want to compile with `-mavx -mavx2` and without them we will not get `avxintrin.h` and `avx2intrin.h`.

But I note that even changing the GCC versions in this logic:

```
#ifndef XXH_DISPATCH_AVX2
#  if (defined(__GNUC__) \
       && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 7))) /* GCC 4.7+ */ \
   || (defined(_MSC_VER) && _MSC_VER >= 1900) /* VS 2015+ */ \
   || (defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 180030501) /* VS 2013 Update 2 */ \
   || XXH_HAS_INCLUDE(<avx2intrin.h>) /* GCC/Clang internal header */
#    define XXH_DISPATCH_AVX2 1   /* enable dispatch towards AVX2 */
#  else
#    define XXH_DISPATCH_AVX2 0
#  endif
#endif /* XXH_DISPATCH_AVX2 */
```

Won't work, because the `XXH_HAS_INCLUDE(<avx2intrin.h>)` case will still return true - it's there, it's just useless to us!

**Comment by willbryant** [comment]
Looks like the guards were removed from the GCC headers in https://patchwork.ozlabs.org/project/gcc/patch/CAAs8HmwAVJqNe+e1C17Vnq5PcEvYuaBfw-jhGU1mRLLDMpsSvw@mail.gmail.com/

I have no idea what GCC version that got released in :(

**Comment by easyaspi314** [comment]
Ah yes I mentioned that in another issue. It was merged early.

I believe that it is impossible to do dispatching on GCC < 4.9 without messing around with internals or inline asm

**Comment by willbryant** [comment]
OK cool. One error in what I said above, `XXH_HAS_INCLUDE(<avx2intrin.h>)` is not a problem, because this version of GCC doesn't have `__has_include`. Therefore, we can just change the logic for `XXH_DISPATCH_AVX2` to exclude GCC <5 (and dispatching will still work for SSE2).

Submitted #474 to resolve.
