### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by 0xVavaldi** [Cyan4973/xxHash#476]
Having it be usable as a composer package would make integration in web projects significantly easier

**Comment by exussum12** [comment]
https://github.com/exussum12/xxhash   can be installed via composer

```composer require exussum12/xxhash```

It should solve some needs, add an issue if there is something else needed (Ive seen one added for 128 bit, I can add that in)

**Comment by 0xVavaldi** [comment]
I'm the one that added the 128bit issue for the linked repo

**Comment by exussum12** [comment]
@Cyan4973 is there a document like https://github.com/Cyan4973/xxHash/blob/dev/doc/xxhash_spec.md for xxh128 ? 

Specifically im looking for what do with with the high and low bits to convert to a hash - similar to https://github.com/Cyan4973/xxHash/blob/dev/doc/xxhash_spec.md#step-7-output-1

**Comment by Cyan4973** [comment]
There is currently no specs document for `XXH3`. This will come at a later stage (circa ~v1.0).

> Specifically im looking for what do with with the high and low bits to convert to a hash

This is achieved by `XXH128_canonicalFromHash()` :
https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L838
