### ISSUE TITLE
xxh16 aka xxhash width 16 ?

### ISSUE THREAD

**Issue by joakim-tjernlund** [Cyan4973/xxHash#497]
Would lite to replace a CRC16 with xxhash.
can xxhash32 be folded into 16 bits somehow?

**Comment by Cyan4973** [comment]
One could extract the lower or upper bits of `xxh32`. It will result in a 16-bit hash with good randomness properties.
At its core, `xxh32` will still use 32-bit arithmetic operations.

**Comment by joakim-tjernlund** [comment]
anywhere near crc16?

**Comment by Cyan4973** [comment]
what do you mean ?

**Comment by joakim-tjernlund** [comment]
is the quality of the 16 bit xxhash about the same as the quality of crc16?

**Comment by Cyan4973** [comment]
It's different.
16-bit xxhash will actually offer more uniform randomness than crc16.

Meaning that, given 2 different inputs, whatever the difference is (a single bit, or completely different), the probability of collision within xxh16 remains a steady 1 / 2^16.

In contrast, with `crc16`, a one bit difference between 2 inputs _guarantees_ they will produce different values. However, 2 completely different inputs will have a higher probability of collision (I don't have precise number, but it's typically 3x to 5x larger that flat randomness).
