### ISSUE TITLE
Confusing output with narrow terminal window

### ISSUE THREAD

**Issue by llamafilm** [Cyan4973/xxHash#50]
In OS X, when the Terminal window is narrower than the output of xxhsum, the "Loading filename..." display is not erased after the hash is calculated.  This causes a confusing display, as shown below.  Here I issue the same command twice, but the second time, the Terminal window is narrower.  This is more of a problem when using a very long path or filename as input.

```
macpro-yosemite:A007R6QT dit$ xxhsum-dev A007C001_160108_R6QT.mov 
1886a9da141ee804  A007C001_160108_R6QT.mov      
 
macpro-yosemite:A007R6QT dit$ xxhsum-dev A007C001_160108_R6QT.mov 
Loading A007C001_160108_R6QT.mov..1886a9da141ee804  A007C001_160108_R6QT.mov       
```

**Comment by Cyan4973** [comment]
Could limiting the size of filename do the trick ?
The idea would be to ensure it never breaks the 80 columns assumption.

**Comment by llamafilm** [comment]
I don't think that's practical, because sometimes people need to use long filenames or paths.  Ideally you could delete the "Loading filename..." text once the hash is calculated.

**Comment by Cyan4973** [comment]
> Ideally you could delete the "Loading filename..." text once the hash is calculated.

Well, that's already what happens today, with : 
DISPLAY("\rLoading %s...        __\r__", fileName);

The final  __\r__ means "get back to beginning of the line".
But it's already too late if the size of a line has been crossed : it will only get back to the beginning of the last line.

That's unfortunately all that can be done using standard C. Beyond that one needs dependency to complex libraries.


> I don't think that's practical, because sometimes people need to use long filenames or paths

The proposal is only to limit the size of filename displayed during the message "loading filename...."
But input filename can still be as long as necessary, including a very long path.

So for example : 

`./xxhsum /very/long/path/to/filename`
would be reduced to : 
`loading filename ....` or even `loading lename...` if filename alone is really very long ....

**Comment by llamafilm** [comment]
I see what you mean now.  Yes, that makes sense to truncate the loading display.  But I do think it's important to keep the full filename for the final display, in case the user is saving output for logging.
Sorry I'm not much of a C programmer, just a power user.  I appreciate your work.

**Comment by Cyan4973** [comment]
Loading display and result display are 2 different things.

They do overlap on screen, so it may feel like they are the same, but that's not the case, precisely to support redirection to log file.

So if someone does : 
`./xxhsum file* > log`, all files which name starts by `file*` will be hashed, and the result will be written into file `log`. Only the result will appear in the `log` file, while the console will only display the "loading" messages.

The intention is to inform a human user that some activity is ongoing, and can be tracked. This is less confusing than waiting for a silent process to finish with no feedback, which could be easily confused with a process stuck into an infinite loop.

Result display will preserve the full path, obviously. Only the short-lived "information" display will be limited.

**Comment by Cyan4973** [comment]
A new version of `xxhsum` has been uploaded into [dev branch](https://github.com/Cyan4973/xxHash/tree/dev).

It should limit the size of "loading" notification so that it remains within a line budget, and get properly overwritten either by the hash result or the following notification.

For your testing

**Comment by llamafilm** [comment]
Works well so far.
