### ISSUE TITLE
Add Meson support or alternatively add xxhash 0.8 to wrapdb

### ISSUE THREAD

**Issue by tristan957** [Cyan4973/xxHash#500]
I am a Meson user using your project in our project. I'd like to either propose adding Meson support to xxhash natively or add v0.8 to the wrapdb. If either of those is out of scope for the parent project, I can go and add some v0.8 support to http://github.com/mesonbuild/xxhash myself. Not a big deal at all :). Thanks again for the project.

**Comment by tristan957** [comment]
Reading if you are unfamiliar with Meson's wrapdb: https://mesonbuild.com/Adding-new-projects-to-wrapdb.html

**Comment by tristan957** [comment]
I would plan on adding all the build options as Meson options for complete coverage of the current build system https://github.com/Cyan4973/xxHash#build-modifiers. Which the current 0.6.5 version up on wrapdb sorely lacks

**Comment by Cyan4973** [comment]
Hi @tristan957 

I generally only provide a standard `Makefile` as a default build system,
while additional ones, like meson, are community provided.

If it makes sense to be provided as part of upstream,
we could have a `meson` build hosted inside a `build` subdirectory.
We would then also need a relevant test in CI, to ensure future changes don't break it.

Alternatively, it can be maintained as a separate recipe,
like the proposed http://github.com/mesonbuild/xxhash ,
which might actually fit better with the rest of meson ecosystem.

**Comment by tristan957** [comment]
@Cyan4973 makes sense to me. I'll mark it on my list of things to do, adding 0.8 support to wrapdb. Thanks!

**Comment by tristan957** [comment]
https://github.com/mesonbuild/xxhash/pull/2

@Cyan4973 would appreciate a once over if you have a chance.

**Comment by tristan957** [comment]
Implemented a few months back. Closing.
