### ISSUE TITLE
XXH3_len_4to8_64b -> XXH_ASSERT criteria appears to be incorrect

### ISSUE THREAD

**Issue by La-cu-na** [Cyan4973/xxHash#522]
Running on OS-X the following assert fired:

XXH_ASSERT(4 <= len && len < 8);

The length passed to XXH3_len_4to8_64b was _exactly_ 8

Should the assert criteria not be:

XXH_ASSERT(4 <= len && **len <= 8**);

**Comment by Cyan4973** [comment]
Right, it's `4to8`, both bounds included.
