### ISSUE TITLE
xxhsum client is not properly designed to respect stdin and stdout, --strict does not function

### ISSUE THREAD

**Issue by aceofbitcoin** [Cyan4973/xxHash#526]
#xxhsum --strict -c borg.64.xxh
./dat-eu-c-001/index.31: OK
./dat-eu-c-001/integrity.31: OK
./dat-eu-c-001/data/0/4: OK

#xxhsum --strict -c borg.64.xxh > log.txt
log.txt is empty

#xxhsum --strict -c borg.64.xxh > log.txt 2>&1
log.txt is empty as well

#xxhsum --strict -c borg.64.xxh &> log.txt
log.txt is empty again

Alter some files
Output does not show FAILED status such as the counterpart shasum would do.

**Comment by t-mat** [comment]
Hi, @nihsotas.
Unfortunately I couldn't reproduce your issue at all.
Could you provide just a bit more information about your environment?

I've tried to reproduce your issue with the following commands.  Please feel free to point out mistake in my procedure.

```
# Clone and build
$ cd
$ git clone https://github.com/Cyan4973/xxHash
$ cd xxHash
$ git log -1 --format="%H"
c0e86bc030cfd5ae08d529acac0a8b8a7c5252e6
$ make
$ mkdir issue-526
$ cd issue-526
$ ../xxhsum --version
xxhsum 0.8.0 by Yann Collet
compiled as 64-bit x86_64 + SSE2 little endian with GCC 9.3.0

# Generate random file
$ base64 /dev/urandom | head -c 500 > file1.b64
$ base64 /dev/urandom | head -c 500 > file2.b64
$ base64 /dev/urandom | head -c 500 > file3.b64

# Create .xxh file
$ ../xxhsum -H1 *.b64 > files.xxh

# Verify 1
$ ../xxhsum --strict -c files.xxh > log1.txt
$ cat log1.txt
file1.b64: OK
file2.b64: OK
file3.b64: OK

# Verify 2
$ ../xxhsum --strict -c files.xxh > log2.txt 2>&1
$ cat log2.txt
file1.b64: OK
file2.b64: OK
file3.b64: OK

# Verify 3
$ ../xxhsum --strict -c files.xxh &> log3.txt
$ cat log3.txt
file1.b64: OK
file2.b64: OK
file3.b64: OK

# Alter a file
$ tac file2.b64 | tee file2.b64 > /dev/null
$ ../xxhsum --strict -c files.xxh
file1.b64: OK
file2.b64: FAILED
file3.b64: OK
1 computed checksum did NOT match
```

**Comment by aceofbitcoin** [comment]
OS Ubuntu kernel 5.11.0-17-generic
I did install b3sum to continue my work and now suddenly xxhsum works as expected...so I presume it was related to some lib
Works now as well ?! I think it was something odd

**Comment by t-mat** [comment]
It's really strange.  But since it also means no one is able to reproduce this issue for now, I can't investigate it further.
