### ISSUE TITLE
About travis-ci.org closure

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#529]
ORG Shutdown - https://blog.travis-ci.com/2021-05-07-orgshutdown
> - Travis-ci.org shut down will occur on May 31, 2021

Do we have a plan to migrate from travis-ci.org to .com or other CI service?

**Comment by Cyan4973** [comment]
Thanks for the PR transferring tests to Github Actions @t-mat  !

As we know, some tests can't be transferred, as they are not yet available on GA (and may never be).

For these tests, I was wondering if it would be acceptable to keep them on `travis-ci`, although not `.org` since it's closing.
I'm unaware though if moving to `.com` is more than a domain name change. aka, does it also translate into a change of contract, making it less suitable to open source project.

**Comment by t-mat** [comment]
Yes, `.org` to `.com` migration makes differece.  But we can assume they are virtually same for us so far.

- At `travis-ci.com`, [they offer 10,000 credits as a "Free Plan"](https://travis-ci.com/plans).
- At `travis-ci.com`'s [Billing Overview](https://docs.travis-ci.com/user/billing-overview/#usage---credits), we can confirm that it takes 10 credits/minute for Linux instance.
- At github.com, we have almost 1200 commits since July 2014.  Therefore, as an average, we had 15 commits in every month (`ceil(1200.0/((2021-2014)*12))`).
- If we suppose our CI consumes 30 machine minutes for every commit, we can say that we consume 450 (`15*30`) minutes for every month.  It also means 4500 credits/month.
  - Actually, we consumes 10 to 20 machine minutes at `travis-ci.org`.

So, I can say that 10,000 credits/month limitation is reasonable for a single `travis-ci.com` account which has up to 2 projects.
  - I mean `10000/2 >= 4500`.

But anyway, it'd be nice to remove some tests from `.travis.yml` when we'll confirm both `travis-ci` and GH-Actions works same way.
For now, I think that we can safely remove macOS test and QEMU tests (non-native tests) from our `.travis.yml`.  But I'd like to wait someone will confirm both of CIs are basically do same tests.

**Comment by Cyan4973** [comment]
Thanks for the great explanation and the pointers.

Yes, that sounds like a good plan.

**Comment by Cyan4973** [comment]
For some reason, I've been unable to transfert `xxhash` to `travis.com`, even though I followed the instructions.
Something doesn't seem to work either in the flow of information between github and travis, or within travis.

Not sure if it matters though. We have most tests on github actions now.

**Comment by cclauss** [comment]
https://github.com/curl/curl/issues/7150
