### ISSUE TITLE
Pure java implementation of XXH3 and XXH128

### ISSUE THREAD

**Issue by gzm55** [Cyan4973/xxHash#534]
A pure java implementation of `XXH3` and `XXH128` is released with [Zero-Allocation-Hashing 0.15](https://github.com/OpenHFT/Zero-Allocation-Hashing/releases/tag/zero-allocation-hashing-0.15).

**Comment by Cyan4973** [comment]
Great work @gzm55 !
The Java port list has been updated to reflect the new capability !

**Comment by gzm55** [comment]
@Cyan4973 as notes in #518 , the performance of this porting is not that outstanding as C version, and even slower than the java version XXHASH64. i think other language porting without vectorize instructions will meet the same situation.

**Comment by Cyan4973** [comment]
Yes, this is likely.
Accessing vector instructions is important to `XXH3` performance.
Each language features its own set of limitations when it comes to vector instructions.
Of course, this is also a moving picture, and improvements also happen.
I can only hope that vector instruction support will improve on Java in the future.
