### ISSUE TITLE
XXH3 test vectors

### ISSUE THREAD

**Issue by mattmook** [Cyan4973/xxHash#535]
Are there any published test vectors for XXH3?

Where the resultant hash values have previously changed it would be useful to have a set of known good values to be able to evaluate the accuracy of third party libraries. This is especially necessary given some of these ports may be based on older versions before the output values were stabilised. Additionally, while I have a native version compiled locally there's no guarantee that my compiler settings mean my build matches what is actually expected.

**Comment by Cyan4973** [comment]
`cli/xsum_sanity_check.c` implements a bunch of tests scenarios alongside [a number of test vectors](https://github.com/Cyan4973/xxHash/blob/dev/cli/xsum_sanity_check.c#L99) for each variant.
These tests are automatically run in CI over multiple architectures.
They can also be run locally by using `xxhsum -b` command.
(sanity tests are transparent though, and will only complain if a wrong return value is detected).

**Comment by mattmook** [comment]
Not sure how I managed to miss all those entries, that's perfect.

I'm correct in assuming streaming vs non-streaming should result in the same results?

I ask because while I have a non-steaming implementation working, I'm actually in the process of porting XXH3 streaming to Kotlin Multiplatform. Also not convinced the non-streaming implementation matches spec so those vectors will come in handy.

**Comment by Cyan4973** [comment]
> I'm correct in assuming streaming vs non-streaming should result in the same results?

correct
