### ISSUE TITLE
Kotlin Multiplatform port of the xxHash family

### ISSUE THREAD

**Issue by mattmook** [Cyan4973/xxHash#539]
I've just released v0.5.0 of my Kotlin Multiplatform [cryptohash](https://github.com/appmattus/crypto/tree/main/cryptohash/) library which adds support for XXH32, XXH64, XXH3 and XXH128; streaming mode only as all algorithms are coded to the same Digest interface.

This is compiled for JVM (inc Android), iOS, watchOS, tvOS, macOS, windows, linux, albeit without SIMD support so performance is very much dependent on the Kotlin compiler. The priority for this library is cross platform compatibility rather than performance.

**Comment by Cyan4973** [comment]
Added Kotlin port to the list of `xxHash` ports
