### ISSUE TITLE
.NET implementation of XXH3

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [Cyan4973/xxHash#544]
I'm currently using a .NET implementation of the `XXH64` algorithm but I noticed that `XXH3` performs quite faster according to your benchmark.
Is there any available .NET implementation of the `XXH3` version?

**Comment by Cyan4973** [comment]
There is this one : 
https://github.com/Zhentar/xxHash3.NET

Unfortunately, it's outdated, and doesn't run as fast as `XXH64`.

Yet, it could be a useful inspiration for anyone trying to achieve an equivalent objective.

**Comment by gabriele-ricci-kyklos** [comment]
It also states that is poorly tested, not good for production code imo.
I'd definitely go for the `XXH64`, many thanks.
