### ISSUE TITLE
Split CLI license out of LICENSE

### ISSUE THREAD

**Issue by tamird** [Cyan4973/xxHash#548]
Hello. The grpc project currently uses a subset of this repository that *doesn't* include the CLI (https://github.com/grpc/grpc/tree/master/third_party/xxhash). Would it be possible to move remove the CLI's license from the main LICENSE file so that the GPL text does not appear in the grpc repo? That would make it easier for Fuchsia to import grpc.

Thank you!

**Comment by Cyan4973** [comment]
This request seems in direct conflict with [this prior request](https://github.com/Cyan4973/xxHash/issues/253).

Would love to find a solution which is fine for everybody.

**Comment by tamird** [comment]
That makes sense. Looking at the prior request, it's talking about the contrary license in xxhash.c. As far as I can tell, that file is only needed by the CLI. Perhaps it can move into the CLI directory?

**Comment by tamird** [comment]
Actually, the relevant file shuffling was already done in https://github.com/Cyan4973/xxHash/pull/542. Perhaps these requests are no longer in conflict?

**Comment by tamird** [comment]
Related: https://github.com/grpc/grpc/pull/26879. Kind of a bummer that there isn't a better way to import just the library part of xxhash.

**Comment by tamird** [comment]
Friendly ping! Any thoughts on this? I'd like to upgrade Fuchsia's grpc dependency and it'd be nice to sidestep potential licensing issues by separating the licenses.

**Comment by Cyan4973** [comment]
Sorry, I'm not yet clear about what's the best way forward on this topic.
