### ISSUE TITLE
Add more compilers to CI

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#554]
I think PR #553 hits the difference between `gcc-9` and `gcc-10`.
Since it's difficult to find these differences, test procedure should help contributors.

We can import lz4's matrix as a first step.

**Comment by Cyan4973** [comment]
Agreed, this is a good idea.

**Comment by t-mat** [comment]
note: New test should include `make usan`.  See #557.

**Comment by t-mat** [comment]
I've managed to import lz4's compiler/OS matrix in [my fork](https://github.com/t-mat/xxHash/commits/gh-act-compilers).

- Here's a [test log](https://github.com/t-mat/xxHash/runs/3353623266).

It supports the following compilers

- `gcc-[4.8-11]`
- `clang-[4.9-12]`

Before sending PR of it, I'll post cherry-pick PR for each small issues.

Since I'll keep `git-rebase`, please don't care about my fork.

TODO

- [ ] Add `make usan` (after landing?).

**Comment by Cyan4973** [comment]
Thanks @t-mat ,
these are good objectives and plan.
