### ISSUE TITLE
Configure approval settings for GH-Actions

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#555]
So far, GitHub-Actions are prevented to run automatically for each PR from first-time contributors.  Usually they see information badge which states "1 workflow awaiting approval".

This is a default behavior of GH-Actions, but we can change it (ease the restriction) with the following settings

- [Configuring required approval for workflows from public forks](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#configuring-required-approval-for-workflows-from-public-forks) - Disabling or limiting GitHub Actions for a repository - GitHub Docs

I'm not sure that pushing the approve button is burden for @Cyan4973 or not.  But since we don't see any abuse in our repo for now, automatic approval for CI may help contributors to be noticed their errors earlier.

**Comment by Cyan4973** [comment]
That's a good point. Indeed, since there are no abuse currently, it seems better for contributors to see the results of their PR sooner (although I would certainly prefer contributors to run these tests on their own fork first).

**Comment by Cyan4973** [comment]
Following the doc page (thanks @t-mat for the clear link),
approval requirement has been reduced to : 
"Require approval for first-time contributors who are new to GitHub"
