### ISSUE TITLE
`XXH_ALIGN_MEMBER()` needs improvement

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#557]
When we run the following command, it fails to build `collisionsTest`.

```sh
V=1 make clean usan
```

```
...
clang -Werror -O3 -I ./ -I ../../ -I allcodecs/  -c -o main.o main.c
clang -Werror -O3 -I ./ -I ../../ -I allcodecs/  -c -o pool.o pool.c
clang -Werror -O3 -I ./ -I ../../ -I allcodecs/  -c -o threading.o threading.c
clang++ -Wall -Wextra -Wconversion -std=c++11 -O3 -I ./ -I ../../ -I allcodecs/  -c -o sort.o sort.cc
In file included from sort.cc:34:
../../xxhash.h:983:4: error: 'alignas' attribute cannot be applied to types
   XXH_ALIGN_MEMBER(64, XXH64_hash_t acc[8]);
   ^
../../xxhash.h:937:47: note: expanded from macro 'XXH_ALIGN_MEMBER'
#   define XXH_ALIGN_MEMBER(align, type) type XXH_ALIGN(align)
                                              ^
../../xxhash.h:925:29: note: expanded from macro 'XXH_ALIGN'
#  define XXH_ALIGN(n)      alignas(n)
                            ^
...
```

This error only happens when we use `xxhash.h` with `clang++`.  Because

- It doesn't define `__STDC_VERSION__` for C++ code.
- It defines `__GNUC__`.
- But it doesn't accept GCC style attribute.

I don't remember older (pre-C++11 era) `clang++` accepts GCC style attribute or not.  But it's safe to exclude C++11 from the non-standard declaration.

```cpp
	/* Old GCC versions only accept the attribute after the type in structures. */
	#if !(defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L))   /* C11+ */ \
+	    && ! (defined(__cplusplus) && (__cplusplus >= 201103L)) /* >= C++11 */ \
	    && defined(__GNUC__)
	#   define XXH_ALIGN_MEMBER(align, type) type XXH_ALIGN(align)
	#else
	#   define XXH_ALIGN_MEMBER(align, type) XXH_ALIGN(align) type
	#endif
```

**Comment by Cyan4973** [comment]
I've tried to reproduce this issue, but failed so far.
FYI, tests were performed on both macOS 11.5 and Linux Ubuntu 21.

Which configuration have you been using to produce this issue ?

**Comment by t-mat** [comment]
> Which configuration have you been using to produce this issue ?

I'm using WSL (ubuntu-20.04) with the following compilers

```
$ uname -sro
Linux 5.4.72-microsoft-standard-WSL2 GNU/Linux

$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

$ clang --version
clang version 10.0.0-4ubuntu1

$ clang++ --version
clang version 10.0.0-4ubuntu1

$ make --version
GNU Make 4.2.1
```

I can reproduce this issue with the following commands

```sh
cd
git clone https://github.com/Cyan4973/xxHash.git xxHash-issue-557
cd xxHash-issue-557
V=1 make clean usan
```

Perhaps, you need fresh clone.  Because `clean` in `tests/Makefile` doesn't call `clean` in its child `Makefile`s (`bench` and `collisions`).

The following commands may work for you.

```
make -C ./tests/bench/ clean
make -C ./tests/collisions/ clean
V=1 make clean usan
```

My WIP GH-Actions test [also reproduce this issue](https://github.com/t-mat/xxHash/runs/3344995551#step:11:642) with other versions of `clang++`s.

**Comment by Cyan4973** [comment]
Thanks ! Got it, now it's reproduced
