### ISSUE TITLE
Is Ubuntu 16.04 supported?

### ISSUE THREAD

**Issue by harashimahashi** [Cyan4973/xxHash#586]
There is no such label, however it would be logical if it is supported.

**Comment by Cyan4973** [comment]
`zstd` is highly portable, and can generally be compiled for a large nb of platforms.
Ubuntu Xenial 16.04 even offers `zstd` directly as part of its package manager. Try `sudo apt-get install zstd`.

_edit_ : answered too fast, this is not about `zstd` ... 🤣

**Comment by easyaspi314** [comment]
\*looks at repo name\*

**Comment by felixhandte** [comment]
It looks like xxHash is not packaged for Ubuntu 16.04 ([source](https://repology.org/project/xxhash/versions)). However, it is definitely supported, in the sense that xxHash will compile and run on Ubuntu 16.04 just fine. You just need to (e.g.) clone this repo and integrate it into your project directly.

**Comment by harashimahashi** [comment]
Thanks, I think it gave me an answer to all the questions I had

**Comment by Cyan4973** [comment]
Ah, right, the joy of maintaining multiple repos in parallel....
Sounds like I confused that one in the rush 😆 

@felixhandte 's answer is correct.
