### ISSUE TITLE
Broken man page symlinks

### ISSUE THREAD

**Issue by jpalus** [Cyan4973/xxHash#647]
Installed man page symlinks `xxh32sum/xxh64sum/xxh128sum` are broken in xxHash 0.8.1:
https://github.com/Cyan4973/xxHash/blob/1607d988d9088246dc5be9642d85c8ab527ff23b/Makefile#L521-L523
where `MAN` is
https://github.com/Cyan4973/xxHash/blob/1607d988d9088246dc5be9642d85c8ab527ff23b/Makefile#L371
and `XXHSUM_SRC_DIR` is:
https://github.com/Cyan4973/xxHash/blob/1607d988d9088246dc5be9642d85c8ab527ff23b/Makefile#L74
hence in the end symlinks effectively point to `$(MANDIR)/cli/xxhsum.1` which does not exit

**Comment by Cyan4973** [comment]
Thanks for reporting the issue @jpalus,
this should be fixed in latest `dev` branch update.
