### ISSUE TITLE
Question: Message recovery attack

### ISSUE THREAD

**Issue by phantomcraft** [Cyan4973/xxHash#652]
Let's suppose I hash a message "xxxxxxxx" using xxhash64 generating a hash of 64-bits output.

Is it possible that a adversary only knowing the hash can recover the "xxxxxxxx" message with less than 2^64 tries?

**Comment by Cyan4973** [comment]
For the long answer, it depends on the length of the message, and on the presence or absence of some additional `seed` value.

For the short answer, `xxhash` makes no claim of cryptographic protection, and should not be relied upon for cryptographic needs.

**Comment by phantomcraft** [comment]
@Cyan4973 

Thanks.
