### ISSUE TITLE
Add Blake3 to the benchmark

### ISSUE THREAD

**Issue by MarcusJohnson91** [Cyan4973/xxHash#660]
It'd be nice to know how xxhash compares to Blake3, obviously with the same key size

**Comment by easyaspi314** [comment]
https://github.com/Cyan4973/xxHash/wiki/Performance-comparison
It gets about 2.4 GB/s, but Blake3 is a cryptographic hash and therefore is blazingly fast *in comparison to other cryptographic hashes*, even if it is terrible compared to non-cryptographic hashes which have much different expectations.
