### ISSUE TITLE
Probably a dumb question

### ISSUE THREAD

**Issue by dimkKy** [Cyan4973/xxHash#669]
Could not find by myself but how to generate a hash value from a buffer value?
For example:

int_fast32_t _one_ = 1;
int_fast32_t _two_ = 1;
How do I make that XXH32(_one_) equals XXH32(_two_)?

**Comment by Cyan4973** [comment]
```C
if (XXH32(&one, sizeof(one), seed) == XXH32(&two, sizeof(two), seed)) { ... }
```

**Comment by dimkKy** [comment]
Damn, I just forgot about sizeof() function. Thank you and sorry for wasting your time :)
