### ISSUE TITLE
Consider exposing `*.cmake` files from `Makefile` install targets.

### ISSUE THREAD

**Issue by trofi** [Cyan4973/xxHash#674]
In https://github.com/NixOS/nixpkgs/issues/155007 @foolnotion requested NixOS distribution to install `*.cmake` files by default. I guess helps easier development against `xxHash` for new cmake-based projects. I'm slightly worried that `xxHash`es `cmake` build system itself is considered unofficial by CI (https://github.com/Cyan4973/xxHash/blob/dev/.github/workflows/ci.yml#L247).

What do you think of installing file like

```
cmake/xxHash/xxHashConfig.cmake
cmake/xxHash/xxHashConfigVersion.cmake
cmake/xxHash/xxHashTargets.cmake
cmake/xxHash/xxHashTargets-release.cmake
```

from `Makefile`-based system as well?

That way users could rely a bit more on these files' presence regardless of what build system distributions use to package xxHash. 

Don't know feasible or maintainable it is. As one example `libSDL2` seems to generate `*.cmake` files from autoconf-based system as well: https://github.com/libsdl-org/SDL/blob/main/Makefile.in#L195-L198

**Comment by Cyan4973** [comment]
[edit]
If I understand correctly, some projects using `cmake` as their build system
may require their dependencies to also use `cmake`, or at least generate relevant `*.cmake` files
for the convenience of their integration process.
This effectively pressures all dependent projects to employ `cmake` too.

The proposed solution here is to cave in partially, by distributing the required `*.cmake` files from `Makefile`.
Of course, this requires understanding what these files are, how they are generated,
and find the relevant build system to generate them.
And ensure they remain valid over time, in case `cmake` changes a few details in the future.

And of course, I have no idea what these files are, let alone how to generate them.

As a sidenote, this `cmake` practice feels like a textbook monopolistic strategy.
Let's leverage a dominant position by adding requirements that only the dominant system naturally fulfills,
and then slowing strangling out all alternative build systems,
or at least make their life more difficult and uncertain.

**Comment by juan-lunarg** [comment]
> As a sidenote, this `cmake` practice feels like a textbook monopolistic strategy.
> Let's leverage a dominant position by adding requirements that only the dominant system naturally fulfills,
> and then slowing strangling out all alternative build systems,
> or at least make their life more difficult and uncertain.

FWIW the CMake developers themselves would love for there to be a standard cross platform standard for the information found in cmake config files - https://youtu.be/5X803cXe02Y?t=2761

pkg-config isn't widely used on all platforms and has issues/limitations.

Also it isn't just CMake that can read these config files. Meson can also read these config files https://mesonbuild.com/CMake-module.html

**Comment by juan-lunarg** [comment]
I believe this issue can be marked as resolved thanks to the added unofficial CMake support though. Since the original users closed their linked issue by using the `cmake_unofficial` after seeing that vcpkg uses the `cmake_unofficial`:

See relevant PR/issue:
- https://github.com/NixOS/nixpkgs/issues/155007
- https://github.com/NixOS/nixpkgs/pull/163279

**Comment by trofi** [comment]
> [edit] If I understand correctly, some projects using `cmake` as their build system may require their dependencies to also use `cmake`, or at least generate relevant `*.cmake` files for the convenience of their integration process. This effectively pressures all dependent projects to employ `cmake` too.
> 
> The proposed solution here is to cave in partially, by distributing the required `*.cmake` files from `Makefile`. Of course, this requires understanding what these files are, how they are generated, and find the relevant build system to generate them. And ensure they remain valid over time, in case `cmake` changes a few details in the future.
> 
> And of course, I have no idea what these files are, let alone how to generate them.
> 
> As a sidenote, this `cmake` practice feels like a textbook monopolistic strategy. Let's leverage a dominant position by adding requirements that only the dominant system naturally fulfills, and then slowing strangling out all alternative build systems, or at least make their life more difficult and uncertain.

I'll try to rephrase my request:

`xxHash` has two build systems: `Makefile`-based and `cmake`-based. These build systems install different file sets. Distribution needs to pick some build system: either `cmake`-based or `Makefile`-based. Given that `cmake`-based system installs more files it is natural to many distributions to use `cmake` for `xxHash`. `nixpkgs` uses `cmake`. People start relying on those `*.cmake` files that `xxHash` already provides. That means that distributions have a hard time to flip back to `Makefile`-based `xxHash` build: it will break users.

I'm not sure what you mean by caving in. I think `Makefile`-based and `cmake`-based build system should install identical set of files to be less confusing. Not installing `*.cmake` files in `cmake`-based build system would also make sense.

I hope it clarifies the report a bit.

Mechanical file comparison:

```
$ make 
$ make install DESTDIR=$PWD/__m__
$ find __m__
__m__
__m__/usr
__m__/usr/local
__m__/usr/local/lib
__m__/usr/local/lib/libxxhash.a
__m__/usr/local/lib/libxxhash.so.0.8.1
__m__/usr/local/lib/libxxhash.so.0
__m__/usr/local/lib/libxxhash.so
__m__/usr/local/lib/pkgconfig
__m__/usr/local/lib/pkgconfig/libxxhash.pc
__m__/usr/local/include
__m__/usr/local/include/xxhash.h
__m__/usr/local/include/xxh3.h
__m__/usr/local/bin
__m__/usr/local/bin/xxhsum
__m__/usr/local/bin/xxh32sum
__m__/usr/local/bin/xxh64sum
__m__/usr/local/bin/xxh128sum
__m__/usr/local/share
__m__/usr/local/share/man
__m__/usr/local/share/man/man1
__m__/usr/local/share/man/man1/xxhsum.1
__m__/usr/local/share/man/man1/xxh32sum.1
__m__/usr/local/share/man/man1/xxh64sum.1
__m__/usr/local/share/man/man1/xxh128sum.1
```

```
$ mkdir -p b && cmake cmake_unofficial -B b/
$ cd b
$ make
$ make install DESTDIR=$PWD/__i__
$ find __i__
__i__
__i__/var
__i__/var/empty
__i__/var/empty/local
__i__/var/empty/local/lib64
__i__/var/empty/local/lib64/libxxhash.so.0.8.1
__i__/var/empty/local/lib64/libxxhash.so.0
__i__/var/empty/local/lib64/libxxhash.so
__i__/var/empty/local/lib64/cmake
__i__/var/empty/local/lib64/cmake/xxHash
__i__/var/empty/local/lib64/cmake/xxHash/xxHashConfig.cmake
__i__/var/empty/local/lib64/cmake/xxHash/xxHashConfigVersion.cmake
__i__/var/empty/local/lib64/cmake/xxHash/xxHashTargets.cmake
__i__/var/empty/local/lib64/cmake/xxHash/xxHashTargets-release.cmake
__i__/var/empty/local/lib64/pkgconfig
__i__/var/empty/local/lib64/pkgconfig/libxxhash.pc
__i__/var/empty/local/include
__i__/var/empty/local/include/xxhash.h
__i__/var/empty/local/include/xxh3.h
__i__/var/empty/local/bin
__i__/var/empty/local/bin/xxhsum
__i__/var/empty/local/share
__i__/var/empty/local/share/man
__i__/var/empty/local/share/man/man1
__i__/var/empty/local/share/man/man1/xxhsum.1
```

Note the extra `*.cmake` files.

**Comment by Cyan4973** [comment]
I sincerely don't know.

As the maintainer of this repository, I was only concerned by the maintenance of the official `Makefile` build script.
The `cmake` one is additional, community maintained, and exists because there is a demand for it.

Along the road, one contributor believed it would be a good idea to add these cmake-specific files,
which is probably a correct statement, especially in the `cmake` world,
but now we have this situation of 2 build systems generating different set of files.

I'm not against generating these config files from `Makefile`,
after all we already produce `pkgconfig` files,
but how easy / feasible is it, that's the part I don't know.
Furthermore, will that feature increase the dependency surface of the build system ?
If yes, that can become a serious blocking problem.
If no, then maybe we can actually get it done.
