### ISSUE TITLE
Update xxhash_spec.md with the details for XXH3 ?

### ISSUE THREAD

**Issue by palladium-coder** [Cyan4973/xxHash#675]
Hello,

Can xxhash_spec.md doc be updated to include the details of XXH3 algorithm . It will help the folks who are implementing it from scratch.

**Comment by Cyan4973** [comment]
Note : this is a `v1.0` release topic.

Also : partially redundant with #589.

**Comment by t-mat** [comment]
Since #589 has been closed, we can also close this issue via #750.  @Cyan4973
