### ISSUE TITLE
Question: Are XXH3_64bits and XXH3_128bits designed for 64-bit platforms?

### ISSUE THREAD

**Issue by phantomcraft** [Cyan4973/xxHash#677]
I'm planning to write a program in the future which will use XXH, but I would like to maintain compatibility with 32-bit systems.

My question is:

Are XXH3_64bits and XXH3_128bits designed for 64-bit systems?

I'm asking this because XXH64 is two times faster than XXH32.

**Comment by Cyan4973** [comment]
Yes, these hashes are "designed for" 64-bit systems
(unlike `XXH32` which is "designed for" 32-bit systems),

but they are not limited to either side.
The code is highly portable, and will work on any system, including good old 16-bit `m68k` for example. And produce same (directly comparable) results.

Now, when it comes to "designed for", it merely means that the code will tend to provide better performance on expected system. `XXH64` for example is 2x faster than `XXH32` on 64-bit systems. But it's 2x slower than `XXH32` on 32-bit systems. It still works, it's just less efficient for these platforms.

`XXH3` is also designed for 64-bit platforms, and takes advantage of (but does not require) vector instructions.
Another advantage is that it takes a lower performance hit (than `XXH64`) when running on 32-bit platforms.

**Comment by phantomcraft** [comment]
I got.

Thanks.

**Comment by UnlimitedChild** [comment]
Hello,

XXH32 api does not appear in the set if I use define 

#define XXH_INLINE_ALL
#define INCLUDE_XXHASH

How can I call these functions?! This question is a little related to this topic, so I decided to ask it here. Thanks!

**Comment by Cyan4973** [comment]
What does `#define INCLUDE_XXHASH` do ? (or is supposed to do ?)

**Comment by UnlimitedChild** [comment]
> #define INCLUDE_XXHASH

It's just the result of experimentation, on a clean version of the library, with this define #define XXH_INLINE_ALL, the following functions are available
![xxh_x86dispatch obj](https://user-images.githubusercontent.com/16466330/150884630-388d867a-3295-4215-be26-f9b5bee37358.jpg)

XXH32 is not available ..

**Comment by Cyan4973** [comment]
`#define XXH_INLINE_ALL` exists, and has a defined role,
while `#define INCLUDE_XXHASH` doesn't exist, and should not have any impact.

If you mean `#include "xxhash.h"`, that's a fairly different statement.

In this last case, `XXH32` symbols are supposed to be present.

One example where this happens is in `tests/bench/hashes.h`,
and it's used to link `XXH32()`.
If `XXH32()` wasn't present, the link stage would fail.

**Comment by UnlimitedChild** [comment]
Hello Cyan4973, 

I have a static library, there is no sign of this function, I searched in object files, without this define "#define XXH_INLINE_ALL" the function is available:
![xxhash](https://user-images.githubusercontent.com/16466330/150940809-a6b1a9e7-09f8-47f7-a155-c5b9970ce8d3.jpg)

Thanks!
