### ISSUE TITLE
MSVCRT Debloating

### ISSUE THREAD

**Issue by UnlimitedChild** [Cyan4973/xxHash#678]
Hello,

the project depends too much on runtime functions, the project cannot be used in a kernel mod or embedded hardware. The size of the library increases by almost 4 times, some functions cause a lot of unnecessary subfunctions. For example _free, _malloc, __allmul, _aullshr, _memcpy, _memset includes many other runtime functions. 

The best solution would be to update the library so that it is fully portable on any system. 

Regards,
UC

**Comment by Cyan4973** [comment]
Try [`XXH_NO_STDLIB`](https://github.com/Cyan4973/xxHash#build-modifiers)

**Comment by UnlimitedChild** [comment]
Hi Cyan4973,

thanks for the quick response!

This option did not work for me, since the define was written after the file was included. My library still has many crt functions, the problem is not in the xxHash library, it is the problem of building a dynamic library. 

In any case, the code contains __allmul, _aullshr, _memcpy, _memset, 
[memcpy_memset.zip](https://github.com/Cyan4973/xxHash/files/7920694/memcpy_memset.zip)

If you do not use your own implementations, then extra functions are added to the code. 

Thanks for the great library, this question is closed.
