### ISSUE TITLE
Option to output just the hash

### ISSUE THREAD

**Issue by mrbluecoat** [Cyan4973/xxHash#679]
Is there a way to output just the hash alone, without the filename? I know this can be done in combination with awk or cut, but curious if it could be baked into the binary for consistency. Here's my current workaround with awk (using `uuidgen` as an example input):

`uuidgen | xxhsum -H3 --tag | awk -F' = ' '{print $2}'`

**Comment by Cyan4973** [comment]
Consistency would be for `xxhsum` to replicate the experience offered by `md5sum`.
Is there a way for `md5sum` to output only the hash value ?
Otherwise, `awk` looks like the correct solution to me.

**Comment by mrbluecoat** [comment]
I guess by 'consistency' I meant reliable xxhsum output format in future versions but `--tag` is reliable enough for me. Hashing a piped string is probably an edge case so I'll close. Thanks for a great tool!
