### ISSUE TITLE
Add 256bit variant

### ISSUE THREAD

**Issue by That3Percent** [Cyan4973/xxHash#680]
The [blog post introducing XXH3](https://fastcompression.blogspot.com/2019/03/presenting-xxh3.html) mentions that a 256 bit variant is possible.

I have a use-case for a 256 bit variant in a set hash which uses the resulting hashes in an accumulator which would benefit from the larger state space in the accumulator.

**Comment by Cyan4973** [comment]
Indeed, a 256-bit variant of `XXH3` is technically possible,
but unfortunately, this is a pretty big undertaking, 
and I don't have the bandwidth to make it happen on short term.

Also, note that many use cases I know of needing a set of 256-bit
have been doing fine to my knowledge with `XXH128()`.

The trick is to-rehash the 128-bit result to get a second 128-bit set.
While technically the variance is still only 128-bit,
in practice, the produced randomness is largely good enough for all use cases I know of 
(you would need a problem scale in the 2^60 range to _start_ feeling the side effects).

If all you need is a random-looking reproducible bitfield totalling 256 bits, to be distributed across multiple variables or parameters (the classical example being a bloom filter), give it a try. Assuming no field ever get close to 60 bit, this is going to provide a distribution performance undistinguishable from "true" 256-bit variance.
(You could run a statistics comparison test with a "true" 256-bit hash or cypher algorithm to control this statement).

**Comment by Cyan4973** [comment]
While a 256-bit variant is theoretically possible based on `XXH3` mixing strategy,
it's a lot of work, and I don't see this outcome happening any time soon.
Closing for now.
