### ISSUE TITLE
XXH64 produces 32bit hash in MIPS arch in C

### ISSUE THREAD

**Issue by LoloBee** [Cyan4973/xxHash#686]
As the title describes, I'm getting a 32bit hash when using XXH64 function in 32bit MIPS arch. The same code, in x64 produces 64bit hashes.

Here's my C code:

```
#include "libs/xxh3.h"

XXH64_state_t* hashState = NULL;
/* Initialize state with selected seed */
XXH64_hash_t const seed = 0;   /* or any other value */

hashState = XXH64_createState();
  if (hashState==NULL) {
      ieHashError = 0;
  //hashState is reset because it's reused in a while loop
  if (XXH64_reset(hashState, seed) == XXH_ERROR) {
      ieHashError = 0;
  }

XXH64_hash_t hash = XXH64(rawString, rawStringLen, seed);
printf("Hash: %lX\r\n", hash);
```
This is the result in MIPS running OpenWRT
```
Hash: 23546B61
Hash: 61C94666
Hash: DE07728C
Hash: 84843E3F
Hash: 5DBAB46D
```
And this is in intel x64 running ubuntu:
```
Hash: EF46DB3751D8E999
Hash: E05A8D9DC30EE6FC
Hash: D0C12D47B1086B21
Hash: FFAB96637F0DB60A
```

Please, note that the hashed strings are note the same.

Is this the expected behaviour? 
Can't I produce 64Bit hashes in order to lower down collisions? In this [closed issue](https://github.com/Cyan4973/xxHash/issues/677#issuecomment-1016841665) the author points that the only problem when using the library in x32 is that it will work slower, not producing different hashes.

Is there something I am missing?

Thank you.

**Comment by t-mat** [comment]
> Is this the expected behaviour?

~Yes.~
Oops.  No.

(1) As for many standard libraries for 32-bits architectures, `%lx` != `%llx`.
(2) If `%lx` shows 32bits value and `%llx` displays 64bits value, `%lx` must display lower or higher part of 64-bit hash value.   It may disaply higher 32-bit in big endian systems, lower 32-bit in little endian systems.  It seems strange.
(3) I don't understand why the number of hash values are difference for same strings.  (5 vs 4)

> Is there something I am missing?

Please use `XXH64_canonical_t`.
https://github.com/Cyan4973/xxHash/blob/d8aff149b5b9b9461f4b01fc5ab4842112d2c867/xxhash.h#L835-L836

**Comment by Cyan4973** [comment]
Indeed, the issue is the `%lX` display statement in your sample code.

**Comment by LoloBee** [comment]
Shame on me...

Still much to learn.

Thank you!
