### ISSUE TITLE
Problem with projects that use lizard, lz4 and xxhash at the same time.

### ISSUE THREAD

**Issue by pps83** [Cyan4973/xxHash#687]
lizard and lz4 both include a copy of xxhash.c/xxhash.h. That copy is usually outdated.
The problem happens if a project also needs to use xxhash separately: suddenly you get multiply defined symbols. Can this be addressed in xxHash and lz4/lizard updated with latest version of xxHash?

**Comment by Cyan4973** [comment]
`XXH_NAMESPACE` can be used to mitigate naming collisions.

`liblz4` already uses it, but if you skip library creation for direct integration of source file level, such setting is lost.

On the other hand, if you integrate source files directly, you can also remove duplicated `xxhash` file.

**Comment by pps83** [comment]
I placed latest xxhash.h into lz4 (removed xxhash.c) and then replaced `#define XXH_STATIC_LINKING_ONLY` with `XXH_INLINE_ALL` inside lz4\lib\lz4frame.c. This seems to avoid all possible collisions.

**Comment by pps83** [comment]
I can do a PR if you think that's an acceptable approach.
Sample PR: https://github.com/pps83/lz4/commit/a226d7ee7455da8e564e14b8163040008365b25c
