### ISSUE TITLE
How to copy a state?

### ISSUE THREAD

**Issue by ifduyue** [Cyan4973/xxHash#69]
Hello,

Since ``XXH32_state_t`` and ``XXH64_state_t`` are incomplete types, memcpy doesn't work.
How about providing ``XXH*_copyState``?

**Comment by Cyan4973** [comment]
Yes, that's a very good point.

`XXHnn_state_t ` are POD types, so they could be `memcpy()`. 
But to access their definition, it's necessary to set 
`XXH_STATIC_LINKING_ONLY` macro, which is incompatible with dynamic linking.
So there is a functionality gap for such use case.

I'll add this feature in the next release.

**Comment by Cyan4973** [comment]
I guess these candidate prototypes are self-explaining ?

```
void XXH_copyState32(XXH32_state_t* dstState, const XXH32_state_t* srcState);
void XXH_copyState64(XXH64_state_t* dstState, const XXH64_state_t* srcState);
```

**Comment by ifduyue** [comment]
> I guess these candidate prototypes are self-explaining ?
> 
> void XXH_copyState32(XXH32_state_t* dstState, const XXH32_state_t* srcState);
> void XXH_copyState64(XXH64_state_t* dstState, const XXH64_state_t* srcState);

Looks good to me.

**Comment by petervaro** [comment]
if I may, it should be something like this:

```
#if (!__STDC__ || __STDC_VERSION__ < 199901L)
    #define restrict
#endif

void
XXH32_state_copy(XXH32_state_t       *restrict dst_state,
                 const XXH32_state_t *restrict src_state);

void
XXH64_state_copy(XXH64_state_t       *restrict dst_state,
                 const XXH64_state_t *restrict src_state);
```

**Comment by ifduyue** [comment]
@petervaro +1 for restrict.

However, IMHO, ``XXHnn_copyState`` is more consistent compared to ``XXHnn_state_copy``. There already are  ``XXHnn_createState`` and ``XXHnn_freeState``. https://github.com/Cyan4973/xxHash/blob/20d943930190f92f493f3ec196d8d495575c0c15/xxhash.h#L179-L183

**Comment by Cyan4973** [comment]
Correct,
naming style is always [prefix][verb][object].
So `XXH*_copyState()`

**Comment by petervaro** [comment]
@ifduyue sure, if that is the naming convention, it is too late now to fix it :P IMHO it should be PREFIX_[MODULE_]CLASS_[SUBTYPE_]METHOD, as you would do in higher level languages, but I don't think this thread is about discussing this *religion*-based views.

*Truth to be told: `_t` prefix should never be used in the first place, as it is reserved by the POSIX standard, which strictly forbids its use.. so that's why I said, it is already too late* :P

**Comment by Cyan4973** [comment]
"dev" branch has been updated with the proposed new API.
Should become part of v0.6.1

**Comment by Cyan4973** [comment]
pushed to master
