### ISSUE TITLE
[info] i ported this library to arduino

### ISSUE THREAD

**Issue by atesin** [Cyan4973/xxHash#700]
hi... thanks for this excelent hash...  these are the links for my arduino port (attempt :)

- https://www.arduino.cc/reference/en/libraries/xxhash_arduino/
- https://gitlab.com/atesin/XxHash_arduino

in first instance i tried to port it using Daniel Kirchner's [C++ constexpr library](https://github.com/ekpyron/xxhashct), it worked but he suggest me to better use the original `xxhash.h` file from this project and gave me some advices on how to do it, it worked better.... this is the [same message](https://github.com/ekpyron/xxhashct/issues/3) i sent him that i think also applies to you...

----
i was looking for a light and fast hash function for arduino, also present in php to make interact them
- i checked crc16 (native in avr-libc) but it is not so 'entropic'
- i know there are md5, sha1 and other hash libs for arduino but they are huuuge
- another candidate i saw were djb2 hash, but until simpler is slow and has no native php support
- others i saw were Paul Hsieh's SuperFastHash and Eric Ztamnl Fast-Hash, but have larger code and no port to other langs

until maybe not perfect i think this lib is the best option we have (short code, efficient, ported), i think this libs would be very useful for all arduino projects, i hope you don't mind if i (try to) port this lib to arduino

**Comment by Cyan4973** [comment]
Nice work @atesin !
