### ISSUE TITLE
C++-friendly namespace macros

### ISSUE THREAD

**Issue by iboB** [Cyan4973/xxHash#705]
I want to use xxHash in C++ and wrap it in several minimalistic classes to do incremental hashes. Since I want to avoid allocations I would like them to have `XXH_state_t` as a by-value member. Without C++20 modules though, including the header files for my C++ classes will cause the xxHash public interface to "leak" into the global namespace. 

Now the library does provide C-style namespacing where a used-provided prefix can be concatenated with the public interface symbols, but for C++ if would be much nicer if it also provided a C++ namespace configuration option.

Something like this:

```c++
#if defined (__cplusplus) && defined (XXH_CPP_NAMESPACE)
namespace XXH_CPP_NAMESPACE {
#endif
// ...
// ...
#if defined (__cplusplus) && defined (XXH_CPP_NAMESPACE)
} // namespace XXH_CPP_NAMESPACE
#endif
```

What do you think?

**Comment by iboB** [comment]
... alternatively a configuration option do skip all includes can be added. Thus one can include `xxhash.h` within a namespace:

```c++
namespace xxhash {
#include "xxhash.h"
}
```

... though this does seem more error prone than the first option

**Comment by Cyan4973** [comment]
`xxhash` exposes public symbols using C naming convention thanks to this statement  :
```
#if defined (__cplusplus)
extern "C" {
#endif
```

To answer your request, would it be enough to replace it with something like : 
```
#if defined (__cplusplus) && defined (XXH_CPP_NAMESPACE)
namespace XXH_CPP_NAMESPACE {
#endif
```

I presume this could be tested in your target environment.
I would expect a certain amount of additional adjustments required, such as "don't `#include` within the `namespace`" for example.
Unfortunately, I don't have some similar enough use case available to check and adjust.

**Comment by iboB** [comment]
Since you seem to be open to the idea I can submit a PR

**Comment by Cyan4973** [comment]
It seems that the solution proposed (#706) was different from the problem enounced in this issue. Since there is no other request in the same direction, closing for now.
