### ISSUE TITLE
MSVC different parameters warning

### ISSUE THREAD

**Issue by Photosounder** [Cyan4973/xxHash#716]
I just updated my copy of `xxhash.h` to the latest and when compiling in MSVC I get this warning:

`xxhash.h(5054,116): warning C4113: 'XXH64_hash_t (__cdecl *)(const void *,size_t,XXH64_hash_t,const xxh_u8 *,size_t)' differs in parameter lists from 'XXH3_hashLong64_f'`

I couldn't figure out what the inconsistency is, but this should definitely be looked into. GCC and Clang give me no warnings.

**Comment by Cyan4973** [comment]
> I just updated my copy of xxhash.h to the latest 

Could you define  `latest` ?
- Latest `dev` branch update
- Latest `release` `v0.8.1` ?

**Comment by Photosounder** [comment]
`dev` branch

**Comment by Cyan4973** [comment]
I just tried a blindfix, that may fix your case.
Could you update your local `dev` branch and try again ?

**Comment by Photosounder** [comment]
I confirm that this solves the problem.
