### ISSUE TITLE
XXH_FALLTHROUGH macros generates warning with ICC compilation

### ISSUE THREAD

**Issue by rohanaggarwal7997** [Cyan4973/xxHash#717]
Compiling with ICC, leads to evaluation of XXH_FALLTHROUGH as empty string and we get the following warning message 

xxhash.h(2344): warning #169: expected a declaration
             case 11:      XXH_PROCESS4; XXH_FALLTHROUGH

**Comment by Cyan4973** [comment]
I presume that `XXH_FALLTHROUGH` definition reaches this line :  
https://github.com/Cyan4973/xxHash/blame/dev/xxhash.h#L743

It's questionable if this macro definition does anything. I wouldn't expect it to transport the comment statement at the target place.

What does ICC require for explicit fall-through ?
And also, which version of ICC are you using ?

**Comment by Cyan4973** [comment]
Could you try to patch in #718 ?
It might help for `icc`, at least temporarily.
