### ISSUE TITLE
build statically linked executable support

### ISSUE THREAD

**Issue by leleliu008** [Cyan4973/xxHash#732]
can't pass `-static` option to `LDFLAGS` to build statically linked executable. because `-shared` and `-static` don't work together.

advise:
 `LDFLAGS` for the creation of shared libraries and executables.
 `LDFLAGS_LIB`   for the creation of shared libraries only.
 `LDFLAGS_EXE` for the creation of executables only.

**Comment by Cyan4973** [comment]
What about : `LDFLAGS=-static make xxhsum` ?

**Comment by leleliu008** [comment]
it works. Thanks.
