### ISSUE TITLE
Hash fails between NTFS and ext4

### ISSUE THREAD

**Issue by Jolly-Pirate** [Cyan4973/xxHash#735]
Using a bunch of zip files for testing.
Created checksums of the zips on Ubuntu 22.04 (ext4), using `xxh128sum`.
Copied the files to Windows 10 (NTFS) via Samba share.
**Most** of the checksums fail on the target machine, however the zips integrities are all OK when tested with Winrar.
The same happens in the opposite direction: checkum on Windows and test them on Linux.

When doing the same procedures with the popular `sha256sum`, all the zips checksums are OK on the both machines.

It appears the hashing is different on Linux vs Windows.

**Comment by Cyan4973** [comment]
How are you computing `xxh128sum` ?
Using the CLI ? Or linking to `libxxhash` ?
Which versions were used ?

**Comment by Jolly-Pirate** [comment]
Sorry I didn't mention it, I'm using cli, installed with `apt install xxhash`.
On the Linux machine it's Ubuntu 22.04.
```
$ xxh128sum -V    
xxh128sum 0.8.1 by Yann Collet 
compiled as 64-bit x86_64 autoVec little endian with GCC 11.2.0
```

And on Windows 10 using Ubuntu 20.04 WSL version 1 (WSL2 was extremely too slow to do any computations by the way).
```
$ xxh128sum -V
xxh128sum 0.7.3 (64-bit x86_64 + SSE2 little endian), GCC 9.3.0, by Yann Collet
```

**Comment by Cyan4973** [comment]
`XXH128` has been officially finalized starting `v0.8.0` only.
All previous `v0.7.x` versions are labelled "development versions", and therefore their resulting hash values can vary from version to version.

Retrospectively, allowing `xxh128sum` symlink before `v0.8.0` was a mistake, since it now generates this confusion.

**Comment by Jolly-Pirate** [comment]
Ah I didn't realize it was a symlink to `xxhsum`. Can I still use `xxh128sum` or do you recommend `xxhsum` instead?
I will install the latest version on WSL1 and see if it reproduces the bug.

**Comment by Jolly-Pirate** [comment]
You were right, the 0.7.x version was buggy. I redid my initial testing with the zips, 30% of the checksums failed. So, I uninstalled v0.7.3 from WSL (`apt remove xxhash`), then compiled the latest v0.8.1 from the source. Finally, all the hashes pass at 100%. And indeed, the checksums (done on the same machine) are different for many files, when comparing v0.7.3 and v0.8.1.
