### ISSUE TITLE
XXH3_accumulate_512_neon processing 1024byte blocks?

### ISSUE THREAD

**Issue by Over17** [Cyan4973/xxHash#741]
Hi! I'm working on porting the Neon version to a Unity Burst-compiled C# version, and one thing keep puzzling me in the Neon implementation.

`XXH3_accumulate_512_neon`, which is an equivalent to all other 512bit processing functions, is actually processing XXH_ACC_NB (=8) rounds of 128bits ( `uint64x2_t` ), so it's 1024bits. Maybe I'm completely misunderstanding something, can someone please explain then.

Somewhat unrelated: I ran a local benchmark of scalar vs. Neon version on my Galaxy S22 (Cortex-X2 and A710), and the results are not assuring - scalar version is at least as fast as the Neon one. The benchmark in this repo seems to produce quite unstable results when run as an ELF application on Android, so wondering if anyone has a performance testing strategy on Android.

**Comment by Over17** [comment]
Comments at line 4477

```
            /* data_key_lo = {(data_key1 & 0xFFFFFFFF), (data_key2 & 0xFFFFFFFF)};
             * data_key_hi = {(data_key1 >> 32), (data_key2 >> 32)};
             */
            uint32x4x2_t zipped = vuzpq_u32(vreinterpretq_u32_u64(data_key1), vreinterpretq_u32_u64(data_key2));
```

Also suggest the code was once written for 64-bit vectors, but then upgraded to full 128-bit.

**Comment by Cyan4973** [comment]
Not being the author of the `NEON` variant, I'm not in great position to provide useful advises.

However, I can say that this variant is tested, like all others, using a test vector, and generates the expected hash values.

I could also test `XXH3` on a Galaxy S22 and confirm that `NEON` and `SCALAR` are roughly equivalent, though in my case, `SCALAR` was slightly slower.

**Comment by easyaspi314** [comment]
> Somewhat unrelated: I ran a local benchmark of scalar vs. Neon version on my Galaxy S22 (Cortex-X2 and A710), and the results are not assuring - scalar version is at least as fast as the Neon one.

Scalar and NEON performance depend heavily on not only the device but the individual cores (due to how big.LITTLE works), and there is unfortunately no correct answer. It isn't consistent like x86 (avx512 > avx2 > sse2 > scalar, 100% of the time), especially because there are multiple manufacturers.

It roughly seems to be:
 - Older/lower end out-of-order cortexes (a.k.a. raspi4 and your run-of-the-mill Android device) prefer a hybrid scalar and neon path because of the limited dispatching bandwidth and multiplication latency (although the new double width improves it)
 - In-order cortexes don't care.
 - Apple M1 prefers pure NEON, not sure about the mobile line
 - Older server-class chips prefer scalar
 - Newer cortexes are a tossup (as you observed)
 - Codegen for scalar multiplies is kinda shady due to clang not realizing that `and+madd` is slower than `umaddl`, and that there is an errata that causes a bad result when a store follows a 64-bit multiply on the A53 requiring a workaround.

> The benchmark in this repo seems to produce quite unstable results when run as an ELF application on Android, so wondering if anyone has a performance testing strategy on Android.

Performance testing is really difficult due to how Linux's schedulers work. It tries to balance the load across cores to prevent one core from overheating, but the cores are asymmetrical. It is basically a lottery whether you get a performance, balanced, or efficiency core.

> Comments at line 4477
> ```c
>             /* data_key_lo = {(data_key1 & 0xFFFFFFFF), (data_key2 & 0xFFFFFFFF)};
>              * data_key_hi = {(data_key1 >> 32), (data_key2 >> 32)};
>              */
>             uint32x4x2_t zipped = vuzpq_u32(vreinterpretq_u32_u64(data_key1), vreinterpretq_u32_u64(data_key2));
> ```
> Also suggest the code was once written for 64-bit vectors, but then upgraded to full 128-bit.

That is correct, the comments should be updated because there is a lot of confusing shuffling going on.

**Comment by Over17** [comment]
Thank you @Cyan4973 and @easyaspi314 .

> Codegen for scalar multiplies is kinda shady due to clang not realizing that `and+madd` is slower than `umaddl`

I'm not an expert in C++ standards, but I think the compiler cannot deduce that

```
xxh_u64
XXH_mult32to64(xxh_u64 x, xxh_u64 y)
{
   return (x & 0xFFFFFFFF) * (y & 0xFFFFFFFF);
}
```

multiplies unsigned ints. If you think this is a clang bug, I'm happy to report it to the compiler team at Arm.


> Performance testing is really difficult due to how Linux's schedulers work. It tries to balance the load across cores to prevent one core from overheating, but the cores are asymmetrical. It is basically a lottery whether you get a performance, balanced, or efficiency core.

Thank you for the explanation. I'm aware of how complicated it could be to correctly measure performance on mobiles. Some of the solutions could be
- hardcode, at your own risk: use a rooted device, fix the core frequencies, use controlled environment (temperature), set thread affinity to the core that you're interested in
- softcore: cool down the device before running benchmark (idling for 5 minutes), make sure the duration of the benchmark is short enough to not make the scheduler/governor clock down the core or migrate the thread, set thread affinity for a more stable result.

I totally realize all of the above are platform-dependent suggestions that may be hard to implement in a cross-platform library/product. Would love to hear though how do you get a single number result to understand if it's an improvement or a regression.

I was a bit surprised that the benchmark in this repo runs for quite some time, because all the issues you mentioned definitely kick in - throttling, thread migration on the big-little-huge cluster, scheduling and interference with the system processes, environment. My own benchmark was running for a second and produces quite stable results, but it's also as simple as a single long hash calculation.

=============================================
I do realize the results produced by Neon path are correct so there must be no algorithm error, but still the question remains - is `XXH3_accumulate_512_neon` actually processing 1024bits? is it intended?

**Comment by easyaspi314** [comment]
> Thank you @Cyan4973 and @easyaspi314 .
> 
> > Codegen for scalar multiplies is kinda shady due to clang not realizing that `and+madd` is slower than `umaddl`
> 
> I'm not an expert in C++ standards, but I think the compiler cannot deduce that
> 
> ```c
> xxh_u64
> XXH_mult32to64(xxh_u64 x, xxh_u64 y)
> {
>    return (x & 0xFFFFFFFF) * (y & 0xFFFFFFFF);
> }
> ```
> 
> multiplies unsigned ints. If you think this is a clang bug, I'm happy to report it to the compiler team at Arm.

Nope, it recognizes that pattern.

I could be wrong but I think that clang sees umaddl as
```c
u64 umaddl(u32 x, u32 y, u64 acc)
{
    return (u64)x * (u64)y + acc;
}
```
instead of
```c
u64 umaddl(u64 x, u64 y, u64 acc)
{
    return (x & 0xFFFFFFFF) * (y & 0xFFFFFFFF) + acc;
}
```
and therefore can't merge the mask.

Additionally, clang will always try to avoid downcasting. 

> > Performance testing is really difficult due to how Linux's schedulers work. It tries to balance the load across cores to prevent one core from overheating, but the cores are asymmetrical. It is basically a lottery whether you get a performance, balanced, or efficiency core.
> 
> Thank you for the explanation. I'm aware of how complicated it could be to correctly measure performance on mobiles. Some of the solutions could be
> - hardcode, at your own risk: use a rooted device, fix the core frequencies, use controlled environment (temperature), set thread affinity to the core that you're interested in
> - softcore: cool down the device before running benchmark (idling for 5 minutes), make sure the duration of the benchmark is short enough to not make the scheduler/governor clock down the core or migrate the thread, set thread affinity for a more stable result.

The best way is to increase the iterations. It takes a lot to heat up an ARM core (well, most of them), and the benchmark takes the best result.

> I totally realize all of the above are platform-dependent suggestions that may be hard to implement in a cross-platform library/product. Would love to hear though how do you get a single number result to understand if it's an improvement or a regression.

There really isn't. The hybrid NEON/scalar code is 

> I was a bit surprised that the benchmark in this repo runs for quite some time, because all the issues you mentioned definitely kick in - throttling, thread migration on the big-little-huge cluster, scheduling and interference with the system processes, environment. My own benchmark was running for a second and produces quite stable results, but it's also as simple as a single long hash calculation.

It runs multiple iterations because 
1. Many schedulers avoid higher frequencies unless there is a long term load
2. The big.LITTLE issue as stated before
3. It warms up the cache so the benchmark is about the cache instead of RAM speed
 =============================================
> I do realize the results produced by Neon path are correct so there must be no algorithm error, but still the question remains - is `XXH3_accumulate_512_neon` actually processing 1024bits? is it intended?

It isn't processing 1024 bits. It processes two lanes at a time for half the iterations. The math is a little confusing because of the overflow loop.

**Comment by Over17** [comment]
> It takes a lot to heat up an ARM core (well, most of them)
> Many schedulers avoid higher frequencies unless there is a long term load
> The big.LITTLE issue as stated before

I'm talking of mobile phones and Android in particular, but the above is far from being correct. Yes the app is likely to start on a little core running on low frequencies. However, once the scheduler and the governor sees high load, it will migrate the thread to a big core and clock it up to the max within **few milliseconds**. Then, within a range of seconds, the core is likely to overheat, which will cause throttling and possible thread migration to another core. During this timeframe of seconds, the performance results have high chance to be consistent. Other measurements can not be trusted, or at least should be taken with a grain of salt; any change under 10% is likely to be a noise.

> It isn't processing 1024 bits. It processes two lanes at a time for half the iterations. The math is a little confusing because of the overflow loop.

Yeah right looking thoroughly once again it looks like I was wrong initially. Thank you for clarifying!

> Older/lower end out-of-order cortexes (a.k.a. raspi4 and your run-of-the-mill Android device) prefer a hybrid scalar and neon path because of the limited dispatching bandwidth and multiplication latency (although the new double width improves it)

Just ran my benchmark (a single long string hash calculation) on a Galaxy S8, running on big cores, which are a rough equivalent of Cortex A73. Neon version is faster than the scalar one by 1%. I'm a bit surprised; the codebase seems to be optimized to use different CPU pipelines at the same time, has manually unrolled loops, per-cycle latency calculations, but the overall improvement is that minor? It's a rhetorical question; maybe my calculations are completely incorrect; hence I asked for advice re: robust benchmarking methodology.

Feel free to close the issue, and thanks for the answers!
