### ISSUE TITLE
The Ubuntu 18.04 GitHub Actions runner image is being deprecated

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Cyan4973/xxHash#743]
[GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)

> The Ubuntu 18.04 Actions runner image [started our deprecation process](https://github.com/actions/runner-images/issues/6002) on 8/8/22 and will be fully unsupported by 12/1/22. To raise awareness of the upcoming removal, jobs using Ubuntu 18.04 will temporarily fail during scheduled time periods defined below:
> [...]
> 
> **What you need to do**
> 
> Workflows using the `ubuntu-18.04` YAML workflow label should be updated to `ubuntu-20.04`, `ubuntu-22.04`, or `ubuntu-latest`. You can always get up-to-date information on our tools by reading about the [software](https://github.com/actions/virtual-environments) in GitHub Actions virtual environments.

This will break CI support for older compilers:
https://github.com/Cyan4973/xxHash/blob/43ea6fdf838782688716f6ad85792a39e7e38e9a/.github/workflows/ci.yml#L81-L83
https://github.com/Cyan4973/xxHash/blob/43ea6fdf838782688716f6ad85792a39e7e38e9a/.github/workflows/ci.yml#L94-L96

**Comment by Cyan4973** [comment]
On this topic, see this follow up :
https://github.com/actions/runner-images/issues/6002#issuecomment-1235119350
