### ISSUE TITLE
Collision ratio comparison

### ISSUE THREAD

**Issue by tansy** [Cyan4973/xxHash#753]
I have few questions to your [Collision ratio comparison](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison) which I found interesting and useful.

How do you calculate expected number of collisions, which in table 1 is given as 312.5? I understand that number of hashes (Nb Hashes = 100Gi) will increase the chance of collision; width of hash (number of hash bits: 32/64/128...) will decrease it but where this number come from?

Reason I'm asking is I have reorganized the other hash (here: wyhash) to make it "streamable" and, hopefully, having better avalanche and wanted to test it for collisions, which in your test are 4 times higher than "expected". And that expected is the clue. How can one calculate it?
Anyway, there is no way I can get 800GB of ram to perform the test with 100G of hashes but I can do some smaller test/s and assess whether I'm going in the right direction. But I need to calculate that expected value for different numbers. If I wanted to use 10G of hashes would it be 31.25?

**Comment by adrien1018** [comment]
Assuming N p-bit hashes, there are N(N-1)/2 pairs of hashes, and the probability of each pair having the same hash value is 1/2^p. Thus, the expected number of colliding pairs is N(N-1)/(2*2^p).
It is roughly proportional to N^2, so the expected value would be ~3.125 if you use 10Gi of hashes.

**Comment by Cyan4973** [comment]
@adrien1018 is right : https://github.com/Cyan4973/xxHash/blob/dev/tests/collisions/main.c#L533

If you use the [collision tester](https://github.com/Cyan4973/xxHash/tree/dev/tests/collisions), it will tell you how many collisions it expects for a given quantity of hashes and a given hash width,
which is indeed about 3 for 10G 64-bit hashes.

Unfortunately, for a low nb of hashes, a difference of 1 single collision can be a lot. 
Hence, to mitigate the impact of this random rounding effect, I would consider 25G to be a reasonable quantity.

That's indeed a lot of memory to store the hashes.
If you can't afford that amount, there is a `--filter` mode which reduces the amount of memory needed by a factor ~4, though it's also sensibly slower.

**Comment by tansy** [comment]
Thanks for the answers.

How that number of hashes apply to 32-bit hash? For the hash that has possible 4Gi of possible values 10Gi/25Gi seems redundant.

I tried low 32-bit of my version of 64-bit hash, wyhash32, xxhash32, and with CRC32/C and with 1Gi and they mostly give x0.96 of expected number of (128Mi) collisions with the exception of CRC32C that gave x1.83.

**Comment by Cyan4973** [comment]
There is no need for the massive collision tester in order to evaluate a 32-bit hash.
A few million of hashes is good enough to determine if the nb of produced hashes respect the birthday paradox.
All tests in the SMHasher test suite are suitable for 32-bit width.
The massive collision test becomes useful when trying to probe the collision rate for 64-bit hashes, in which case billions of hashes become necessary.
