### ISSUE TITLE
hash of vector

### ISSUE THREAD

**Issue by hros** [Cyan4973/xxHash#755]
what is the proper way to hash a vector, e.g. vector<int>?
consider the following code:
```c++
#include "xxhash.h"
#include <iostream>
#include <vector>

int main(int, char **) {
  std::vector<int> v;
  v.push_back(1);
  int a[] = {1};
  int d = 1;
  auto h = XXH32(v.data(), v.size(), 0);
  std::cout << "hash(v) = " << h << std::endl;
  h = XXH32(&d, sizeof(d), 0);
  std::cout << "hash(d) = " << h << std::endl;
  h = XXH32(a, sizeof(a), 0);
  std::cout << "hash(a) = " << h << std::endl;
}
```

results in the output:
```sh
hash(v) = 949155633
hash(d) = 4089149075
hash(a) = 4089149075
```

If I check `(v.data())[0]` it is indeed equal to `1`, and `v.size()` is also `1` as expected.
Why is the vector hashed to a different value?

**Comment by Cyan4973** [comment]
`v.size()` is the nb of elements in the vector,
not the size of the content.

Content size is actually `v.size() * sizeof(int)`.

**Comment by hros** [comment]
of course.... don't know how I missed it
thanks for the quick answer
