### ISSUE TITLE
`PATH=$(PATH)` in Makefile must be fixed

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#764]
Typical WSL environment `$(PATH)` may contain ` ` (space, 0x20) and/or `(`. For example

```
PATH=...:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:...
```

And it causes the following error

```
/bin/sh: 1: Syntax error: "(" unexpected
```

Therefore, we need proper escaping for these special characters.

**Comment by Cyan4973** [comment]
In which scenario is this a `xxHash` concern ?

**Comment by t-mat** [comment]
Ugh.  Sorry.  I've written about [`lz4/tests/Makefile`](https://github.com/lz4/lz4/blob/8a31e6402df11c1bf8fbb1db3b29ec2c76fe6f26/tests/Makefile#L217).  But here's xxHash... 😓
