### ISSUE TITLE
GH-Actions: QEMU and compiler matrix test are broken

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/xxHash#766]
Currently, almost all expression for platform detection is written with `==`

```
    - name: ARM64 (XXH_VECTOR=[ scalar, NEON, SVE ])
      if: ${{ matrix.name == 'ARM64' }}
```

But it must be replaced with `startsWith()`

```
    - name: ARM64 (XXH_VECTOR=[ scalar, NEON, SVE ])
      if: ${{ startsWith(matrix.name, 'ARM64,') }}
```

Because our `name` format is `PLATFORM, compiler`, first entry passes the condition but all other entries are skipped.

```
  qemu-consistency:
    strategy:
      matrix:
        include: [
          { name: 'ARM64',           ... },
          { name: 'ARM64, gcc-10',   ... },
          { name: 'ARM64, gcc-9',    ... },
```

**Comment by t-mat** [comment]
First of all, this is my mistake :facepalm:.

I made potential patch for `ci.yml` : https://github.com/t-mat/xxHash/commit/e6bee1dd9fe9b7304f89b376b613883627ee331c
and here's its full test log https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029038872

We also need

- Investigate platform=S390X, XXH_VECTOR=VSX
- Investigate platform=ARM64, XXH_VECTOR=SVE

**Comment by t-mat** [comment]
As for "S390X, VSX", some versions are failed, but other versions pass the test.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/898396/204806896-707b6eea-a32d-4efd-82c3-a9a568247ceb.png">

For example, in above case, `gcc-8` pass the test.
- gcc-8 : https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029045125#step:10:303

But `gcc-10` failed
- gcc-10 https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029043494#step:10:303

Perhaps, QEMU and/or gcc may have issue.

**Comment by t-mat** [comment]
## QEMU ARM64 : Summary

I think it's okay to disable ARM64/SVE test for old `gcc` and `QEMU`s.  Because they won't have further support or fix.

Errors:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/898396/204812951-a0b692fe-76b1-4c89-99cc-9bf2fa27bdbf.png">
https://github.com/t-mat/xxHash/actions/runs/3583516752

## QEMU ARM64, gcc-6

SVE isn't supported.  Must be disabled.

https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029046660#step:8:579

```
xxhash.h:3192:6: warning: #warning "__ARM_FEATURE_SVE isn't supported. Use SCALAR instead." [-Wcpp]
 #    warning "__ARM_FEATURE_SVE isn't supported. Use SCALAR instead."
```

Older verison of QEMU doesn't support `max` as a CPU model.

https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029046660#step:8:589

```
qemu-aarch64-static -cpu max,sve128=on,sve256=off,sve512=off,sve1024=off,sve2048=off ./xxhsum < xxhash.c
unable to find CPU model 'max'
```

## QEMU ARM64, gcc-7

Same as `gcc-6`

https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029045652#step:8:579

```
xxhash.h:3192:6: warning: #warning "__ARM_FEATURE_SVE isn't supported. Use SCALAR instead." [-Wcpp]
 #    warning "__ARM_FEATURE_SVE isn't supported. Use SCALAR instead."
```

https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029045652#step:8:589

```
qemu-aarch64-static -cpu max,sve128=on,sve256=off,sve512=off,sve1024=off,sve2048=off ./xxhsum < xxhash.c
unable to find CPU model 'max'
```

## QEMU ARM64, gcc-8

It seems linker (script) issue.

https://github.com/t-mat/xxHash/actions/runs/3583516752/jobs/6029044732#step:8:33

```
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/lib/../lib/libc.a(abort.o): in function `abort':
(.text.unlikely+0x48): undefined reference to `__aarch64_cas4_acq'
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: (.text.unlikely+0xd4): undefined reference to `__aarch64_swp4_rel'
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: (.text.unlikely+0x118): undefined reference to `__aarch64_cas4_acq'
/usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/gcc-cross/aarch64-linux-gnu/8/../../../../aarch64-linux-gnu/lib/../lib/libc.a(libc-start.o): in function `__libc_start_main':
(.text+0x338): undefined reference to `__aarch64_ldadd4_acq'
```

**Comment by Cyan4973** [comment]
> I think it's okay to disable ARM64/SVE test for old `gcc` and `QEMU`s. Because they won't have further support or fix.

I agree

**Comment by t-mat** [comment]
#785 resolved this issue.
