### ISSUE TITLE
ubuntu 18.04 will bu unsupported in GitHub

### ISSUE THREAD

**Issue by hzhuang1** [Cyan4973/xxHash#768]
The ubuntu 18.04 Actions runner image will be unsupported by 2023/04/01 (https://github.com/actions/virtual-environments/issues/6002). And it's also used in current CI to support gcc lower version. Do we need to remove them from current CI?

**Comment by Cyan4973** [comment]
Is it so urgent to remove these images ?

**Comment by t-mat** [comment]
@hzhuang1 Thanks for the heads up.
I think it's okay to leave `ubuntu-18.04` VM so far.
We've also discussed this issue a bit at https://github.com/lz4/lz4/issues/1137

> Is it so urgent to remove these images ?

It seems GH team didn't change their plan.  So we can open this issue as a reminder, but it's not an urgent one.
