### ISSUE TITLE
Passing keys length as compile-time constant

### ISSUE THREAD

**Issue by Carath** [Cyan4973/xxHash#770]
Hello, maybe the following question has already been asked but I couldn't find the answer...

In this project README (and in this [article](https://fastcompression.blogspot.com/2018/03/xxhash-for-small-keys-impressive-power.html)) it is said that when defining the ``` XXH_INLINE_ALL ``` symbol it is also possible to pass a key length as compile-time constant, however no symbol name (e.g like ``` KEY_LENGTH ```) is given for doing just this... Is it still possible in the current build?

**Comment by Cyan4973** [comment]
There is no need for any specific symbol name.

Just use the regular function as you would normally, such as for example: 
`hash32 = XXH32(input, len, seed);`

If `len` and `seed` are compile-time constants, 
and `xxhash.h` is integrated directly using `XXH_INLINE_ALL`,
then the constants will propagate inside the hash function at compile time,
resulting in a simplification of the function,
resulting in  improved performance.

**Comment by Carath** [comment]
Hello, that's quite nice, thank you!
