### ISSUE TITLE
How to use xxHash as the git annex backend

### ISSUE THREAD

**Issue by anikfal** [Cyan4973/xxHash#771]
My settings for `.gitattributes` is as follows:
```
* annex.backend=MD5E
**/.git* annex.largefiles=nothing
* annex.largefiles=((mimeencoding=binary)and(largerthan=0))
```
I have installed xxHash in the same conda environment that git-annex is installed. All xxHash binaries (`xxh64sum`, `xxh128sum`, ...) are available. How can I use xxHash instead of the current `annex.backend` (MD5E)?

**Comment by Cyan4973** [comment]
This seems to be a question for  git annex.

According to this documentation :
https://git-annex.branchable.com/backends/
the list of provided backends is limited, 
and none of the offered options list `xxHash`.

git annex seems to also support "External back-ends",
which, in theory, could accept some externally defined back-end, like `xxhsum`.
https://git-annex.branchable.com/design/external_backend_protocol/

But the documentation looks a bit complex, there's a mention of a protocol to respect,
so maybe there is a need to develop a wrapper around `xxhsum` to make it compatible,
and that's as far as I'm willing to go on such a topic.

I would expect git annex to have already been through several rounds of comments on the topic of external backends.
That's probably a better source of information to tap into.

**Comment by anikfal** [comment]
Yeah. I've already read those documentations, but without an effective solution to this issue.
