### ISSUE TITLE
Feature request: Test that identical hashing results are returned on different OS/architectures

### ISSUE THREAD

**Issue by pombredanne** [Cyan4973/xxHash#78]
As a follow up to http://stackoverflow.com/questions/34058947/hashing-tuple-in-python-causing-different-results-in-different-systems/37360914?noredirect=1#comment64261200_37360914 it would be great to include a few sanity test that **prove** that a hash value is the same when computed on different OSes and architectures. One possibility could be to use appveyor to run tests on Windows and QEMU on Travis to test various OS/arches. 

If this can help there is a Google Summer of Code projects and some test setup code available strace that could be used as a base for QEMU.

**Comment by Cyan4973** [comment]
When using `./xxhsum -b`, it runs, behind the scene, [a few sanity tests](https://github.com/Cyan4973/xxHash/blob/master/xxhsum.c#L415) to ensure results remain consistent across versions. This test is triggered at each commit. It's the primary tool to ensure all results remain stable after every modification.

While xxhash repo doesn't have (yet) an automated big-endian test,
[zstd has one](https://travis-ci.org/Cyan4973/zstd/jobs/145437479), and xxhash is tested there as one of its components.
[zstd](http://www.zstd.net) test suite also provides ARM tests, linux / Mac / Windows, gcc / clang / Visual / mingw / g++, 32/64 bits tests, which are definitely a lot of combinations. Here also, xxHash is embarked into all these tests, piggy-backing on zstd for its own extended test coverage.

**Comment by pombredanne** [comment]
@Cyan4973 Thanks! Feel free to close this then :P
