### ISSUE TITLE
Compare XXH128 to AES-128

### ISSUE THREAD

**Issue by ParadaCarleton** [Cyan4973/xxHash#781]
I'm interested in a comparison of XXH128 to AES with a fixed key, given that AES has hardware support on most computers nowadays. (AES isn't usually considered a hash in cryptography, but can be used as a non-cryptographic hash, since it maps arbitrary inputs to random-looking outputs.)

**Comment by Cyan4973** [comment]
Some comparisons are documented, for example in [this section](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison#testing-64-bit-non-portable-hashes-) of the wiki.

**Comment by ParadaCarleton** [comment]
> Some comparisons are documented, for example in [this section](https://github.com/Cyan4973/xxHash/wiki/Collision-ratio-comparison#testing-64-bit-non-portable-hashes-) of the wiki.

Hmm, that’s weird—all the libraries seem to be using AES as a building block, rather than just using it directly. Have you tested the hash quality if you just map a 128-bit string to another one using plain AES? AES should be indistinguishable from random for that use case.

**Comment by Cyan4973** [comment]
> Hmm, that’s weird—all the libraries seem to be using AES as a building block, rather than just using it directly. Have you tested the hash quality if you just map a 128-bit string to another one using plain AES? AES should be indistinguishable from random for that use case.

That's essentially what aquahash tries to do, and it's the worst of them.

AES is not that random. It requires multiple passes to be considered cryptographically secured. 
Multiple passes == multiple times slower.

Algorithms trying to achieve high speed with AES will naturally try to stick to single pass, but then, a single pass is not random enough, which leads to increased collisions. It must be mitigated by additional mechanisms. This is more or less well done depending on the specifics of each algorithm.

**Comment by ParadaCarleton** [comment]
> AES is not that random. It requires multiple passes to be considered cryptographically secured.

Right, so when I said AES, I meant true AES (i.e. with the default number of rounds). I know it's fast enough to be competitive as an RNG (it runs substantially faster than MT, and only about 1.5 times slower than Xoshiro256** on my PC).

**Comment by Cyan4973** [comment]
It's my understanding that the nb of AES rounds used in a AES-protected protocol is variable, and that there is a minimum amount required to get the label "cryptographic".
From memory, this minimum amount was 8 rounds, but was more recently upgraded to 13 rounds, due to advances in cipher breaking techniques.

The resulting speed can be "mechanically" derived from the faster single-round AES variants already benchmarked, and the expectation is a speed and a latency an order of magnitude slower.
