### ISSUE TITLE
GH-Actions: Publish xxhash.h header to a public NuGet gallery

### ISSUE THREAD

**Issue by claban3** [Cyan4973/xxHash#789]
I've created a NuGet package here https://www.nuget.org/packages/xxHash.Header containing only xxhash.h, with the hope of simplifying integration/version management in Visual C++ projects.

I was wondering if I could create a gh-action to automate deploying nuget updates whenever a new major release is created.

**Comment by Cyan4973** [comment]
> I was wondering if I could create a gh-action to automate deploying nuget updates whenever a new major release is created.

The general idea is "yes, that's most likely possible", but alas, I can't guide more than that as this is more a Github Actions thing.

One would need a way to detect a new release (likely not provided by Github), and from that signal, initiate build, artifact generation, and finally publication to NuGet.
Each of these steps looks "doable", but their combination in a clean package will require some work...
