### ISSUE TITLE
Can there be differences in the output for different language implementations?

### ISSUE THREAD

**Issue by db-instacart** [Cyan4973/xxHash#794]
Hello,

We're looking at utilizing some of the xxHash implementations in other languages and had a question on whether or not the language implementation from different authors could impact the output of the hash?

e.g. if we have a system using the python package https://pypi.org/project/xxhash/ and another system utilizing the go package https://github.com/zeebo/xxh3 is it safe to assume that given the same inputs for the xxh3 hashing algorithm we should expect to see the same outputs?

Thanks

**Comment by Cyan4973** [comment]
That's indeed the intention. Each algorithm within `libxxhash` is designed to produce the exact same result given the same input, whatever the platform (cpu, compiler, os). 
Compliant 3rd party implementations should feature the same property.

**Comment by db-instacart** [comment]
Thanks @Cyan4973
