### ISSUE TITLE
Question: Next release?

### ISSUE THREAD

**Issue by daj-code** [Cyan4973/xxHash#796]
Hi, thanks for providing this package!

I just wanted to quickly ask whether there was a new release planned any time soon? There's been a lot of commits to `dev` since `0.8.1`, so I was just wondering when there might be a new release containing these changes? Thanks!

**Comment by Cyan4973** [comment]
There will be a release this year,
likely this half.
Primary driver is performance improvements on ARM.
More specific than that, I can't tell (yet).

**Comment by daj-code** [comment]
Thank you, that's great
