### ISSUE TITLE
just two naive questions

### ISSUE THREAD

**Issue by uat230214** [Cyan4973/xxHash#798]
Hi,
I have been trying to get the hash of a string simply using
xxhsum.exe string (in the windows console)
with all variations trying to figure out what is indicated in the help,
such as xxhsum.exe 'string' or  xxhsum - string or xxhsum '-' string or xxhsum <string or ...
so, I am unable to find how to use stdin ... 

which is the trick here? can anyone provide a working example?
(of course if I use xxhsum filename.pfd it works...)

My second question is ... is there any way to use a custom seed?
I would like to do in my pc localy what is shown is this page - https://asecuritysite.com/hash/xxHash

Thanks!

**Comment by Cyan4973** [comment]
> I have been trying to get the hash of a string (...)
> so, I am unable to find how to use stdin ...

```
echo "string" | xxhsum
```

> is there any way to use a custom seed?

Unfortunately, this capability is only available at API level, not from the command line tool.

I would expect https://asecuritysite.com/hash/xxHash and any other similar web application to use a JS binding to the library.

**Comment by uat230214** [comment]
@Cyan4973 
Thanks for the hint!
F*ck, i must be rotting, I knew that but for some reason it eluded me.. I just fixated in the wrong approach.
Sorry for disturbing with that nuisance.
I see I have to choice, either local either with seed.
Thanks again!
