### ISSUE TITLE
Support `--ignore-missing` command-line option 

### ISSUE THREAD

**Issue by MestreLion** [Cyan4973/xxHash#811]
As `xxhsum` strives (for a good reason!) to mimic `md5sum`'s behavior and command-line API (seen a lot of issues referring to that), it would be _very_ useful to have `--ignore-missing`:

```
The following five options are useful only when verifying checksums:
      --ignore-missing  don't fail or report status for missing files
```

I use this a **lot** for situations when I have a "master" file containing known hashes and just want to test integrity of _existing_ files.

This would be a very welcome addition, and I could gladly create a PR if you approve the idea!

**Comment by Cyan4973** [comment]
Yes, that's a good idea.
