### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by wmorgan6796** [Cyan4973/xxHash#813]
I was curious if there were any plans on cutting a new release for xxhash. As a general rule, many teams can only use “released” versions of the library and there have been features released since the last release over a year ago that would greatly be appreciated (especially for those that could make use of dynamic dispatch or improved cmake integrations).

**Comment by Cyan4973** [comment]
See #796 ,
there will be a new release this year,
exact date though is not clear yet.
