### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [Cyan4973/xxHash#827]
Adding a Security Policy is important to provide guidance on how people can report any potential vulnerabilities while also ensuring awareness of the vulnerabilities disclosure timeframe.

I recently recommended https://github.com/Cyan4973/xxHash/issues/806 and, like that change, this one also considered a good-practice and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy, and we can work together to communicate how the repo can best handle vulnerability reports.

##### Additional Context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by Cyan4973** [comment]
This seems a topic worth progressing. Agreed, let's start.
