### ISSUE TITLE
Register for HTTP Digest

### ISSUE THREAD

**Issue by maartenbrock** [Cyan4973/xxHash#830]
Hi,

Are you working on getting xxHash registered as an HTTP Digest hash algorithm? See also:
https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers

**Comment by Cyan4973** [comment]
Interesting !
I wasn't aware of this draft, unfortunately.
No idea where to engage this discussion,
but it probably starts with at least one clear use case (or more) that would benefit from xxhash as an HTTP Digest.

**Comment by felixhandte** [comment]
Based on [Section 5](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers#name-hash-algorithm-consideratio)'s description of the registration criteria, we could register xxHash even though it is not cryptographically secure or standardized in an RFC.

@vanmierlo, do you have a use case where you would use xxhash in this way? Do you have a client or server in which you would implement it?

**Comment by maartenbrock** [comment]
Yes, I'm constructing a json-rpc server on an ARMv7 with NEON support that also accepts large uploaded data files for which I would like to use an efficient hash for checking file integrity.
But more generically, if HTTP sees a use for using hashes as digests then using the most efficient algorithm seems only logical.
I understand that they support MD5 and SHA1 for legacy reasons, but I need more speed which xxHash provides. xxHash is faster than all supported algorithms. And of the insecure algorithms only SHA1 has more bits in its digest than XXH3-128.

**Comment by Cyan4973** [comment]
The working group seems to have settled: 
https://datatracker.ietf.org/doc/rfc9530/

Let's note that only `sha-256` and `sha-512` are considered "active",
all other hashes are considered "deprecated", including "sha" and "md5",
likely because they are not cryptographically secure by 2024 standards.
