### ISSUE TITLE
Minecraft (Bedrock Edition) uses XXH64 for content-addressed client-side caches

### ISSUE THREAD

**Issue by dktapps** [Cyan4973/xxHash#834]
Worth mentioning on the website?

**Comment by Cyan4973** [comment]
Any public link that could be used to illustrate this use case ?

**Comment by dktapps** [comment]
It's not documented on their attributions page, but it's well-known amongst the Minecraft Bedrock custom server ecosystem.

**Comment by Cyan4973** [comment]
It would definitely be worth mentioning on the website.
However, I can't seem to find a source referencing this fact, which would be useful for the link.

**Comment by dktapps** [comment]
Their attributions page hasn't been updated for a while. I've contacted someone to get it updated. If they update it it'll appear on this page: https://www.minecraft.net/en-us/attribution
