### ISSUE TITLE
Support # comment lines in --check files

### ISSUE THREAD

**Issue by Cyan4973** [Cyan4973/xxHash#836]
`md5sum` seems to support `#` comments in `--check` files.

For better compatibility, `xxhsum` should preferably support the same capability.

**Comment by t-mat** [comment]
It seems it only recognize `#` at the beginning of the line.
All other `#`s are treated as a normal character.

https://github.com/homer6/gnu_coreutils/blob/c9f4c323220f51a42e3da8ea79f9ddcedab041b9/src/md5sum.c#L530-L532
