### ISSUE TITLE
Reg : xxsum testing

### ISSUE THREAD

**Issue by chellasundar** [Cyan4973/xxHash#84]
Good Morning.

We need test Fast Hash algorithm, So i have installed xxhsum, How to install xxhash for Fedora-24 version & CentOS - 7.2
 
Kindly advice how to install xxhash & xxHash64.
 
How to test the xxHash64 in command.

Thanks,
Chellasundar SR

**Comment by Cyan4973** [comment]
> how to install xxhash & xxHash64.

If you switch to the "dev" branch,
you can do : 
`sudo make install`

**Comment by chellasundar** [comment]
Hi Yann Collet,

Thanks for your quick response.

I have installed OS version-Fedora-24-64 bit and CentOS-7.0-64-bit version.

My File name is Digest-xxHash-2.03.tar.gz.

How to install and how to test the file and folder.

Kindly share me the document to installation and testing the files and folder.

-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----

**Comment by Cyan4973** [comment]
You don't need to install in order to test a single file.
Download / clone xxhash directory, go there, and then :

```
make
./xxhsum path/to/Digest-xxHash-2.03.tar.gz
```

**Comment by chellasundar** [comment]
Hi Yann,

[root@localhost Digest-xxHash-2.03]# make
make: *** No targets specified and no makefile found.  Stop.

We are unable to make a file. 

We need to install any RPM package.

-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----

**Comment by chellasundar** [comment]
Hi Yann,

As per trial mail, I have installed xxh64sum and xx32sum.

I need to check the entire directory.

We need every file and folder checksum value.

How to run and check the directory.


[root@localhost xxHash-master]# ./xxh
xxh32sum  xxh64sum  xxhsum
[root@localhost xxHash-master]# ./xxh64sum
Wrong parameters
./xxh64sum 0.6.2 (64-bits little endian), by Yann Collet
Usage :
      ./xxh64sum [arg] [filenames]
When no filename provided, or - provided : use stdin as input
Arguments :
 -H# : hash selection : 0=32bits, 1=64bits (default: 1)
 -c  : read xxHash sums from the [filenames] and check them
 -h  : help
[root@localhost xxHash-master]#



-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----
