### ISSUE TITLE
Release soon?

### ISSUE THREAD

**Issue by dwsteele** [Cyan4973/xxHash#843]
We (https://github.com/pgbackrest/pgbackrest) have been using v0.8.1, which we had to include in our project due to many distros not having a high enough version. We have seen some compilation failures that were fixed by ad639468 but there is no release version that includes this commit that we can pull into our project. We hesitate to pull something out of the dev branch.

@red1452 has adapted ad639468 for v0.8.1 here (https://github.com/pgbackrest/pgbackrest/pull/2096) but we would definitely prefer to have an official (and tested) release from the xxHash project.

Any chance of that happening in the near future?

**Comment by Cyan4973** [comment]
I would like a new release of xxhash to happen this year.

Time availability is the main issue.
I expect to have a bit of availability during the Summer.
Not sure yet if this will be enough.

**Comment by dwsteele** [comment]
> I would like a new release of xxhash to happen this year.

I hear you. Never enough time, is there?

We will proceed with the assumption that there will not be a release this year. Thanks!
