### ISSUE TITLE
Reg : xxsum testing

### ISSUE THREAD

**Issue by chellasundar** [Cyan4973/xxHash#85]
Hi Yann, 
As per trial mail, I have installed xxh64sum and xx32sum. I need to check the entire directory. We need every file and folder checksum value. How to run and check the directory. 
[root@localhost xxHash-master]# ./xxh xxh32sum xxh64sum xxhsum 
[root@localhost xxHash-master]# ./xxh64sum Wrong parameters ./xxh64sum 0.6.2 (64-bits little endian), by Yann Collet Usage : ./xxh64sum [arg] [filenames] When no filename provided, or - provided : use stdin as input Arguments : -H# : hash selection : 0=32bits, 1=64bits (default: 1) -c : read xxHash sums from the [filenames] and check them -h : help [root@localhost xxHash-master]#

**Comment by Cyan4973** [comment]
`xxhsum directory/*`

**Comment by chellasundar** [comment]
Hi Yann,

I have tried using below mentioned command xxhsum directory/* But it will give the same checksum value entire directory.

We have so many sub folders and files in a single source directory.

I have attached screen shot.

-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----

**Comment by Cyan4973** [comment]
Sorry, there is no "include sub-directory" command at this stage.

You'll have to create the list of files using alternate method, such as `find .`, and provide that as argument to `xxhsum`.

**Comment by chellasundar** [comment]
Hi Yann,

Thanks for your valuable support.

-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----

**Comment by chellasundar** [comment]
Hi Yann,

Good Evening.

Hope all is well.

I try to run the script using xxh32sum and xx64sum file.Its show some error message.

-bash: /root/xxHash-master/xxh64sum: Argument list too long.

Our total file is 29000 Nos.

How many numbers of files can support xxh32sum and xxh64sum script.

Any alternate opensource or paid software is available to check the checksum with sub folder and files.

Kindly find the screen shot.

-- 
Thanks & Regards,
Chellasundar SR
System Administrator
EFX - Prasad Corporation Ltd.
  ----- Original Message -----
