### ISSUE TITLE
Include SHA512 and SHA256 in collision tests?

### ISSUE THREAD

**Issue by turian** [Cyan4973/xxHash#861]
We are interested in a low collision hash (preferably for text, but any data would be fine). We are less concerned with speed.

Could you include SHA512 and SHA256 in your benchmarks?

**Comment by t-mat** [comment]
Since our collisions test is designed for up to 128-bit hash, it may be not suitable to test the actual collision rate of SHA256 or greater.

In general, if you just need lower collision rate, you should use SHA512.

**Comment by Cyan4973** [comment]
I tested `sha256` for speed, and the low 64-bit for collisions.

As could be expected, this cryptographic hash is _very_ slow, and the nb of collisions is fine, consistent with the birthday paradox.

Therefore, no surprise. 
I'm not eager to extend the tests to `sha512`, given how horribly slow was already this round of tests.
