### ISSUE TITLE
`restrict` keyword used in header breaks some C++ inclusion

### ISSUE THREAD

**Issue by mitchblank** [Cyan4973/xxHash#88]
in xxhash.h:

```
#if !(defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L))   /* ! C99 */
#  define restrict   /* disable restrict */
#endif
```

`restrict` is technically only a keyword in C, not C++ yet this header needs to be includible from either.  Most C++ compilers I guess either accept it as an extension or doesn't set `__STDC_VERSION__` incorrectly.  However, one host in my build farm (a Solaris x86_64 machine with gcc 4.7.3) is getting a compile error when this header is included from C++ code:

```
include/xxhash.h:233:61: error: expected ',' or '...' before 'dst_state'
include/xxhash.h:234:61: error: expected ',' or '...' before 'dst_state'
```

According to wikipedia https://en.wikipedia.org/wiki/Restrict 

> C++ does not have standard support for restrict, but many compilers have equivalents that usually work in both C++ and C, such as the GNU Compiler Collection's and Clang's __restrict__, and Visual C++'s __restrict and __declspec(restrict).

I'll try fixing it tomorrow, but I'll probably do something like:

```
#ifdef __cplusplus
#  if defined(__GNUC__) || defined(__clang__)
#    define XXH_RESTRICT __restrict__
#  elif defined (_MSC_VER)
#    define XXH_RESTRICT  __restrict
#  endif
#else
#  if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)   /* C99 */
#    define XXH_RESTRICT restrict
#  endif
#endif
#ifndef XXH_RESTRICT
#  define restrict   /* disable restrict */
#endif
```

I think defining an xxhash-specific macro like `XXH_RESTRICT` is less intrusive than potentially defining `restrict` which might affect how system headers, etc, are interpreted.

**Comment by Cyan4973** [comment]
Thanks for feedback.

It's also possible to remove `restrict` which use case within `xxhash` is extremely limited.
That would reduce complexity.

**Comment by Cyan4973** [comment]
`restrict` removed from source

**Comment by mitchblank** [comment]
I can confirm my previously failing environment builds after the 386a634f787ba728ef0aa50601514db74cf3b3f4 change
