### ISSUE TITLE
kernel support?

### ISSUE THREAD

**Issue by Nitr0-G** [Cyan4973/xxHash#885]
Hello everyone!
I would like to know if xxHash has Ring0 support(windows) and if so, in which IRQL levels can the XXH64 function be called?

**Comment by Cyan4973** [comment]
`XXH64()` is running as part of the Linux Kernel.

**Comment by Nitr0-G** [comment]
> `XXH64()` is running as part of the Linux Kernel.

I apologize for the stupid question, I just didn't find any mention of kernel anywhere, and I only looked at the Linux code a couple of times ;)
