### ISSUE TITLE
Resolved: 'make test' fails in Fedora 38

### ISSUE THREAD

**Issue by jccleaver** [Cyan4973/xxHash#888]
<Removing -- sorry for the misread. g++ was missing>

**Comment by Cyan4973** [comment]
FYI,
following the [GNU guidance for Standard `make` Targets](https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html),
`make check` runs a more reduced set of tests, focused more strictly on the library `libxxhash` and the `xxhsum` CLI,
which avoids any need of `g++`.

`g++` is only needed by some advanced testing tools, not part of the library proper.
