### ISSUE TITLE
Why called XXH?What does XX mean?

### ISSUE THREAD

**Issue by yw920** [Cyan4973/xxHash#899]
I guess that "H" means "Hash", but What does XX mean? it is only a name or have other meaning?

**Comment by Cyan4973** [comment]
It's a play on XXL

**Comment by easyaspi314** [comment]
Here I was assuming it named after two multiplies in the original algorithm, similar to shishua, xorshiro, or murmur. Interesting.

**Comment by yw920** [comment]
well, I see..
