### ISSUE TITLE
MAX OS X issue with vcpkg 

### ISSUE THREAD

**Issue by Jinyaox** [Cyan4973/xxHash#900]
I followed the vcpkg rule to build the whole file. And I tried to use the library by doing 

#include "xxhash.h"

However, it gives me a path not found error (I guess it's not in usr/bin or so). So I went into the vcpkg folder and included the absolute path for the xxhash.h inside the installed

Undefined symbols for architecture x86_64:
  "_XXH32", referenced from:
       random_test-40ecb6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I wonder what is the correct path inclusion way?

**Comment by t-mat** [comment]
Hi @Jinyaox,

Unfortunately, we don't maintain any `vcpkg` related configurations or tutorials.
Therefore, we have no idea at all.

Please ask vcpkg team directly.

**Comment by Jinyaox** [comment]
So if I clone the repo directly and do make (by default), including the xxhash.h should be working right? It produces the same error. I wonder what is the build process for the repo for x86 based MAC OS?

Or should I use ubuntu or Windows 10 instead?

**Comment by t-mat** [comment]
> So if I clone the repo directly and do make (by default), including the xxhash.h should be working right?

Yes, it should work.

> I wonder what is the build process for the repo for x86 based MAC OS?

I'm not sure about x86 mac, but at least the following standard `make install` command works on my ARM64 macbook today.

```
cd
git clone https://github.com/Cyan4973/xxHash.git -b v0.8.2
cd xxHash
git log -1
make
make install  # Perhaps, you may need `sudo`
ls -l /usr/local/lib

cc --version
# Apple clang version 14.0.0 (clang-1400.0.29.202)
# Target: arm64-apple-darwin22.4.0

curl -LOJ https://gist.githubusercontent.com/t-mat/78eefcbb1ccb047cc12791e07035d481/raw/xxhash-hello.c
cat xxhash-hello.c
cc xxhash-hello.c -lxxhash
./a.out
```

> Or should I use ubuntu or Windows 10 instead?

No.  xxHash should work fine on macos.  Actually, Cyan4973 has been using macos.

**Comment by Jinyaox** [comment]
it's all good. Using make creates dylib for Mac and I did not include the lib's to my usr/local/lib path which makes the linker cannot find the symbol. After done so, it'll good.
