### ISSUE TITLE
XXH3_128bits Android armeabi fail

### ISSUE THREAD

**Issue by sisong** [Cyan4973/xxHash#905]
I used XXH3_128bits on android, .so ABI armeabi-v7a\arm64-v8a\x86\x86_64 all run checksum ok;
but only .so ABI armeabi fail, checksum value not equality.

armeabi:
  __ARM_ARCH==5 && no thumb2  && memory access need align  && no neon

**Comment by Cyan4973** [comment]
Can you ensure that compared versions are all >= v0.8.0 ?

**Comment by sisong** [comment]
I test release v0.8.2  and the newest dev

**Comment by Cyan4973** [comment]
Given the same input, the same algorithm and same seed,
the result should be identical, no matter the underlying architecture.

We have a few verification tests that check this property:
a small one integrated within `xxxhsum`,
and a more involved one prepared by @t-mat in the `tests/` subdirectory : 
`make -C tests test_sanity`.

Is that what you tried ?

**Comment by sisong** [comment]
I haven't run xxsum or test_sanity.
I hash a data on my PC; When checking it on an Android phone, armeabi-v7a\ arm64-V8A ok, but armeabi failed(not crash).

**Comment by Cyan4973** [comment]
>  but armeabi failed(not crash).

What do you mean by fail ? wrong checksum value ?

**Comment by sisong** [comment]
same data, wrong checksum value

**Comment by sisong** [comment]
armeabi .so print out XSUM_ARCH : "ARMv5 Thumb-1"

**Comment by Cyan4973** [comment]
Ideally, we should be able to emulate a similar system using `qemu`.
Do you have any experience on this topic ?

**Comment by sisong** [comment]
I have an arm64 linux mcu, maybe can make(-march=armv5s?) & run tests.   

(qemu:   I installed big-endian powerpc & mips & riscv  for test; but  no arm, because have phone for test, not need qemu)

**Comment by Cyan4973** [comment]
I have tested a hopefully equivalent cpu to yours using the following cross-compiler : 
```
CC=arm-linux-gnueabi-gcc -march=armv5t -mtune=arm926ej-s -marm -mfloat-abi=soft
```
resulting in the production of the following binary : 
```
❯ ./xxhsum -V
xxhsum 0.8.2 by Yann Collet
compiled as 32-bit ARMv5 little endian with GCC 9.4.0
```
It passes all validation tests (all hashes tested are correct).

Other possibilities include: 
- The emulation is not exactly identical, one would require some additional flags to get closer to goal
- The error is specific to one specific payload. In which case, sharing the payload to test would be helpful.
- The target hardware equipment might be faulty
- Something else, in the software environment around `xxhash`, is corrupting or incorrectly interpreting xxhash data.

**Comment by sisong** [comment]
I call XSUM_sanityCheck() on android, build xsum_sanity.c by Android NDK 16.1.4479499, only changed XSUM_log func.

run on arm64-v8a:
```
xsum_sanity_on_android 0.8.2 by Yann Collet  compiled as 64-bit aarch64 + NEON little endian with Clang 5.0.300080                                                                      
Sanity check -- all tests ok
```

run on armeabi-v7a:
```
xsum_sanity_on_android 0.8.2 by Yann Collet  compiled as 32-bit ARMv7 Thumb-2 + unaligned little endian with Clang 5.0.300080  
Sanity check -- all tests ok
```

run on armeabi:
```
xsum_sanity_on_android 0.8.2 by Yann Collet  compiled as 32-bit ARMv5 Thumb-1 little endian with Clang 5.0.300080  
Error: 64-bit hash test 23: Internal sanity check failed!
Got 0x5DF4AFD6B7E3F0CCULL, expected 0xB641AE8CB691C174ULL.
Note: If you modified the hash functions, make sure to either update the values or temporarily recompile with XSUM_NO_TESTS=1.
```
   
(test on others 3 mobile phones, same log out)

**Comment by Cyan4973** [comment]
OK, now we have a clear test results to reproduce,
let's try to recreate the same conditions with `qemu`, 
once that's achieved, debugging will become possible.

**Comment by sisong** [comment]
NDK armeabi arch is armv5te ？
> -march=armv5t

**Comment by Cyan4973** [comment]
Tested a new cross-compilation target that seems closer to the one you describe:
```
CC=arm-linux-gnueabi-gcc -march=armv5te -mtune=arm926ej-s -mthumb -mfloat-abi=soft
```
resulting in the production of the following binary :
```
❯ ./xxhsum -V
xxhsum 0.8.2 by Yann Collet
compiled as 32-bit ARMv5 Thumb-1 little endian with GCC 9.4.0
```

The important new detail is the `Thumb-1`, which wasn't present previously.

Still, even this binary passes all validation checks....

Also worth mentioning: I'm getting the following warning during compilation:
`warning: #warning "XXH3 is highly inefficient without ARM or Thumb-2."`

**Comment by sisong** [comment]
I changed NDK builder, from deafult clang to GCC4.9(NDK_TOOLCHAIN_VERSION:=4.9), all tests are passed!
```
xsum_sanity_on_android 0.8.2 by Yann Collet  compiled as 32-bit ARMv5 Thumb-1 little endian with GCC 4.9.x 20150123 (prerelease) 
Sanity check -- all tests ok
```

**Comment by Cyan4973** [comment]
so apparently a compiler issue ?

**Comment by sisong** [comment]
yes，a compiler issue   
I want to know why

**Comment by sisong** [comment]
I close clang optimize by -O0, then all test passed!   
reset to -Os, and close some function optimize by `#pragma clang  optimize on|off` to find the first fail;   
found it's at func `XXH64_mergeRound()`;   
then changed the func's code to 
```
#pragma clang  optimize off
static xxh_u64 _bad_xor_(xxh_u64 acc,xxh_u64 val){
    acc ^= val;
    return acc;
}
#pragma clang  optimize on

static xxh_u64 XXH64_mergeRound(xxh_u64 acc, xxh_u64 val)
{
    val  = XXH64_round(0, val);
    acc = _bad_xor_(acc,val);
    acc  = acc * XXH_PRIME64_1 + XXH_PRIME64_4;
    return acc;
}
```
then the first fail, now passed; so this is a compiler issue.

**Comment by easyaspi314** [comment]
I believe this may actually be related to XXH_FORCE_MEMORY_ACCESS. Clang tends to be a little too cheeky with ARM.

**Comment by sisong** [comment]
@easyaspi314

Not because of XXH_FORCE_MEMORY_ACCESS;
Before I created this issue, I tested that XXH_FORCE_MEMORY_ACCESS equals 0,1,2,3 respectively, and neither can be fixed.
