### ISSUE TITLE
add BLAKE3 to benchmark

### ISSUE THREAD

**Issue by divinity76** [Cyan4973/xxHash#918]
BLAKE3 is a very fast cryptographic hash: https://github.com/BLAKE3-team/BLAKE3/
On your benchmark with i7-9700K, I suspect it will be faster than Murmur3 and slower than City32 for 1 core
here is the official benchmark:
![](https://raw.githubusercontent.com/BLAKE3-team/BLAKE3/master/media/speed.svg)
and here is some of my own for AMD Ryzen 9 7950x:
![image](https://github.com/php/php-src/assets/1874996/c759ac1e-530b-403e-b312-6ddd68508902)
and here is one for Oracle Cloud's cheapest ARM VPS VM.Standard.A1.Flex
![image](https://github.com/php/php-src/assets/1874996/f6cb0d13-2197-4588-b7d3-aabb9fd2b779)

**Comment by Cyan4973** [comment]
I'm testing `blake3` "portable" at the moment,
and from what I can see,
it has slightly slower throughput than `blake2`.
Though it seems to offer better latency on small data.

**Comment by Cyan4973** [comment]
Blake3 `sse2` and `avx2` were already measured, and reported on the [wiki performance comparison page](https://github.com/Cyan4973/xxHash/wiki/Performance-comparison)

**Comment by divinity76** [comment]
@Cyan4973 thanks, are those from the c intrinsics versions, or the hand-written assembly versions? (Fwiw the hand written assembly versions are faster)

**Comment by Cyan4973** [comment]
Probably c intrinsics. I haven't checked the exact code path. Just using the `c` files in the `blake3` repository.
