### ISSUE TITLE
Add t1ha to speed/quality comparison table

### ISSUE THREAD

**Issue by leventov** [Cyan4973/xxHash#92]
https://github.com/leo-yuriev/t1ha/issues/1

**Comment by Cyan4973** [comment]
mmmh, I no longer have access to the machine which created these benchmark figures, so I would have to run them again on a new configuration (and thus restore or update some smHasher benchmark modules).

An important point though is that these benchmarks were run on a 32-bits platform.
64-bits code pay a significant cost when run on 32-bits.
This situation is more common than it sounds, as even on 64-bits platforms, many sub-components and applications still run in 32-bits mode (Python, javascript, ruby, etc.)

For a more complete and up to date comparison, I would suggest to have a look at @aras-p 's excellent analysis : [Hash-Functions-all-the-way-down](http://aras-p.info/blog/2016/08/02/Hash-Functions-all-the-way-down/)

**Comment by alphaonex86** [comment]
If you need access to ARMv6, ARMv7, ARMv8 just ask me ;) I'm always happy to help you.

**Comment by leo-yuriev** [comment]
@alphaonex86, could you check https://github.com/leo-yuriev/t1ha (xxHash is included for comparison) and publish the results?

Just `git clone` and `make bech` are required.

On the other hand, I will be grateful for any improvements to the [processor ticks measurement code](https://github.com/leo-yuriev/t1ha/blob/master/tests/mera.c), especially for ARM, ARM64 and MIPS. Once stabilized, it will become a separate library.

**Comment by alphaonex86** [comment]
Hi,

You can rent a cheap ARM VPS o buy an RPI3 to do this test.
PS: In my case I need endianess independent.

Cheers,
