### ISSUE TITLE
Pip installation on Fedora23

### ISSUE THREAD

**Issue by patriczek** [Cyan4973/xxHash#95]
Hi,

i tried install xxHash via pip and i get error:

`Collecting xxhash
  Using cached xxhash-0.6.1.tar.gz
Building wheels for collected packages: xxhash
  Running setup.py bdist_wheel for xxhash ... error
  Complete output from command /bin/python35 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k2nynhgm/xxhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpv4u1_b9wpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'xxhash' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/xxhash
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DVERSION=0.6.1 -I/usr/include/python3.5m -c python-xxhash.c -o build/temp.linux-x86_64-3.5/python-xxhash.o -std=c99 -O3 -Wall -W -Wundef -Wno-error=declaration-after-statement
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for xxhash
  Running setup.py clean for xxhash
Failed to build xxhash
Installing collected packages: xxhash
  Running setup.py install for xxhash ... error
    Complete output from command /bin/python35 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k2nynhgm/xxhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-trdp7asl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/xxhash
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DVERSION=0.6.1 -I/usr/include/python3.5m -c python-xxhash.c -o build/temp.linux-x86_64-3.5/python-xxhash.o -std=c99 -O3 -Wall -W -Wundef -Wno-error=declaration-after-statement
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/bin/python35 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-k2nynhgm/xxhash/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-trdp7asl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-k2nynhgm/xxhash/`

**Comment by ifduyue** [comment]
Hello, 

Please try again after `dnf install redhat-rpm-config`

**Comment by patriczek** [comment]
Thank you so much! It's work now.
