### ISSUE TITLE
How to handle error with xxhash?

### ISSUE THREAD

**Issue by YunchengLiu** [Cyan4973/xxHash#951]
Thank to this great library for providing high-quality hash algorithm implementation.
I would like to ask if there was an error during the initialization/hash calculation process, such as an API return value equal to `XXH-ERROR`. If there is no targeted processing and instead continues to call subsequent APIs, what will the behavior of this library be? Is it an undefined behavior?

**Comment by Cyan4973** [comment]
Yes, it is undefined behavior.

**Comment by YunchengLiu** [comment]
thanks!
