### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [Cyan4973/xxHash#96]
Sorry to bother you, but why there are no binaries yet?
I would appreciate stepping into the future with xxHash for Windows x64 on board.
There are many *.iso, *.mkv, etc waiting to be processed with your rapid checksum gem.

**Comment by Cyan4973** [comment]
We don't have Windows-based CI for xxHash project yet.

This is a task that will have to be completed before expecting automatic generation of Windows Binaries for Releases.

**Comment by sergeevabc** [comment]
This is strange. xxHash is out there for years, author’s page lists dozen of implementations, there is even optimized [202 lines of Windows-ready code][1] to compile. Yet it remains out of reach for ordinary people. 
[1]: http://create.stephan-brumme.com/xxhash/

**Comment by sergeevabc** [comment]
Tried to compile with [Tiny C Compiler][1].
However the resulting file crashes while calculating the checksum 
```
tcc xxhash.c xxhsum.c -o xxh.exe
xxh.exe somefile
```
[1]: http://bellard.org/tcc/

**Comment by Bulat-Ziganshin** [comment]
since TCC isn't optimizng, i foresee a lot of crying why xxh isn't as fast as advertized :)))

**Comment by Cyan4973** [comment]
I used to play and test with [TCC](http://bellard.org/tcc/) several years ago.

Unfortunately, this compiler is too buggy to be a valid target.
In particular, the 64-bits code generation was problematic.
It seems it still is.

**Comment by Cyan4973** [comment]
I added a version of `xxhsum` compiled with Visual Studio 2013 as attached file to current release (`0.6.2`).
The operation is manual, and I was lucky to have a Windows PC available to do it.

**Comment by alphaonex86** [comment]
Note: I compil Ultracopier with mingw under wine on my server

**Comment by sergeevabc** [comment]
@Cyan4973, mere Windows user are eager to try out XX3 as well. Consider adding the binary, please.

**Comment by Cyan4973** [comment]
I'm okay with providing Windows binaries,
the only issue is that, in term of usage, `xxhsum` will not give much.
The only part of `XXH3` integrated into `xxhsum` is the benchmark module (`-b`).
But it can't be used to generate hash values, since the format is not stable (yet).

**Comment by Cyan4973** [comment]
2 Windows binaries have been added to the Release tab,
one `SSE2` and one `AVX2`.
Hopefully, at least one of them will run on your target system.
Both are `x64`, I was not successful at generating 32-bit binaries so far.

**Comment by easyaspi314** [comment]
I should probably set up a CPU dispatcher like I did in XXH32a. Of course, I don't have an AVX2 chip, but I can write the test code and have like you test it. That way we don't need special binaries.
