### ISSUE TITLE
Streaming Java implementation of XXH3

### ISSUE THREAD

**Issue by oertl** [Cyan4973/xxHash#961]
Hey! Version 0.18.0 of [hash4j ](https://github.com/dynatrace-oss/hash4j) was just released and features a streaming version of XXH3 implemented in Java. The implementation has been thoroughly tested against your C reference implementation. It would be great if you would also list it on the xxHash homepage.

**Comment by Cyan4973** [comment]
Great work @oertl !
`hash4j` reference added
