### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [Cyan4973/xxHash#965]
Dear @Cyan4973,

Can you create a new version?

Already more one year since the last one: 0.8.2 (2023-07-21):
- https://github.com/Cyan4973/xxHash/releases

Thanks in advance.

**Comment by Cyan4973** [comment]
Any particular reason you are looking for a new release ?

**Comment by shepmaster** [comment]
0.8.2 does not contain the fix for `XXH3_128bits_withSecretandSeed` from #894. In my [Rust implementation](https://github.com/shepmaster/twox-hash), I want to compare against (a tagged version of) xxHash. My in-progress implementation of XXH3_128 fails these comparison tests because I produce the value found in the `dev` branch, not the value found in 0.8.2.

Releasing 0.8.3 would allow me to compare against a well-known version of xxHash *and* produce correct values.

**Comment by t-mat** [comment]
#894 is definitely an issue to be fixed.  Since it minimizes future confusion.

Anyway, here is a potential issues/PRs which may be referenced in the next release:
https://github.com/Cyan4973/xxHash/issues?q=created%3A%3E%3D2023-07-21+

**Comment by scribam** [comment]
@Neustradamus xxHash v0.8.3 is out! https://github.com/Cyan4973/xxHash/releases/tag/v0.8.3

**Comment by Neustradamus** [comment]
@scribam: Thanks for this news!

Good job @Cyan4973, thanks!

**Comment by Neustradamus** [comment]
@Cyan4973: Do you plan a new version of lz4 and zstandard too? It will be good too.
-> Debian 13 will be freezed soon.

**Comment by Cyan4973** [comment]
> @Cyan4973: Do you plan a new version of lz4 and zstandard too? It will be good too. -> Debian 13 will be freezed soon.

maybe Zstandard. Depends on what "soon" means.

**Comment by Neustradamus** [comment]
@Cyan4973: lz4 has changes too since latest build (6 months early).

You can see here: https://lists.debian.org/debian-devel-announce/2024/12/msg00001.html

The first steps is for 2025-01-12, like every releases:
- Debian 10: https://release.debian.org/buster/freeze_policy.html
- Debian 11: https://release.debian.org/bookworm/freeze_policy.html
- Debian 12: https://release.debian.org/bullseye/freeze_policy.html
- Debian 13: https://release.debian.org/testing/freeze_policy.html

**Comment by Cyan4973** [comment]
January 12th is a bit short for a new zstd release,
I wouldn't plan for such an outcome.

**Comment by Neustradamus** [comment]
@noahfx: What is for you the latest moment to add new xxHash (0.8.3 has been released today 2024-12-20) version in Debian testing and Debian 13?
- https://tracker.debian.org/pkg/xxhash
- https://github.com/Cyan4973/xxHash/releases

@iwamatsu: What is for you the latest moment to add a new lz4 version in Debian testing and Debian 13?
- https://tracker.debian.org/pkg/lz4
- https://github.com/lz4/lz4/releases
Note: Current latest lz4 1.10.0 (2024-07-22)

@ppentchev:  What is for you the latest moment to add a new zstandard version in Debian testing and Debian 13?
- https://tracker.debian.org/pkg/libzstd
- https://github.com/facebook/zstd/releases

**Comment by ppentchev** [comment]
On Mon, Dec 30, 2024 at 10:41:44AM -0800, Neustradamus wrote:
> @noahfx: What is for you the latest moment to add new xxHash (0.8.3 has been released today 2024-12-20) version in Debian testing and Debian 13?
> - https://tracker.debian.org/pkg/xxhash
> - https://github.com/Cyan4973/xxHash/releases
> 
> @iwamatsu: What is for you the latest moment to add a new lz4 version in Debian testing and Debian 13?
> - https://tracker.debian.org/pkg/lz4
> - https://github.com/lz4/lz4/releases
> Note: Current latest lz4 1.10.0 (2024-07-22)
> 
> @ppentchev:  What is for you the latest moment to add a new zstandard version in Debian testing and Debian 13?
> - https://tracker.debian.org/pkg/libzstd
> - https://github.com/facebook/zstd/releases

I have to admit I don't understand the lz4 and libzstd questions;
the latest upstream versions are already packaged in Debian.

G'luck,
Peter

-- 
Peter Pentchev  ***@***.*** ***@***.*** ***@***.***
PGP key:        https://www.ringlet.net/roam/roam.key.asc
Key fingerprint 2EE7 A7A5 17FC 124C F115  C354 651E EFB0 2527 DF13

**Comment by ppentchev** [comment]
On Tue, Dec 31, 2024 at 02:40:07AM +0200, Peter Pentchev wrote:
> On Mon, Dec 30, 2024 at 10:41:44AM -0800, Neustradamus wrote:
> > @noahfx: What is for you the latest moment to add new xxHash (0.8.3 has been released today 2024-12-20) version in Debian testing and Debian 13?
> > - https://tracker.debian.org/pkg/xxhash
> > - https://github.com/Cyan4973/xxHash/releases
> > 
> > @iwamatsu: What is for you the latest moment to add a new lz4 version in Debian testing and Debian 13?
> > - https://tracker.debian.org/pkg/lz4
> > - https://github.com/lz4/lz4/releases
> > Note: Current latest lz4 1.10.0 (2024-07-22)
> > 
> > @ppentchev:  What is for you the latest moment to add a new zstandard version in Debian testing and Debian 13?
> > - https://tracker.debian.org/pkg/libzstd
> > - https://github.com/facebook/zstd/releases
> 
> I have to admit I don't understand the lz4 and libzstd questions;
> the latest upstream versions are already packaged in Debian.

Or wait, did you mean how late can a new upstream version be released and
still be in time for inclusion in Debian 13? Well, the Debian release team
have not yet set the dates for any of the freeze stages for Debian 13, so
my best guess would be "sometime in 2025, most probably the first half of
the year".

G'luck,
Peter

-- 
Peter Pentchev  ***@***.*** ***@***.*** ***@***.***
PGP key:        https://www.ringlet.net/roam/roam.key.asc
Key fingerprint 2EE7 A7A5 17FC 124C F115  C354 651E EFB0 2527 DF13

**Comment by Neustradamus** [comment]
@ppentchev: Yes, I have requested a new Zstandard and lz4 versions.

Normally, the beginning like every Debian release:
202X-01-12 - Milestone 1 - Transition and (build-)essential Freeze
202X-02-12 - Milestone 2 - Soft Freeze

About Zstandard, currently in testing it is the current latest, but for lz4 is not.

**Comment by ppentchev** [comment]
On Mon, Dec 30, 2024 at 05:28:15PM -0800, Neustradamus wrote:
> @ppentchev: Yes, I have requested a new Zstandard and lz4 versions.
> 
> Normally, the beginning like every Debian release:
> 202X-01-12 - Milestone 1 - Transition and (build-)essential Freeze
> 202X-02-12 - Milestone 2 - Soft Freeze

Right, but as I said, those dates have not yet been announced for Trixie,
so they will probably come a couple of months later.

> About Zstandard, currently in testing it is the current latest, but for lz4 is not.

Right, I misread the output of apt-cache policy; lz4 1.10.0 is
currently in experimental; I guess the maintainer wants to make sure
that the new version won't break anything.

G'luck,
Peter

-- 
Peter Pentchev  ***@***.*** ***@***.*** ***@***.***
PGP key:        https://www.ringlet.net/roam/roam.key.asc
Key fingerprint 2EE7 A7A5 17FC 124C F115  C354 651E EFB0 2527 DF13

**Comment by ppentchev** [comment]
On Tue, Dec 31, 2024 at 03:38:42AM +0200, Peter Pentchev wrote:
> On Mon, Dec 30, 2024 at 05:28:15PM -0800, Neustradamus wrote:
> > @ppentchev: Yes, I have requested a new Zstandard and lz4 versions.
> > 
> > Normally, the beginning like every Debian release:
> > 202X-01-12 - Milestone 1 - Transition and (build-)essential Freeze
> > 202X-02-12 - Milestone 2 - Soft Freeze
> 
> Right, but as I said, those dates have not yet been announced for Trixie,
> so they will probably come a couple of months later.

FWIW, the dates were announced some hours ago:

  https://lists.debian.org/debian-devel-announce/2025/01/msg00004.html

Since zstd is basically a key package (dpkg depends on it for extracing
*.deb packages), that means that the 2025-05-15 hard freeze date does
apply to it. Allow a couple of days for migration from unstable to
testing, and I'd say anything before or very near 2025-05-01 should be
fine to get into the next Debian release without the need to ask for
freeze exceptions.

G'luck,
Peter

-- 
Peter Pentchev  ***@***.*** ***@***.*** ***@***.***
PGP key:        https://www.ringlet.net/roam/roam.key.asc
Key fingerprint 2EE7 A7A5 17FC 124C F115  C354 651E EFB0 2527 DF13

**Comment by iwamatsu** [comment]
@Neustradamus , Sorry for the late reply.

About lz4, I will be uploading lz4 1.10.0 to unstable this week.

Thanks,
  Nobuhiro

**Comment by Neustradamus** [comment]
@ppentchev: Thanks for the recent announcement information :)

@iwamatsu: Nice thanks :)

@Cyan4973: Can you plan a new release build for lz4 and zstandard, you have little time to do it.

**Comment by Cyan4973** [comment]
A new release of Zstandard will be available before 2025-05-15.

The current plan is ~ February. Even if it were to slip to March, that's still fine.

xxHash v0.8.3 was just released last December.

There is currently no plan to update LZ4 beyond v1.10.0 before May this year.
