### ISSUE TITLE
printing ^M characters on strerr

### ISSUE THREAD

**Issue by timoteicampian** [Cyan4973/xxHash#968]
`xxhsum --version`
xxhsum 0.8.1 by Yann Collet
compiled as 64-bit x86_64 autoVec little endian with GCC 11.2.0

```
cat script.sh
exec &>script.log
xxhsum file
```

```
cat -A script.log
^M                                                                      ^Mf89ec9be9b6aabc0  file$
```

**Comment by Cyan4973** [comment]
try `xxhsum -q`

**Comment by timoteicampian** [comment]
> try `xxhsum -q`

works, but this option is not obvious from the --help or man description. 
Thanks anyway for the practical workaround
