### ISSUE TITLE
Add benchmark result about wyhash?

### ISSUE THREAD

**Issue by PeterRK** [Cyan4973/xxHash#980]
Wyhash is competitive now. Why not add benchmark result about it into README.
I have tested XXH3 and wyhash by SMhasher, and found XXH3 generally faster.

**Comment by Cyan4973** [comment]
I'll see what I can do, 
but this is not a benchmark focused website. Other implementations are mentioned just for context. 
Some implementations do not provide a useful context. 
Specifically in the case of `wyhash`, this hash has changed so many times after being declared "final" (what is it currently? final4?) that it's difficult to tell which version is being tested when spelling this name.
