### ISSUE TITLE
xxhsum should probably error out on closed FIFO

### ISSUE THREAD

**Issue by voltagex** [Cyan4973/xxHash#984]
After writing this I checked and md5sum also hangs! So maybe xxhsum is correct here?

```
voltagex@scratch:~$ mkfifo this_is_a_fifo
voltagex@scratch:~$ file this_is_a_fifo
this_is_a_fifo: fifo (named pipe)
voltagex@scratch:~$ xxhsum this_is_a_fifo && will_never_run
```

xxhsum "hangs" at this point

**Comment by Cyan4973** [comment]
Well, this is the expected behavior for any consumer process of a fifo without yet any producer connected.
For the consumer to start processing and end, a producer must send some data into the fifo and end, like `cat file > fifo`.
There is nothing specific to `xxhsum` here.

**Comment by voltagex** [comment]
Yeah after I wrote this I realised my mistake. I think I will filter the input list earlier to make sure any batch processing doesn't stop due to one of these in my backups.
