### ISSUE TITLE
Could someone please verify that my project does not violate license?

### ISSUE THREAD

**Issue by paulkramme** [Cyan4973/xxHash#99]
I recently imported xxhash into my project https://github.com/paulkramme/btsoot/. I am, however, unsure that i have fulfilled the license's demands. I included the xxhash in the README and put `xxhash.*` inside my repository. Is this all i have to do?

**Comment by paulkramme** [comment]
As i understand i have to include the license text also in the binary.

**Comment by Cyan4973** [comment]
Not necessarily in the binary.
In can lay in whatever could be considered a "documentation".
Nowadays, even a website complies.
I believe even a github project page would be good enough.
As long as it can "reasonably" be found, typically by providing URL in binary, or manpage, etc.

**Comment by paulkramme** [comment]
Ah, ok. I am making a wiki for my project, then there is the license in the
source files and ive just included the license text in the "license"
command... Just to be sure.

**Comment by Cyan4973** [comment]
Yes it sounds good enough to me !

**Comment by paulkramme** [comment]
Great, then will close this. Thank you for your help!
